---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 17.1.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    k8sgatewayImage:
      repository: ghcr.io/k8s-gateway/k8s_gateway
      pullPolicy: IfNotPresent
      tag: 1.2.1@sha256:7830e736192ec17039a0c6f5302d025e93cc323b15b8e74c69fcdeb895062a5b
    service:
      dns:
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
    defaultUpstreams:
      # Cloudflare
      - https://1.1.1.1/dns-query
      - https://1.0.0.1/dns-query

    k8sgateway:
      watchedResources: ["Ingress", "Service"]
      # -- list of processed domains
      domains: 
      - domain: "${BASE_DOMAIN}"
        # -- Optional configuration option for DNS01 challenge that will redirect all acme
        # challenge requests to external cloud domain (e.g. managed by cert-manager)
        # See: https://cert-manager.io/docs/configuration/acme/dns01/
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
      forward:
        enabled: false
        primary: tls://1.1.1.1
        secondary: tls://1.0.0.1
        options:
          - name: tls_servername
            value: cloudflare-dns.com

    rbac:
      main:
        rules:
          - apiGroups:
              - apiextensions.k8s.io
            resources:
              - customresourcedefinitions
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - ""
            resources:
              - services
              - namespaces
            verbs:
              - list
              - watch
          - apiGroups:
              - extensions
              - networking.k8s.io
            resources:
              - ingresses
            verbs:
              - list
              - watch
          - apiGroups:
              - gateway.networking.k8s.io
            resources:
              - "*"
            verbs:
              - "watch"
              - "list"
          - apiGroups:
              - externaldns.k8s.io
            resources:
              - dnsendpoints
            verbs:
              - get
              - watch
              - list
          - apiGroups:
              - externaldns.k8s.io
            resources:
              - dnsendpoints/status
            verbs:
              - "*"
    configmap:
      dashboard:
        enabled: false
