---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: blocky
spec:
  interval: 15m
  chart:
    spec:
      chart: blocky
      version: 17.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    k8sgatewayImage:
      repository: ghcr.io/k8s-gateway/k8s_gateway
      pullPolicy: IfNotPresent
      tag: 1.2.0@sha256:41bce7edf43b0d9a3f2ddcc4c64bbc5af2d7aaf8cd19a472e34a3981c20f059b
    service:
      dns:
        externalTrafficPolicy: Local
        loadBalancerIP: ${BLOCKY_IP}
        type: LoadBalancer
    defaultUpstreams:
      # Cloudflare
      - https://1.1.1.1/dns-query
      - https://1.0.0.1/dns-query

    k8sgateway:
      watchedResources: ["Ingress", "Service"]
      # -- list of processed domains
      domains: 
      - domain: "${BASE_DOMAIN}"
        # -- Optional configuration option for DNS01 challenge that will redirect all acme
        # challenge requests to external cloud domain (e.g. managed by cert-manager)
        # See: https://cert-manager.io/docs/configuration/acme/dns01/
        dnsChallenge:
          enabled: false
          domain: dns01.clouddns.com
      forward:
        enabled: false
        primary: tls://1.1.1.1
        secondary: tls://1.0.0.1
        options:
          - name: tls_servername
            value: cloudflare-dns.com

    rbac:
      main:
        # -- Enables or disables the ClusterRole and ClusterRoleBinding
        enabled: true
        primary: true
        clusterWide: true
        # -- Set Rules on the ClusterRole
        rules:
          - apiGroups:
              - ""
            resources:
              - services
              - namespaces
            verbs:
              - list
              - watch
          - apiGroups:
              - extensions
              - networking.k8s.io
            resources:
              - ingresses
            verbs:
              - list
              - watch
          - apiGroups:
              - apiextensions.k8s.io
            resources:
              - customresourcedefinitions
            verbs:
              - get
              - list

    configmap:
      dashboard:
        enabled: false

    cnpg:
      main:
        cluster:
          singleNode: true