apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:22RqcgdfSP+CIKJS,iv:19rig5STtJ/WRkp2r85/Kk9Mf3LSabPLqUBh0rb5ErM=,tag:7rXd4zmYHeDu8NvsO0gW5A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcUNBU0pJdG9VMnM1UXd0
            ZmRBZVZIcExuYWd1U1I2U1ZzbjFUaFMzZ1JjCk1EaDRnZnNOaEVmU2Vrako5S3pz
            anl3K3dQSFlGL2dkbG9MZWhZSWFzM1EKLS0tIEFpc3d5NTIwdE1zdzJ4QkdZR2dF
            TnRKQmRYWkdlbFZGYk1UMGpDUXdpOVUKKlZA8weVW01Af5Iq+25lhEqRO3Q6g1aD
            Vg+mMixio2XPqTD2pVH2L10PRbbjMK34woAvx1qTDMKdOovciJts3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T15:41:26Z"
    mac: ENC[AES256_GCM,data:vI/oEIlRdfuc90j2cIFnNSKhi5oGBp2mAoXABvCe2J8kC3CpQiohk7pbpg8GXozSOOJ6rsq448HCIqfpQIZSIh8+lA3SfNYYETAlt00I/tpM58onb1frEpIORtGVPog3zkdaee90/98xjXihguXTLvdalZ/LqkLngYL03WF7gyg=,iv:Hxt+a2bfyUSSmDLNcMCdq1qFMdNYd4ZcfuuY/bFA2+M=,tag:XK2S3B3NtdZky7gqh0QG7g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
