apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:by8kTCnB0XW9bBkQ,iv:AAPURt9ZpgkkLHly2t/qWKJ47z9S6qYC3QZ9Q9Lp8gk=,tag:ZcCvX4SXYu9jtT2DB/o7dA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV3d6UlZBTkJPM3VZQ05G
            TVkvSjB6VUZsTHA0aEtIa2haOFRtUUxQVEFzCjkxNVA0dHIrSnlYUWwyN0lpbGRC
            SFI0VTkvbmZHMHpLZkZFaktISnpkU28KLS0tIHU4N09mdytBMW9nRTFuZlBOeW1K
            N3hIeVh0SFJvbmhtcjJSbWx4bzhxUW8KAwN7G2D9zRGp0W5acKozUdYzPpGjrFeO
            s2MYovs3jEaGBH74cCF1eE93h6AFMmyDalOqXyIPlXt0ecikzoWFQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T23:26:05Z"
    mac: ENC[AES256_GCM,data:ZnmipK4a9/tqlzHofE/RbbNyA+W9OVy+jA2AVTooofKI6IPOLmfF0YaF4+CNBSskKrccoXbmbm7Y+DFbUUR38dyXJBK8LspXi4Z0zadzi1WfKczOpM6OpHVMk4+K/hAgniI1hj3gulnQMSuFGXw/zV3z8LuRs0LHJ7DFbPSDCYU=,iv:QiTx/sk7BzVik6uBOeFuJD6stRD2XR8Ves4yf6Qf0ok=,tag:IBJFTI3MlGAKmftocObFmQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
