apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1SZ3vw2xq9MNucnn,iv:fPhKNk000sgGvPgbrOKlYSdZBTQIUIjGwHZmCOCqBvM=,tag:0C/q01Wzn2PUDAs9AF4vRg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT1QyRWNib1FGTVF0V3NK
            bTBxVEpnc1Nsam5mR1NYV3hZQWRXclowT0JnClcvdWpPR3RsVngxSGhGRWlFaFlE
            SUNFYjBpcjFkMy8ycVlDYnJqcTRaV28KLS0tICtwWUFqWDRqbUtFbGxSVnYwUEJC
            Yk9VUWJOOVp4VmVIQ2dNMitsbHlxdzAKYdza+KGNMwfnIjKU9yXlimggNweGSKc7
            bEZZHxk06Z2n0hU1Phd1ftm8SSgD+CZLo4FDifPboOQ+d7lki3ZHNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T10:30:10Z"
    mac: ENC[AES256_GCM,data:dGI0AraFRiIv3ymswtNheaMto69lNY2ylbExpeSTg6llVszW1UN912yP5X/yoJtBWXsMjx1jiqCmcsh+T5HnqmgUolAh1xxCM6+gdM7A4IOkYgAcBJTwmVpkf8w2Q1wocb0KSlgOnsi5MxmFhi4+xOUzhBtX3acFB2T3T5XFpoU=,iv:hCFbO0kIb9EWMJeLmu5WzK4M+xwLvbQoUtRJUXUWVDc=,tag:9cQWQLK+o/qUU+yQXk5Lvw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
