apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qBQkin+IR7W32Q22,iv:HwJ8zGpz6iM1mMBuezvYO7sLI9lv1Br/0Pj2KOV+daE=,tag:j64iZVI29xc233VzvNYAMQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RndUVldZUUhjN20veVpB
            ZmJsemsxcll2UEFRYVNRQ0hESkRFWWNlWlJBCllwTjJ6L1M1Snl4MEpVRUF4djA1
            T21GYktMWEdBWkdtZy9jRkE2bHZLTmMKLS0tIHNVa3hZVUd0L2xVSkxkMm5WR25B
            TnhBLzl5RG5zVGQwR0ZLeTA2U1RUWWMKnbD1Y8CE9aFTXuV2JxPU36PY7aWNk4zi
            vt5liE7T4EvuQ9aMc9Kgawj5FyrENQOQM7+vFODWBuQAP2YZidewHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T11:30:54Z"
    mac: ENC[AES256_GCM,data:JKTngoj29ybuyMf0Wpy9NBLixn1V3OoapP8ucN+5kqSbYf3l3v9r3Vrc6cnP73pWGBrh1HKeRy0YtLaD8GYInJ7OxI6QrLHgIyEisM+A036mLqwsy8sRce4heBcMobPS3qxMY4emqe2AWqfI2u7n3mq9uKOcmkgtqklbHDkwKOY=,iv:R9redZaouSmCKV/6T0OuH0xE07jhcGsGxLeGtGTCj/c=,tag:Y1l9hPQXr5SSdbk6fDm1Yw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
