apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DfmFaroDwmB/ZMPM,iv:RPgFZw0rokjHfRC3prnfeXeyXnWELq1F6zMqVcrQm5g=,tag:KBV8ngbTmR2fw6nD/9vpBQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK0Z3MVR5UFBQN1gvUmVK
            ZUk5NDZheUJ1VTkwcXBlTkhoajZtKy9zT0hRCmEyQWVPdzU4cXVVNzNnamU3ZEJQ
            VWpGaWI1aUtCQ0xGWE1sQm5SNEtOdVUKLS0tIEJVelRlWVRFMGdaTU00eTd1eHdq
            cnhMNnFUY1JNWGdVZzNNcnUyTE5VTm8K65X1Px/GW5nbr90jvGo/WM33MGJwUczJ
            YhdLT/iD6aQMTRjefTH6AJiA0onkA4+nCUvyE0wUSvAMwjrKfh/AUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T16:07:03Z"
    mac: ENC[AES256_GCM,data:gpYJKV9bxMHYneXQhQEbJnv6+AEO4xA6CJNeS456vUuDa/a1IO4+5THSGiCax5CVbIanguneFvBdODom3+kpaQzLL76cUgueUIVfDc6cWxE/48XXkawdNYy/w8SwsgQKhmBWWTgdMVwFEKsPMrPI2jCJuAD6g+S7Hu+M2yyv0UU=,iv:V8eZ0fLa7Q07MM7CkSQZ6fACeWV31nF503Eh+sY0hE4=,tag:fMXvKgHbsJuTneO6SuRpaA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
