apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qW6afVBLzfUxUWtl,iv:yTE7aulkZHqp59+VCLt/bR4LS4Ci4bGWVnx9Aha0wYs=,tag:TLxjbvm+hDsKeCEpCnveWQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM3d4d0x1UHovdmZCMnBY
            WFlYZzRYRG96UjFvc201ZDBHeFgxM2dDOUEwCnhHMC81Vzg2WFN4M3NpVjNGY01V
            OHV2aDYzb0xJcWl0MW9ZUE5ldHpJNXcKLS0tIHlSQ2tRUnlsTWlXSGdUNzJiYklX
            bW5TNytIY1UrVjJjQnl0SEtGbmY1NEEKD68n3bskl4JG5Y9l0PNH9trS2I1yLBZy
            ZKFHL915qNesnY9V8yfWXk/Oo6gGaYX0nq2L/KykbIQlyelPG2tyrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-24T14:32:01Z"
    mac: ENC[AES256_GCM,data:wsOSuNV8sQEaLVb8F6ZsT/xUkps6ZuHkSKTzoyNhzkoTMFDZGo+5ZOQemKuJRDglaSIOQ81Ocg3Jx0GdqWq8CcaZFGfhm5ptJy+5yKlh94y9j9W1fKMQVYj8UXan9HF1bmLn0QWqGi5h3C7tQkegEMM1h3LsO6KYucIndFMHWto=,iv:hketwSI1+ceSfbkBJ+1eCv0HeUFD0JPhzf0cZdATSxQ=,tag:P6FX0hO5qWxkZaubXibGbg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
