apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterissuer
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/clusterissuer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  healthCheckExprs:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
