---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1xx2hgmxtll6gxchzszxfr0j2n2fujw3kkx3d4kktyc99ceex336seqg5m3"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1xx2hgmxtll6gxchzszxfr0j2n2fujw3kkx3d4kktyc99ceex336seqg5m3"
