apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/core/alloy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
