---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stash2
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: stash
      version: 9.2.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-stash2"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: cloudflare
        hosts:
          - host: stash2.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              cacheCapacity: 10Gi
              enabled: true
      cache:
        volsync:
          - name: cache
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              cacheCapacity: 10Gi
              enabled: true
      generated:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              cacheCapacity: 10Gi
              enabled: true
      metadata:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              cacheCapacity: 10Gi
              enabled: true
      blobs:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              cacheCapacity: 10Gi
              enabled: true
      data:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              cacheCapacity: 10Gi
              enabled: true                                        
      store:
        enabled: true
        existingClaim: media-stash2-nfs-pvc
        mountPath: "/store"
