apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippet-box
  namespace: snippet-box
spec:
  interval: 15m
  chart:
    spec:
      chart: snippet-box
      version: 9.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-snippet-box"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
            - websecure
          certManager:
            enabled: true
            certificateIssuer: cloudflared
        hosts:
          - host: snippet.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        volsync:
        - name: data
          type: restic
          credentials: s3
          dest:
            enabled: true
            moverSecurityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
          src:
            enabled: true
            trigger:
              schedule: 30 1 * * *
            moverSecurityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0