apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - media
  - metrics
  - uptime-kuma/ks.yaml
  - mealie/ks.yaml
  - homepage/ks.yaml
  - linkwarden/ks.yaml
  - freshrss/ks.yaml
