apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - media
  - metrics
  - homepage2/ks.yaml
  - uptime-kuma2/ks.yaml
  - mealie/ks.yaml
  - external-service/ks.yaml
  - homepage/ks.yaml
  - uptime-kuma/ks.yaml
