apiVersion: v1
kind: Secret
metadata:
    name: monitoring-secrets
    namespace: alloy
type: Opaque
stringData:
    externalservices-host: ENC[AES256_GCM,data:FZ4S6m9j+8FwqUWarJffQ5xnEUjviIP2Hi//BijivkcSv6USZ2AkwxllQ80y60jvpc3eOee0UhDyYlNV9nx0CJmx8g==,iv:LgBljk+IPDoLJrRuqMz1WKNB+yDhPuYErVAE6CREWsQ=,tag:7kCkLf+aApLjweklxDly2g==,type:str]
    externalservices-username: ENC[AES256_GCM,data:nrU1E1IMiw==,iv:IWmycXjHEfZdaZ+cjxu2Vb+NqHs/TUZwPLDWp4c8kd4=,tag:TbazSH1koYNFfpMSXBcOEA==,type:str]
    externalservices-password: ENC[AES256_GCM,data:EFEvijVEp6RDWrNAGHYHXRsmbNLkcknbhLxwIsE30H2dkmmZK5XhKTtRqXQZwlxubqnici1JPYI+LUxDFGm71G13BFQxrZsTLSh6sgftwwHxLeY4zADzWxoeURiCh0OPQrwmpNbUspucYRHRE54qq7XbyAcJMKquEqtoOrNu/ptj2NvFqT8Ry1udwwdXFpJmUdNZF1lvVMCTbJXO9iFtz6Pp+BAQh48ITs0SmHz+IMI=,iv:lyJ4qZ0SFjLAzTO1fuyjyGyZNd8pjT9WctIJHkzzEmg=,tag:FW7IV0NgKlMiTjamHb8DKA==,type:str]
    loki-host: ENC[AES256_GCM,data:KBuWzSsFHb9iq1ANE4FI6rJFt5QraLo5TUDdsTAlwqVGW9J5MbRipUibwL7B7CrQI2o=,iv:iJCAXpdKs5Gf8/uhLpJCLJvBPSjKIu7lJ/7u8zJNMEY=,tag:wSGEfJ+aNoEIgoZee556tA==,type:str]
    loki-username: ENC[AES256_GCM,data:IFZNj4VZLQ==,iv:JS1cOHoVK62PyJM+H2R2aP91ydVUZCKcXgX5V6Q7QgU=,tag:Ul33sUGrKcI6ouOVPy8t7Q==,type:str]
    loki-password: ENC[AES256_GCM,data:tuyH65XHAPRhr0jyYVwl9s/GQ4MGlofPHi1kfMvIE8ziPaZwBkEtz5Kz1lXyNAXtKI/MjsjqEFyNGDG0EsdatwkGjh9QIrh1bnea9w03Wma3ESqShBqImpIyLVKbyllWhQMgyTHkjC5s7BDlGPw56yxqhJQZVRgcxNWpIMi/pwTGH/WQsN5FxhADeNN1Yt92fDXd6akPamzlhaTXQB5ovbHDoH/+IYKWIuqNeC4Jdew=,iv:L7zPETxwJphQwepMbBEgKv0e6GGiSeEldfMkO0lfL2E=,tag:sEkgZKjqZnTpCnOd4um9Fg==,type:str]
    traces-host: ENC[AES256_GCM,data:3nYGT/XKZ6IMRZYN4DbBfFMegr6RtmuAY1+1jTSsqN0TAu3T2KVyvfprmy2/qAga5EmvtQ==,iv:k+UyX+go7monG0pqubU/vwtPMTu/1G/MHsfT7aEmjlQ=,tag:oIxW+TweUZBhAMlkkrntgQ==,type:str]
    traces-username: ENC[AES256_GCM,data:IQ66dZTgBA==,iv:nHuDrDjHJJVf4xlyDxpMS5fDVOkg+CK4OVaM516pUeM=,tag:gMRFeCentGR3Qg5HQEl2gQ==,type:str]
    traces-password: ENC[AES256_GCM,data:mVj0Ee8k3lLhm3NJ8TNULBkrgzWuBXt5nI5KEjV+6YmvbcPBtf4njmXNiX44/YrpCKHY1IG/RU+Kbp0Ov1lgE1k+z5/JOz/qkoxJK436LVJrwpYf4Pa6DFPmwJZOXKUagjOmIApSb04U0QYNi0ykUbDWedcyERHKxni/8cr0jBCdA66TUx+fFRuN08px52g0fuKnlhRouFgjellrDW+F8y/hfUi8iAwNd2XnA+G01p4=,iv:EYsz3NEv/Hjpn4WL92SPiekzAxp2BR+1CK02UiYn9W4=,tag:pPL3W4J9bQO1KBTrDwZ4sg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLODhwSzJDbmdjRXhLTU1k
            K29QYStIb2VmeE04K3BVbC9rMEE2U1VtMVNzCmpHNmF5SHEzT3pybE9vRFdaaUZ4
            WkNFNVVBVmFwVER1ZE1KekJNRTVCOWMKLS0tIEFNaFpzbXIwcm8ycmJZZGZ1L2VN
            ZjJ5MzMrVVZKOG9BZ1BWUG9FU1Z5U28KMhHhDq2TC94Ke2go28Fir8z0/7YmqEH6
            OWiWzLCUkI7DOUPKWzjYgwpU7oJOV4atb1mvh6jRCnkdwR/Qi4MSBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T23:40:39Z"
    mac: ENC[AES256_GCM,data:vc1vrZ0EvdlJT1aYb84Ys+6ytWU/l2rHh6BPi34hubduv08k/5vHcNiA+FaOQcatm5hOscA0cigdkwLByeqMkMvVUz5r6QZq0336cMy+1mIeYVQpRPikKSxaIKX/Uvs2cLuFNNQjalWCp2/0uoE0Cjv0dpPaGNlcGtl+CsikJb8=,iv:j5tJJtLsxdz3bhNOVKVfnZ7+qdZs/cfPB51npgql4bo=,tag:hCl5D3lKIRO+Ut8/LOh9vw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
