---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: alloy
spec:
  interval: 15m
  chart:
    spec:
      chart: k8s-monitoring
      version: 2.0.16
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    cluster:
      name: home-cluster
    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        url: ${PROMURL}
        auth:
          type: basic
          usernameKey: externalservices-username
          passwordKey: externalservices-password
        secret:
          create: false
          name: "monitoring-secrets"
          namespace: "alloy"
      - name: grafana-cloud-logs
        type: loki
        url: ${LOKIURL}
        auth:
          type: basic
          usernameKey: loki-username
          passwordKey: loki-password
        secret:
          create: false
          name: "monitoring-secrets"
          namespace: "alloy"
      - name: grafana-cloud-traces
        type: otlp
        url: ${TRACEURL}
        protocol: grpc
        auth:
          type: basic
          usernameKey: traces-username
          passwordKey: traces-password
        secret:
          create: false
          name: "monitoring-secrets"
          namespace: "alloy"
        metrics:
          enabled: false
        logs:
          enabled: false
        traces:
          enabled: true
    clusterMetrics:
      enabled: true
    prometheusOperatorObjects:
      enabled: false
    clusterEvents:
      enabled: true
    podLogs:
      enabled: true
    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
            port: 4317
          http:
            enabled: true
            port: 4318
        zipkin:
          enabled: true
          port: 9411
    integrations:
      alloy:
        instances:
          - name: alloy
            labelSelectors:
              app.kubernetes.io/name:
                - alloy-metrics
                - alloy-singleton
                - alloy-logs
                - alloy-receiver
    alloy-metrics:
      enabled: true
    alloy-singleton:
      enabled: true
    alloy-logs:
      enabled: true
    alloy-receiver:
      enabled: true
      alloy:
        extraPorts:
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
          - name: zipkin
            port: 9411
            targetPort: 9411
            protocol: TCP