apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:E9ydIwf6ptd8wxy2csKb+ozbB8upX8mQ9CPRqQuurHLEQ2TcBl4WpYJPT/buzpxUutLnziYj6XtzyNwWOAuHEufBLOHUqsknYKacrHYnbyV89bdhm9OCtDgae1nEPhtthDYhdr2tTGV4caKfgTfgBCt7KaufxS+hoQ==,iv:QbkIdP8y+BHvO0KFVYYEzXTGm6BYZnA4zeME8QWreaw=,tag:6WZC1inC8a3HpO7JM2ZQQw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VDdZR20yS0hXTE03cmVv
            cGJyTGw2UHl0ZmNUSERVYW52T0hzU05UWmxNCjZtQ3J3S3JwUXplc08yTDVNODl5
            V053Qzlid01BSlNKSlpLQ016VmRZalUKLS0tIE9IMHVvYmNoblQ5Z1phdUxzenhB
            YXBwSjMzclM4SjZKVWdoVDVDVXRtVzQK5wz9RwgiAR0o7zj01Jfs5vuywZm/RHVb
            rpUqOvlRan7N/fX/P+TKoBYX1BRa+CInhQ72g/7vbAcYO3OYIzMm2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T23:26:05Z"
    mac: ENC[AES256_GCM,data:GBPgAKkU+zJUAn42D3ITK2qZriwdZfjEPJ2A06x/IVd9obmkaRjSdqJcNCrByfmhW3jsE+HQV9HDw7I+/5DYLRvOoZt6iwm/KxeObH740tqvltib4B6O2sCQ7nOYUnTVDGbMRyD2DNWo4BwrInADmJx+sBd5c1zKt0zPp+6tnaM=,iv:4oRdIE5wrHJVYjl2plG6xyunVOS1FiTS5x0Zxd/ZHXg=,tag:GtQE+sWY6pYaY2lbaQk/pg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
