apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 69.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
      reconcileStrategy: Revision
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    nameOverride: "prometheus"
    crds:
      enabled: true
    prometheusOperator:
      enabled: true
      serviceMonitor:
        selfMonitor: true
    windowsMonitoring:
      enabled: false
    prometheus-windows-exporter:
      prometheus:
        monitor:
          enabled: false
    grafana:
      enabled: false
      forceDeployDashboards: true
      defaultDashboardsEnabled: true
    kubeDns:
      enabled: false
    prometheus:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: cloudflared
          cert-manager.io/private-key-rotation-policy: Always
          traefik.frontend.passHostHeader: "false"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - prom.${DOMAIN_0}
        paths:
          - /
        pathType: Prefix
        tls:
          - hosts:
            - prom.${DOMAIN_0}
            secretName: prometheus-tls-0
      portName: main

    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      scrapeConfigSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false