apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync
spec:
  interval: 5m
  chart:
    spec:
      chart: volsync
      version: 2.11.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    workload:
      main:
        podSpec:
          containers:
            kube-rbac-proxy:
              args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - "--tls-min-version=VersionTLS12"
                - --v=0
                - --ignore-paths=/metrics

    metrics:
      main:
        enabled: true
        type: servicemonitor
        endpoints:
          - port: metrics
            path: /metrics
            scheme: https
            tlsConfig:
              insecureSkipVerify: true
        targetSelector: metrics
