apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:nHjuWyGyRUvxRh30cpzU02E7SAS8645LsmwOIhycPZErKYyjujPHzNZyAYlbgWgaMvmmxEhJHgjFOvk82UZY8N0=,iv:LHTFvhqX323nRQeKc/tTJo6v04w0xKVt1xCJTUVtQRU=,tag:DPVJ8nIqsca4L86hGTmaLg==,type:comment]
    #ENC[AES256_GCM,data:dv9zBksulu6Z2ZYdy+iZvV9Tbjqt8mCf+miKRIl3tS8g+Vf17PaIRxY75+8=,iv:S8oaE2MLG5qJNidGgy1n/NAilPNonlGpcQswHFT5Sfk=,tag:dDYeq3JgjewAKBdTktyGdw==,type:comment]
    VIP: ENC[AES256_GCM,data:Go5A8nStcJpAPhHHi1c=,iv:+1xEk6x0d1k4rca/XtP6nJnIKx9Ki66O3oY5LT9YZCY=,tag:Xj85DlWlKdc4hH8wa0kYtQ==,type:str]
    #ENC[AES256_GCM,data:zNYQohsfYlojJW7NJS7nBlRUBjTTHaS4+zA=,iv:SxPLJzMyiCh6Pi19heq2gzdeENZwQfTdWieq0Aat9fc=,tag:CWwfkoz460/eO/A6YiZAdQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:i9xYd9zrx45vXADi,iv:ag20U8IGh5jMFh27/HHsXg4+bthZjCBA/UhX9JUSYqY=,tag:iqXILWzFFADUgE5i0Msz2Q==,type:str]
    #ENC[AES256_GCM,data:Vqmw94Ix3F5XfC7Q/5D4NBvdzysOHtwM/Qdqug5Y7Ge9BA==,iv:44uYiE8NGDNwqZkNrQ5IcPbD5T0p9R4tCNc8F4y9fhc=,tag:3VWiPsfCv8jb2BT5hPG7RQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:LsqiZDs8mE3tUJFA,iv:snxEupccCV2SvMAW0yO29e9PXxYobHmjc/0+Y9atdwY=,tag:Vi/zDmMuGAaxdam/lHqlvQ==,type:str]
    #ENC[AES256_GCM,data:yHPvgbJAEkyroax3rkUYZrgIcW09XM7j08bQv+hSFgB3/FwYWIQKzFbTRAjtHOo=,iv:7voZwFI/yBdYbrI1MgTY3HiYBSj7hILjHWOcFeS4PsU=,tag:9SZ5xXA7iD9CR5p1bJ1fxw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:jkSRkDEqPzUw7eGFoegHt2ydvMC+v5Yq5pr9E3M=,iv:KSX+scjRTCT9Om91qLNrapRpVZJEa4v9ArDgRG3hfRg=,tag:hUXmHLRwO6Xvheg91JT43Q==,type:str]
    #ENC[AES256_GCM,data:Fy/vpJbRP3nR3ScK03e4l8D8/W9V9A7tARsoSaA44dDJJYwaXWGLdEpZwN3PVrdhYsZgE/41FdCwgKYELb87pxdrsVi7xOfvlKLYDAroMso=,iv:57G48nWqDY6LWklcaalAS1wzlayPtLVvL6+xvvD+nUc=,tag:I0CQ1qNMWl/AUbTkoD97Bg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:AVpuYPNRQnCowSeQFCQ=,iv:FH2xkz++VUTdJjuM52+SWetCynjS5kWGDJX7WNgBSQw=,tag:beR9G0j6RdRp243xS78xVQ==,type:str]
    #ENC[AES256_GCM,data:h/RXIOmAOrZGK3/d9h6lKInERbXcolPd4knqhmdYL3ChYAIycD52j5EhafHHOFgLjaxBDyzPoGw=,iv:BTijMS2KbsGzUob2hl+o9bZ5tIBymSnu1MPyqzbOFPs=,tag:l8Lsr2O13cPJCrIKmB6rFA==,type:comment]
    #ENC[AES256_GCM,data:R4Qg12cETAfaHIuE5IKJLkI9HVMcV3p45w==,iv:jpUK5OvIF5ph5qMQ7bZunn37KOC25MToeapJ7w+2ikg=,tag:tEvUbj+q7Z2FcsOedKTqEw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:SjiZMEzOeQqvckfZFOy1ACazNOhIGTykQuXOqIG4cCG4qIOqMP7w99IaKubJ,iv:TK1lv/DNOufshsATwfCdoE1oeo14P6qfiqKIWtgLwKE=,tag:v+M79Jli4T2JB2/V9mZz3Q==,type:str]
    #ENC[AES256_GCM,data:HEAioc4s2nMflyUCwQ==,iv:JM31dHXSbuwj5N5sh61mYGaifnecU4SAWVHgI22ubRE=,tag:VfnIcE9dOWM3N7h+GA8GVw==,type:comment]
    PODNET: ENC[AES256_GCM,data:JEh+EF+7zXfymHOQVw==,iv:2pfPVZKJu4uCeGzS/5Scb6JPyVRBZ2LX/vKo0sLbMsQ=,tag:pRVXgGSdtaR14FaX6f3vuQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:OsJo8DV/G2L1dzi14A==,iv:FKy1Ob5DFoCIpbiDTkEMrP+uJa+f240w7YbtWkDEgTA=,tag:TbZydtQ17ue9HiGrYEmPYg==,type:str]
    BLOCKYIP: ENC[AES256_GCM,data:68CK9oEljr5SEKojVa8=,iv:uhZoZD8nuNqkpHi3tfzvHPQIR19aV98AssAsnkfmPU8=,tag:L4AFamH6Ft1xkTq9NCLPLA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:4ZfB6zFazLnMNe/+TJM=,iv:C8/TAuXC0GGqxBgTibaCgFvelMlKMiq4uqefHjfLX2I=,tag:I2a1zVAniWjJgEGDj0rPTA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:ZL0SmNgmw20=,iv:gjU1iTs+GHMUce/SyYMX1Sx6/vMekj7FFpwD45muXeA=,tag:mHS2SYDOgfSvLzgXTANcug==,type:str]
    S3URL: ENC[AES256_GCM,data:z5/HUKMUUdO3ALwrrnqKJELrlSeF6En4BPsr9qT8Hk01HDZ7is0=,iv:ZHghW9X1MGXh0VG9BOiUnlryMOCyMsuyCVil6v8MNeg=,tag:JrKsOTIzOHNCRgJYPToT+w==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:nO4YrRaVyjM929M=,iv:H6ntROEdrH8SCIh2AmtxmLDFV2y/46fIy0SE8a/Ofnk=,tag:1/mZ3HIQtJuvhPnxsQHceA==,type:str]
    S3ID: ENC[AES256_GCM,data:N+usO9JCxl8Pwupr53FoV0V1kDV7qPKmKQ==,iv:FZu6oTSYVYgVJxCqLbaZciNP63ov17fXcysp/pJQSmM=,tag:LfTWmRTFyHJ5RtvD9LwsIA==,type:str]
    S3KEY: ENC[AES256_GCM,data:T4jK/HwBmypv50qzTg8cemlYLEES9xENa+eXJLG5uA==,iv:/OLZt5VxozRQs4BUlKT2ja0F3UbKPJ2/Tfawh8HZHEk=,tag:3PzNpaYgeqc2LmMhLLlijw==,type:str]
    EMAIL: ENC[AES256_GCM,data:shShSJyuSPF/JJMCjL4Oj5Lq4r0iTXhUnQ==,iv:+sKLamnj3tLQZv9OVURNgYaHvC69pcr/XAITQy2H+V4=,tag:eqAgGxDd1r13SMQJ9+3Dsw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:mPsRgnpCRtr43+R5ncG+PpOk1dpQBA43Vr03hU9cTkbY9G6oUw6Rsw==,iv:v/qdhnG+f0JEsrpTsVMSsgKIr1S1Cw2xIjHM/IKt6+k=,tag:BES5H/Hjk60aSb1YDDvPRw==,type:str]
    HPIP: ENC[AES256_GCM,data:05o1yK74Lf8WdVen++s=,iv:2dwPJqpcH1tbkbUfDBRaq4C9CLgDkv0gpHnPDKci07M=,tag:0x7W/8Pvu3/VTuthiXB0yw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:XNTnJw==,iv:pV/cV7HGqaAI2cgvxM0/fKc+sJvYI9t2nPAnYURJvdk=,tag:cykOzWJXQpwW3BGXju2fuA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbWZrVzQvWHhTeUgyeUxs
            dmthUVhEOWd2QVd5Z1ZQbUg0c3M4Y3BkTmh3CmQ4VEthQXR0bTA2OG9jUnBnaSs0
            ZFA5dlhhaitnOU90VUp5SklFbkxheFEKLS0tIG12d2hZUmtnSDJyYUs0NmQ4TTJI
            d0xERDFrTnZBK2RFNXVNMGJNL3hjamsKYe+1VD5eVUdMRzjEmctKlwVJ5H5+h9yU
            /DpeM5Rg05hhWOquk42U0cPhg/rfvWgzDTl1iR3hHVp0dHHOMpej1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T19:50:18Z"
    mac: ENC[AES256_GCM,data:c498urtsI7b/bE/eHAPZJBvrxJ+k+tGdHlVe0Ja1HzWsCIuNrfq2Hfq7bATbtlDT/ibzDWGsEhZpPIrDk7KlD/D10Yahc55VVb1MQ2Kcf1jUDkNG7ZpQMZ15mHTp7S4DdAwyhswS05UsPzR7U5Nq7/VyHYNDBSzxT4W3hOIxdmI=,iv:XNFeh3kl2x1snKqi1JkLtSbYTlva9wxRYmykS67Fv+8=,tag:sb3xMPKqGz95UtQK5DOjmw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
