apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:VcFNsboEhzi0xcm6C3eQmGewI1ROe9GXJ08iUtFzqHr0QGGb/ONGp2PSn9LltMxJrERPJ84p9ssGK9YmQQ5iHNM=,iv:nDbKhlwDKHsIWz0WDk39Jn7SKiAuWEU3Jad+hIRnWpo=,tag:Ri+2l90DAzod+XvaLao9+A==,type:comment]
    #ENC[AES256_GCM,data:jEz9aWk++b0NTNLhzvqHmYyQBFEz0m0eiY8Mp9RNetzYYfpBhnczmzYkjV0=,iv:aieUiWw36qNz+rWczeM3SmJ26TqYIyE53zA0Rx23SGA=,tag:LbpmomK48Aux/W08AJ0cuA==,type:comment]
    VIP: ENC[AES256_GCM,data:gkuY35Ju5D1K8BU4MmI=,iv:3c26rL69PwRUyrWORQYh4tHtXQROGqBumx1bb5KT2kg=,tag:aMIQAf4kQHDIxqr2/rus2Q==,type:str]
    #ENC[AES256_GCM,data:f3Ff59nNfX8UaIM/sOalt88FHpHBXXC5rfE=,iv:G9pdxjXcVgKcN4xfYZ0/UEUsrQ81kJR2HuWJFnlKWzc=,tag:Y7CN+ORFxE1+kYA6pyuinQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:ND/VFtemZltHrVLy,iv:tZQAOb19v/nyS8RmZ3qDMgnf/DbJrKZnDC8I/tPi5Bc=,tag:k64UeriX4ArlD3qQ6dvWVw==,type:str]
    #ENC[AES256_GCM,data:puHwT1vwCHB5ia8ePQYUeWwz9rVvS5Do2fzNYalwK7LD6w==,iv:rMi3cwY1fqdB5CStqUDN4M6bs2NIgaioB2DYtcSpIVU=,tag:DDb4xHFvuBmzysSqNNN83g==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:smGBUUJ47PRs4D1A,iv:lkmxtEJZXAl60EY4uTFDHF8iXyfzDZJgBNtiidROvwk=,tag:rqK4qWOtimZqsxmJmAxlSA==,type:str]
    #ENC[AES256_GCM,data:2CXM6pMmiZLPmVyRzeQ2sI42oj9QN5bkePZGDBif51ecxfLuWSF4TB41d5EcfmQ=,iv:CfaJBrLvRzNRdIeUxpd3bTG3tKlvta0FFu4jIKnxrPQ=,tag:kjMj0yX/gVmG6DGTFmh8og==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:joyjxVQYeIBQrqjCUJO/sSl4MubBfmrcgoKIPys=,iv:CLMd0CYkghI8Kb5p6dzTw9z34Rnrjx2OPTlDp2hr7KE=,tag:hmEZ2p3bzVtNLJzD+6TU5w==,type:str]
    #ENC[AES256_GCM,data:1469IQcQUTm24syUDuzj2s0IuxVCPqVSPpf5zl53X1t9aVlCNnosVe7aPXkEmu2T1rtt/3a3oIXrtFCzRr/3ycihVnEXHpdtO89umcwRpPE=,iv:YAkMLr3J506z+YnigMukHxrU7dWKrljutPtLjP0iePw=,tag:xSRkIIHgpYbd/yoPAS4AYA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:S9S+i4OHqR5ggLIa6hM=,iv:EwJMM3n1vtBJ8kU9FI7otTyL3uvX8Z+ZvuULyV/vF+U=,tag:PEFjPQrsk9CaAVbxMUxMLQ==,type:str]
    #ENC[AES256_GCM,data:oJ24vldfOCkowxyQeS2KlcOELfglIURdw69N0hSxeWRgUocswNIm760B0LqGL5nkZSRQNT6yQ9w=,iv:Rx45JgcRyFXOaYAC0NBkNw6VbREeD9COMJQ3F9D+KOw=,tag:rTcJK8lIvSfdqw65YxSdcg==,type:comment]
    #ENC[AES256_GCM,data:Bcy2ta3X/GMco6HEdJz25J2zc8t8wKmCLg==,iv:TYZ+FfhSQ09b9bDIaWmec6qxh4wJEUoLUq+1hl6J2hg=,tag:qmC38iAENvt/QGZb3BmFLw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:xtfgDMQ5onfxDdn9IBGUFPNm9JB+SjdEQb87QwQ2s1FbNwbu7ptHS4RGCVM0,iv:l7sAYcEnJPv3NkHo+L19ian81+Wb3JOD24TrYeGLeoc=,tag:wFuz95m/SvdkD25SK3FYvQ==,type:str]
    #ENC[AES256_GCM,data:9sLCoCgLXbpnSuGJIQ==,iv:Jhsqchx3FrUV4Keq2d60vfUehg0ufRVeUPee0updiI8=,tag:PyCPULJJ7XjCbTQY4bPa8A==,type:comment]
    PODNET: ENC[AES256_GCM,data:nTmhZQ7yV1j7v940Hw==,iv:CWIJu/3zlNXRaMSJ+1/+DBsKkeMb9AiO3wPecbuV3y8=,tag:DUR1uauCU4WfQfeN0c99nA==,type:str]
    SVCNET: ENC[AES256_GCM,data:GcMwkBKeaxxnPaz0kA==,iv:QdXaZ1eJz1tZ/EqmPuVy2AeUyNUGtTudN/NxTts8flg=,tag:ntgW3xcGihO/6Kl7ClGGmQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:W6ixGL4b8UOf/hP5oZk=,iv:TJQH9PxGLjszfycDHKYqcho6h6tr9dwlXc42YEq9pTI=,tag:okoD4k3YPWug32fsKDTqaA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:W/OB1uiRCxR6rQAzKB4=,iv:slamCZMw8Xq+BMWvZUBNAUWTjdkpjEDXkwHTRqH+OP8=,tag:iB0neHYxyvGPO6RDWePfcQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:C5wFhJ/1Pxw=,iv:yK2y5IKUH5qWpVhOnLQQ1vOaomxTohP26hMiX6gArXw=,tag:dVjV9UPwQmMw+TP5O5Vzdw==,type:str]
    S3URL: ENC[AES256_GCM,data:5Xw1e8LPoTTzyxHYP5ZgCAvpMr2rL5dQDnR7SAkl50+/T5lRM1Q=,iv:WlhmNLOBEhtIYvfMKvAuzKXEczEPGDemSJVi2/k6UjU=,tag:8IOwtRY49jUZA9NbNCgQhg==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:8YfWAgVrFdPXBDI=,iv:ixxLwX/SqEWsrXIx1sMgAIJkT7hIK8BthiuEl/dBQvI=,tag:9jOkS4JPcWteK1StKBA7Pw==,type:str]
    S3ID: ENC[AES256_GCM,data:p10qKQ8vBe4Br/w/6fUa+sbgxx1DlaEzCw==,iv:l+kfhzqxs5BUk5ymTzylT2QNLxXnsBjOSmx0Xufo77w=,tag:Qi+F/yZU/SOvmrQUsqwSVg==,type:str]
    S3KEY: ENC[AES256_GCM,data:+9p5CP8YzwKozButxT4JTx3vq6RKHMc6avrXxtbmKQ==,iv:+gaHN9WC0xJKf7Cim8xT/n0Xf+ac/039KhAJalb7cXc=,tag:tif1l3GA5eotNSNhPDV+1A==,type:str]
    EMAIL: ENC[AES256_GCM,data:WONktW1TXBwzxBIy0GxHt2GrMuIaxZj1cQ==,iv:Uz+XuNWc3ELlJA+pmQzjjKptXOv/nzwKqr915uqPfA8=,tag:S9dg3QahbDfIrLUI22zPmg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:bhZabT2ig4HV6JmDMedXbTY5H0kIcpXyr7rmlqZXMHEJpgqBC9BBFQ==,iv:rSj9XbH/QV0hlqu1d3IfFH/whfoCtUZMRl81FYel3qI=,tag:XvECFKkKkYlo5PDD6QRFXQ==,type:str]
    HPIP: ENC[AES256_GCM,data:e+kBmbQAH11FYaOFxJY=,iv:8LNr1aqp7AcVZzf5dp4VvSg8uNx8Cvpx85cC0rtQFh4=,tag:C9X008ptMg5qEsgXBY1XVQ==,type:str]
    LLBASEDN: ENC[AES256_GCM,data:A1fClsUoqt3lnuWSwQ4=,iv:XYnS914ldzKOXb+I5EUUizg4u3NkKKWRuj/vRNjU7yo=,tag:o+YaFsJQ8fBds9EGpeGhCw==,type:str]
    LLUSERDN: ENC[AES256_GCM,data:oMAqFMI=,iv:VHfhHZ26g6mmjcbaRhjx0OkMwnqfWOdlN0cjDK78kBA=,tag:mXq/clxps10lvvDxf/7/sA==,type:str]
    LLUSEREMAIL: ENC[AES256_GCM,data:ieHLvFrrbZrfhILL2pgtTnYR,iv:B1kkpB6J2S8FrGDleT0d0/H0YhQcnf+oYAvbx+89Rnw=,tag:VFySPDLJQLdzAY6D2BxsdA==,type:str]
    LLUSERPASS: ENC[AES256_GCM,data:t8pjZSPyHzJPCzQS9O8SCFlk+w==,iv:r1gj799FjD4G77OOUBfsjAi8ZveY3dqPWPGmv9I27Lk=,tag:BfbwRXYi1OlsxfVHHGuB6A==,type:str]
    LLURL: ENC[AES256_GCM,data:P42m4MmEGgMguaxGQcBLQU+wMlsMwA==,iv:tCS2gKWhpYW7ARZYt5+mrMA9lvmfWnmAeSTzDu/c1Q8=,tag:KghNDNQKeKFi1WH+ED0AcQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:bDCF1w==,iv:HY6/1kzjVeL3ZG8G3huXSwXaRhWy0+X8M/aISHSU7YM=,tag:IaGwbo7RUIGNDghY5fg7Hg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS2dhTHdMUzgwMkVLYjUr
            TzBUWCtDQW9WdHEzS1dIT1c2bTVDVkNSSW5BCnJxTW84cFR0RmducXZhY3NEREFN
            RjdNRzBYMnpVSnkxbFE4OHBPMlFRb2cKLS0tIDRZOXkxVUpIanoxeGM4ZVNXeXEz
            eHNUQVQ4VEtHcXJIcVIvdXM1VmhrTjAKTyeMdyXBdZKJsOF06mcGPsLVSw4Upwqj
            hrV8v9ZMk4p6YRBKEe9UQ/0ymR3hALZ84QSivvSbMqb5DtIgUi1cNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T18:06:27Z"
    mac: ENC[AES256_GCM,data:cF4woEkRXYGgDvD3f4CaUxgTJrIYB8osOeszHwA5mna9/wkEplLPUiuSpSQbEzoMdqdbONxOLUcIzudLRAHxZlwnmnTN7/7xz4kR28dBcYSokuzfbjY1bE+SHUw8sdeEJMYJLRcP5KAgGWGRqni/ZEZu4jK97g9W2hYdt50AnFg=,iv:u+1kfwAiKNGO2NT84GPOTvF14lSo9sHhhYGDPp8w4V4=,tag:JY4ffKsOnRM+Am8Uh7MXnA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
