apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:zKg8g7gUzQgN6RM+lZnbTfTUeyO+XgFl+oXFpZWfh+CY40rtghieCzReQ5pbAqVrNkoKrx7K/CH9jIfiYwaypWk=,iv:dHCODz5Ab6hY92F+71m30qyI9F10Ro7oGnGNL4lyhi8=,tag:fR5BqNqpS96Z/gEB0nrjTA==,type:comment]
    #ENC[AES256_GCM,data:MB5PE1eYteMyNioApZ79VZR+IciolykWOFV1DwkIP138OeoUzrh1i3tSp/k=,iv:rm7cQCL/Sba3YeFJ5lYlLknOZwwNS/0S67UsxuP3jTE=,tag:YMDEV8M5iVng0ROh4lmiSA==,type:comment]
    VIP: ENC[AES256_GCM,data:/U6JOz2kQ9adPMBGOO0=,iv:JwPCEfYdKux4XUe5btfIy6HwV3cvPauDbXjq10hep+s=,tag:YfcF3qLxHopHDiBrP2sPnA==,type:str]
    #ENC[AES256_GCM,data:73Tg7XOfnSK0CtOGP6rDyFhlpp0QaOvcU7A=,iv:FX/FodvAjZpXX7f2h7xaSeE7uZ0V8QI8MaEpbLQnpvY=,tag:obBqxWmfqukuhGplueFpsQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:10PIfLs31S09H9Bv,iv:IwlWrIhhyJ2nVvX2yMw4Vsyo6+8wVZwi6jhiHUERbLw=,tag:FAZBV7klzQRPgJIHFJFj4w==,type:str]
    #ENC[AES256_GCM,data:/zk0tps+6IpJYtW81ikajG/mTIifpjC+pcjOXHV2tDZajQ==,iv:AARXoAlOm3wn2hILjYOnr8i/eq4hUqqIfyobMhnPj6c=,tag:L5J2jCEzoaIhfoF7pfBMdA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:EbP3PZt72ZUUHttd,iv:m+xxtRavPEGXDUjq9JRjeIkMFY5DK3nj/e7t74xn3sg=,tag:3IM4URXLyblrXJoFcmtK6w==,type:str]
    #ENC[AES256_GCM,data:O6bJM8jpqy9jXMD03kmKeJg/jXCZoNmbqCFUT2/kMQQ2EO2BSvDfUtqK9RjtV6I=,iv:cQgt0L7r3ChCKNg2vzXgbasFw40rRo0d7DSx24MvgXo=,tag:cUv8/g5Zxz6riNrrg71SdA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:GuF0vY69pDMeOsv5xufbjikv3X5ls2hzyqn0fiQ=,iv:sD3ADW12Fsk1RWKUx54dNzfcoMV/0w1YdwACYvcDNHA=,tag:NVIV6ZZxoQO+UUmn6CSLng==,type:str]
    #ENC[AES256_GCM,data:HWpPysTsNn3LbM6bkGPaefWedV0LDcNig1V73NuA6Thp1KCpcpYiBDalHp+oIeYuJExiK095b1dG+li6xGjcVRHwUgWCG7baRQnrEGaYspc=,iv:Ru4+gIYpLd/nSlBtsoDnv9aOUdQHN7cz5K4WedwPXGM=,tag:Eni/T9FgRfGtv6jXZ618aw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:y0N3E4Wr7tJ59YHe6uM=,iv:RICZvyxk+QIMH1SnYM/XKLCg5x6sOGtNjcrcDRwDEX4=,tag:XicJyn/ImyVOx+zIkGpN/A==,type:str]
    #ENC[AES256_GCM,data:R3bd2gsUmtL7LnM8hdMOOHUzRiYi0n69Yoy2QWMgbpeRa4alunaV2/KbDaFicHlDQjm016uWE3U=,iv:XvzHWcX8cDacl3mBBsm8Hv1RS2DEurGxpxIErnAjpNU=,tag:vb9aL4zIInQZC79wtvJGAA==,type:comment]
    #ENC[AES256_GCM,data:kjPNqyn6cb6f/3R0/o9PmBQxlnihbgg73g==,iv:+EMsG0sGTkLG9xLuktmQHDrUh9KqFv94an3A8rt9d2M=,tag:9bdDKDvU5Pb2Y02saSASow==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:exfY2cecwd90zmtPORWkZtI02MDzf9xA7d2JgPm7/M7yPlBe7zAO9Rbx2CN3,iv:JBJmohjLRNwQ7i0UYDLDBeryG+GW3k8avsyDCc01iyQ=,tag:Q4sy0gGygK5WwbNH/c2YrA==,type:str]
    #ENC[AES256_GCM,data:FVLPRu2vHs/szs1Rew==,iv:L1ipHGNgEH9jN8VCcSsNGty/N351c9W5zL7zpp0aA2c=,tag:koChk+qdLF3M3MVJk/ueCA==,type:comment]
    PODNET: ENC[AES256_GCM,data:IrkzjEgJwge39P/t1g==,iv:UaHb26HzGbuxOM2cjVOcROXquK6ynQK34kpTO9NWt/I=,tag:/DUX6VpNNkZwmsPG37KPIw==,type:str]
    SVCNET: ENC[AES256_GCM,data:9Wdq/+LvADblDxRWRw==,iv:4SfhtjyYKFpxdM7dk8mgA2+BhkpDGQXspJcYATO6xoM=,tag:ys1+5JlyCFyEd+RhhKZTKQ==,type:str]
    BLOCKYIP: ENC[AES256_GCM,data:Fq5QGhs9r4WtyfmFK4Q=,iv:O4ixLf5vAmJ4Yjt4qg5vANWPavN5o4LzsgSpk0gxEfM=,tag:8AiZVj9vy5G4CbIc5Bq2yA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:Xo2ZUeNyihAKnw9aRCc=,iv:EXBdHaqlBVqw/ndzbFLQPVt4gKnpVxE8lfNi01M8Gf4=,tag:K/WhRvg5vVQgYNGnIqgS1Q==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:zfTKkuyIx2A=,iv:Ie1gZOs6OzJzHlxvdtubu4HScfSvTx1HFJY2W6rMpR8=,tag:g97/YNsAEVqyTTQcnayO4g==,type:str]
    S3URL: ENC[AES256_GCM,data:OEu7/mN5ARNwUP+t0E1jIuO9sCQuPju5hHoYw6J/VtUVa7LmdJ+t,iv:fOlfH02amnX/82Q71ua+rfW8gmEBcRDQ8mVBtglbnT0=,tag:B0cVpMNboUzJv9vsVHB0Pw==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:tpgSN0AHAjsCOGk=,iv:pIbk4VFgZSQXi5kS5fujQEshIJdTjQACXv3CfPJGy34=,tag:Ig3wGJ1ul2iA2GlxYLEDyg==,type:str]
    S3ID: ENC[AES256_GCM,data:BM8hJT/HRIQuX0Jq0nf6EFDJTVmXVdpfjw==,iv:8kZGfWrm4Yu1D1v4XT3+V1ycEgRXUQE6P/2kRL83Ddk=,tag:PKIvvrhri46idNX/orRV3Q==,type:str]
    S3KEY: ENC[AES256_GCM,data:RIJfPLfRcQrmU9jvmmNS7j4ELL3zTcCIPQA1pbgW9w==,iv:9LA6pjIUlwKChp/iZABCvj7vZFEq9P/Vsai7zKoaMLM=,tag:oT/q8qTn7QKOXaONNKMAEA==,type:str]
    EMAIL: ENC[AES256_GCM,data:IArk6ykya0tXOSmj6T6Mi4zU1SO5CaAsBQ==,iv:zDtbzoRdJm0F6T+1hPjaCE6616Kxged/J4DdHKCdIYc=,tag:yLUM4dxPpfLcZnQ0XqkCUg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ww2ckPiXfvOJMNSGaxMQy8VH5bkNKyjnntbJhINOXW1xvSP9U75oFw==,iv:A70sPXtgPTixwQAAmgDD3Zq4FH5cBd32Fvi/t/wCNqM=,tag:NWAzlsrq9SxXNiW8t5Okzg==,type:str]
    HPIP: ENC[AES256_GCM,data:7Z43uWuFovvUt2Gvc1k=,iv:+AXtZbdcim6J5s0qBEjy4ciGn0YA2+X1L7wt2tws7P8=,tag:dzxv7sPF1ZKQMxF0e9J5kg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:z0tFMw==,iv:Pk3hKnyjib6CN7oCfgDdr0s40TCskEs7oc0S1efnF9Q=,tag:R52aVRWwNgQB3dUnwanruQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZ2syc3J2MUgvTy91V2pT
            TjQ1b2ZZeUVXWW04anU2amxtU2R6UEhQOUZjClNaWjZHR25wbkhEUnZTU2NwTUsy
            cVNzbXA3L080KytUSlB4bHo0WTUzb1EKLS0tIHdYTVo2b1hxNVJLNEFLWElWc1VC
            VEM1OGJ6bnVvazA2KzUvcUpYZEVkRHMKuBUpPW4dcMCSpnxx17ltyAK+M74+u9CK
            fZSRcVJ+NmPf5D1UF90jresvTRN8bKtTzhiHuQqFeX6x+L6NQpbcIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T19:05:24Z"
    mac: ENC[AES256_GCM,data:69M8W0A1pDglzA1Q63+nq78i7xqYu+gNfp+Kefead/6NY1XjQJZTeC13rNHemCRJexDBqQNAP1Xy3JDKcIWfCEMRTgezpszqozjNyMUHgee86q9EX7F1S47pfUzAd70rPX8Rr/0+JEpDmQXCz3P4p/ctpbkAd982PZj9yyrUuLw=,iv:30RiDMs69fW0/5TwH0O0dE2093wqDE6dSLa/RpU8Sco=,tag:ARkQvCorUhUeCRtFCfLLPw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
