apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:522YUW7wgfb4Wq5Ay6gWTyUFX4MKgyi2R6XjEJhXU2gAyo4FNpgEEI67YvJR9CKoFBC85iHdJLMF8ej17WYzBCM=,iv:cSye3KgBz8bmn1QqK9ptSKbZbPvDcDqWWXDPOEeelIs=,tag:II9UX/ui7jojNREyr5fg1Q==,type:comment]
    #ENC[AES256_GCM,data:F0gRkWCrt+bQMcS33qb6WaK9APgckVKEGkL2zP5OuX2NHy2W8y1NzQktl88=,iv:t1AhUVxecrX9QnzH2amjzeqWgKKs0GVlIHYfxvfE4XY=,tag:xmpDeoCBtSx0wIM4o+R5AA==,type:comment]
    VIP: ENC[AES256_GCM,data:CK6Zm+XtjBJMXlvAEX4=,iv:m4WSiFsduLT2KqUv2IR2ZtxFdp5Cy1eLc1hWLWi/KrY=,tag:YWj3SORTxuf4t52hK4uLTQ==,type:str]
    #ENC[AES256_GCM,data:xbK4Rz6eGR973dLx2tPx2NJcBimR2feUkNk=,iv:VH+nPCvGulgrhK/bkHFJtZUVHM3niB2syJRXSxdQMmw=,tag:em/ptvL+jBVH414yB47IEA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:08nBRRA3sSgUBFU9,iv:f0tZOF3uTERnNtLBkLsGZK1gNphFmP7J28YjdS6S2fM=,tag:GjvzE1rh6/hrX7Atcv7WDQ==,type:str]
    #ENC[AES256_GCM,data:ES8rC/Uw+JJ0SNa39kj9XuC+BKWRAhr0eSlG7M31J/BrOQ==,iv:LOq0S8PZU8V+B57CIvbdyPq/XXYkHVgvE4kdAG20PSg=,tag:mwzyYdG7+xSbD+aA95M+HA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:K2q3UQ9txrKdiRGw,iv:2PuOkvCNRX6oUCUj5lAtoT59tr+ezTmslzVDSZS/76o=,tag:K2cI9j3PKpAxYz2QjQzBTw==,type:str]
    #ENC[AES256_GCM,data:40R/qhXZhJeK3PWQtOPXv2FLJPfjdka3qmRV9c/a1LotHPz+AxCmJY7xUNpmA4M=,iv:JEKtEYZ1Dse0gy2/mhM6O/GQ84EQCn7A1+PozOQqCr8=,tag:n0XZFubnhybkCK14Pyuisg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:FliZUyDyuzF4QJGI4TK2CEWUSj/WJThCkwYAMjk=,iv:+CQy4yWSJ6lBDB75R3eaHUsxcH0Twx7gSf41dQn/vsI=,tag:Rr3uxbL1tILz+94y7MYLDA==,type:str]
    #ENC[AES256_GCM,data:XoJW5LQR/xbjDEsnrMkHRVogmnwm+3aauZD4QWF/MR7Glvg3Uwggi8af2xy4wn+QNjteR2M0EJtpaqbDlGdycgFIxf3ZPkUVT6GfiwRVsgM=,iv:YNtUangmz22wPjNWEGb49Y/jn/Cy00jJNiRhtWiBSWU=,tag:dd/ZX33oaUHPF88rMpbcJA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:0gowHTleKkaY5ON0Cqg=,iv:9+bdISwyP4K2S78pqyar3stfvJ7GWf2Cn7Vah5Z7bEc=,tag:xtzBpCeXsG3uuRoCO5pz3Q==,type:str]
    #ENC[AES256_GCM,data:lKVg85zpWhEMedLAbxumt+n2yIYaN6vHrU7RMgctQYTxOltoYeDSxGA+zVDlm/54xVB3QmCBHqU=,iv:hS/uJ/LUto14H7Fi9M1Dynf5YXXzfuKXoiW9bfatjhw=,tag:Y4Uhp0ptr4QxjDN97OBYmg==,type:comment]
    #ENC[AES256_GCM,data:DL03Qtli82IbgBPqcb2Xd8DM5A9kvebuQg==,iv:cLeHr9yu+/kYEv6l+MH1p/TE/umooja9jNX4tC+W3c0=,tag:m7uXdqyzqwbuHiTfTC4shw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:UI2vmTHNgHZydKd4DTv3EV9JjqOwNYecl8jdEDRPhPXYjPEsiNOzIS02QoEU,iv:JWfAjO+jI65Vgk595wsQo6vJZWQpDk90Ooeb92sWy2Q=,tag:aQcIjQFhjkecJ4kfx0i6fg==,type:str]
    #ENC[AES256_GCM,data:56pzphSRVIx2fMTvcw==,iv:w5hNJAqDybFm9RVnVKhZ5Pv/f81NQ/S3I7pz+cBKAbo=,tag:tSHHiEL+KYGEIxdcZaKDSA==,type:comment]
    PODNET: ENC[AES256_GCM,data:BD5xplw2R7bPDDinLQ==,iv:LvgcBv1193bzgWx/52ko1qP0QFqB4hd1PMOShLGsOfo=,tag:a9rPNvWdHWUiZrglHZvtsA==,type:str]
    SVCNET: ENC[AES256_GCM,data:VtKvwvk7pytTHdCjfQ==,iv:cJvsgxMxw7pkhiz5fbwZxA3OzvhGQapBiIeqt4a+8no=,tag:73GFlN1LksaQZL6xNxeQxQ==,type:str]
    BLOCKYIP: ENC[AES256_GCM,data:pY3qDiy3Kk6dE/DjiD0=,iv:hnCJENvBdDbuad7B9cp4q6QZzMMfQ42xOXwpj1iSDog=,tag:h/cU3UMLMpz87f4FggFoOA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:exRD3eJR6/6SoaOmJiI=,iv:mmjuE8L9YBim/nauEt04JwVnT8J4ldE/jzwArOZ9zqQ=,tag:4Bno/CzhVkHpN6v8xNU8Kg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:txcFyzsnldQ=,iv:i1hNu6FunRDHYETfp+Art4pjvjaWCqOPsU0yaCqM0yM=,tag:i9r2N7XtHJLsrxltTHMHng==,type:str]
    S3URL: ENC[AES256_GCM,data:VHp03MujYowXv+3w+4IhIva8q0Rbojj8/vSzqs1LFu7dX92kVvEu,iv:reUT0ZU1HtKBHHceSdejwW56dNXYmeI2iM+Nx1m2jAA=,tag:jqw0Q/vjYaIW36+upHHZkA==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:4NrPKhFqlfHC+KQ=,iv:6gR7GB3h1wbU3YumRw+qVNVgJQVETd5CRUHqD5Ylb5g=,tag:157BqGUNOy4vvt5v9SGogw==,type:str]
    S3ID: ENC[AES256_GCM,data:DIR+5iE1N6ASIXfuTsa5Zr3ubDj/VubPcg==,iv:l7BEoXFaQhgk9WuPgSeBMghggvGYWurZZfOJUhutD6U=,tag:Qx6XLTqb817L2w5sB1g22g==,type:str]
    S3KEY: ENC[AES256_GCM,data:s8qNFiXrc7GgNbA4XjHax4/+UTzKbvRx1L+DgCS73g==,iv:05QKBikTpzqEH8vjXbjsTdDJeXLzQ05wCdeGv1zoWWA=,tag:OmKdM5Nrykfh07FbSTFMmQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:4n40pyjiHYPHRdVsMvYmyVYqgawS1pzwwg==,iv:Qmmeq1Pq/PUXt9J25P8cX4ep2ZmivgQdhURrM6NrVjk=,tag:kGHT8HJw8jvrSzUTN3LUhw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:0kga9tXZBhLZaMj6/dDYLqX6raLNc13rODldnXAG0R9ViH95Lb5SJQ==,iv:zmnNLl1pTHc5B/WajoRm7kV+I6YdDq+SZqNnVl3p43w=,tag:UmGfv1EgSfn5A48udjhDNg==,type:str]
    HPIP: ENC[AES256_GCM,data:D8SbGXYdSeuLIdujxh8=,iv:0F1QCHLjzFoSkDzFVhUcNn82bKdTMGGESXwvbIOP86Q=,tag:LF/p65Ozc5NZI8DXFeGN0w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:ZyUzuw==,iv:zjcVnnWlXaxQ3ybOePCqqMfSJf6WYSR0eFNyb73bme8=,tag:6EAzCcCIUPOa1BCGZ9EZMw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYnJLaS9vRmQwRlliS1V4
            MGtGMXYvRllJZmtmUmpaL0ExWEUvRHpFL1dZClcwaURIRzV1MW83UzVBTVBKRUJw
            WVA3ZEsxNWI1dHIzaWt3QUd1TW1xZlUKLS0tIHpLeDNTaDQ0dWQxL2dvRWNYUDBB
            VzhyZG42cEJObHVWNGdVbUNHejljdncKJBKIFdLBRNZ44Dj7b3VSSc2fAiHaRbNr
            BTr0WuGRxxu8uhM9DzQT6h0xXDeNP7LXIOlXcB0cen6al6aY7eP8kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T06:06:41Z"
    mac: ENC[AES256_GCM,data:v32AIa6NcikIcWTkMeBZaQ7qubbweBrB3zaf1XM2tHO3HYJoYQq4DohyJT1x3k85j7cKaxDqmTGT2rIcO650eu5waDeIB19Lzk70Qtzaa6vPSRtfC0+url6lRTwa1DJlJaDeKNJYGbBp2HVgQHuzuafT6aaxsfzffWWCUAMiHRA=,iv:dYyHthl9+IG+Q5bQglc+obNSvFoqY5yNwdxgarMoNc4=,tag:Atn9jEvgCWv8yAS74KLsbA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
