apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:9dRVfjAeMf9RrqTZJIIbKyZjvdRtzKxCckpaNXNNYKJMkMgC6feGUX5AB6eHYi3lYEAuqH9/vjm8kKwhfBN0FVw=,iv:JZAFycM7E1hGRjAX6FFXAigpRHMmctsM+g0KHfgMVyY=,tag:VMWl+L8WbTVrlMsBRWk85A==,type:comment]
    #ENC[AES256_GCM,data:pNvf+lsn5H2GnQzkTbL+7aeZIyq1KWdaH5/eY18bu39pl8At6dxde9lsJ6A=,iv:zdEouvLCuTwf9MQMh8gZwKKxuVbk9TaSLGEt4tHOjds=,tag:GXMYze0VdTvwjWfDt0d8XA==,type:comment]
    VIP: ENC[AES256_GCM,data:IJuvTIZht9Rexj6dhEM=,iv:xxY6YfTHgCDjD7AWsgPrFVf+zSGxytbb820M0z/F4HY=,tag:nL8ue6mHUYKdLOveSUUMjg==,type:str]
    #ENC[AES256_GCM,data:YhsZ/C1QEkt0L3OrCUekOuEB75CIBfJ+Imk=,iv:2+gXB3aXazxibSGdHOsTMyWJ0u4JgjUT1dR57QO4xgI=,tag:fnM+Uo7W2xKqLQSTPgTvjA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:2nOqypBnk4Hb+CQ3,iv:SRRa+Wpmj32qXYbVDITQtnuN53CTzSOyO6hFARhGPyQ=,tag:yoG3mszZOJr89Kx8FFJzJg==,type:str]
    #ENC[AES256_GCM,data:DxIgQFz5iZz54sRg9iyJLndPJFG8lLyRAfaeEUgAvs/VLg==,iv:ACUrN4ri812WN6QkIKW28tqCKSWNx8B+wa7D+vceSZ0=,tag:pnsyajhZPqCAR1qB0f4pPA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:cZicgaEejGoL9lod,iv:GWpdHhPrVx3WnrxuAzNrIOm3/5gALIsExUnfHtvrgiU=,tag:+nQO4zUL66D6WbYJFory2A==,type:str]
    #ENC[AES256_GCM,data:2bUX7TqXoesokuf48lg2HQqc+n3pvA5HdhIoRnEnrEhLvIYWotd7OoiZ/fQ9sXk=,iv:i/dr7Oxkc8GiwyIZELsX+fr2L55XZ7juvhEko5EDZME=,tag:qnk0GoVjoeKdgR6ptaajdA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:eovWATvd3ERU2M3wRDvJfSAjIChbgqPikgDW34w=,iv:+YVdnqH2Cgrj51EExop30l+nLWrYOBVcmYHX1BVrSaU=,tag:Aue96dkGkAPug+OMoTr1mw==,type:str]
    #ENC[AES256_GCM,data:ebtA4E2y3c7wZA2vm3sEbbvL8BCvaQADl7hH8vXudHEUPLnBySvpBI7aRfiuXT9YEXvSX46mMxPSugqLoNv7IzKEa+6/F6T+jcu6/xRxeZk=,iv:qrLTK4ePJaR1s6rQ+TtqhdfuvvBwlFCo139zh37NFQU=,tag:nAhV6IfMlPjbP1lP1h5zEw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:rDU001y1JNHhwDutvPc=,iv:fNBpIZdubJjPNp4CJF3f04pqLzQgmCU7vVxq0IL9luI=,tag:shu+2RWyC2qblT6gaChB2g==,type:str]
    #ENC[AES256_GCM,data:/h1KYxf45ye/ZZrajfuklVOCHIE0fnXcUaCPUsS2NOB1ygelqhgufGMmQ7fhm/sxSjQGsgItpVQ=,iv:QGYpyXxTJlekKiSq6txrg4AVKwqq798xnu5wmKQo8lw=,tag:ttlN0A5CNVhO0DGGKjvYfA==,type:comment]
    #ENC[AES256_GCM,data:fCft+c4/yv4z41vdl+1V2/bw1Ml0iIp2VA==,iv:ufoYjzVBsaEVPYZ4SDCQOVah1KgUMcYjb8gfK9Gcxcc=,tag:i+zUdI3XKHhNvWHfn/lQtA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:XTS7lp4+LKOZJB4HF4twKXWJndMYpF9zI5Coe1ONG4lvrvFhxL4ai6Fxn27U,iv:/25jkoRYrqwGDom07i93zEL7NWE0z9w4BiY3R4VzY4M=,tag:CjRfJ4WsGnlX1ZUdGdL1rA==,type:str]
    #ENC[AES256_GCM,data:lZ/iMUfaIADWxOTj5A==,iv:OMGfReK+aXxBR5KdLxCv7ad9rfzpDg2tux8ChZYkmJY=,tag:9P3Mxn9PqiS73sC3OI7kdw==,type:comment]
    PODNET: ENC[AES256_GCM,data:pdzT/fto8QFPjknTMQ==,iv:b+b7mePzu+8Lwi2F0xNn3EepAwbR8hTHFiuagwBaNuY=,tag:Gl9XmKIGKrx+SFOzErbWRw==,type:str]
    SVCNET: ENC[AES256_GCM,data:6PWIeeKsJmTiPnEaeA==,iv:v0qg3Wc/hzw2KljCONoYZmUs8Xac2eFg35aUI2JYZ+M=,tag:DwHdbabGjMse7aoJ0aPQKQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:TAv/8gQmCbXSyM8EB+k=,iv:KIsHj1/VwM2LP9qvTEqY95FyjNfpAoIqYVgak/bZdxQ=,tag:T2GhN1QkxBDVFBuMJaRW4A==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:JwDdxYwJ72bdADC1XkA=,iv:DzpIAKctLEdsdEM5cMOOyZl5LxRYAx29gGZxgcPuUzU=,tag:kSip4PP8zrfvmRRgcgxbqA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:73tqiYn4K50=,iv:pIm2dqsf5h/RmrS4uAluovyL3wuiLd+uttGpQhFZSDw=,tag:pSleY3sFO+NY86v+4D9W/g==,type:str]
    S3URL: ENC[AES256_GCM,data:icFCVrjNyp+zmX9Z89n8FtrgxfJcgIONzHQhYjyLmk1J7PqzWys=,iv:qrMvV0vZYzmt8NyQhSKhJ0GAyEWLHMsBc+KCC8XzKn8=,tag:BkJJs2psClWqZcT11BAbfw==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:qxVkjvtdVs2JWVQ=,iv:s9ep4zlwWPmC9mRzqBSxC9X/WiKythHxKAfS4IC3NXA=,tag:nsGvNXU6hAyZqsB64pBQbA==,type:str]
    S3ID: ENC[AES256_GCM,data:isxqe1NxXVhdSJOsmGjm2XkPKhpzcIPsZw==,iv:jMeYZ2VAGhu1/XmkvMWhFW3FwZNAzL/rF57PxsFmHqc=,tag:8a/uXKzh1TgOfuQBfXQ2aA==,type:str]
    S3KEY: ENC[AES256_GCM,data:c8FKvFm7mxFDNBmQfaRklLjeGpT2xc9QhJ0w+kOCig==,iv:YQ5avLhggzYNlEP7GUPxDExouxSUL1+7QDgAc6xCmrA=,tag:MaeIXrTIax5ppmvC2LGsnw==,type:str]
    EMAIL: ENC[AES256_GCM,data:ihqAKtjaDCiYtZm6UnFiDG2QqEenmaO8/Q==,iv:jwphEeEr65HtX3mMgZJQBN+ZEQbtIK0hAgXaIHdtbOo=,tag:cPn0Zfb8spZnVNWL8WBWCQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:aywwRGKkOqsr7I/FLcsJldW6yGZtq1ur68PH5gNXrdHDnB6Z/BiqTg==,iv:7BLI8xR+DGDEGH7JhPZjSXcpNzBhvaq75Qn3OD/0oXE=,tag:kalhYwYdeySz2CqCcG3fiQ==,type:str]
    HPIP: ENC[AES256_GCM,data:U3R9k6NQmeyudeQVs8w=,iv:aAcgi8akBIo9atuaHDdWX4/8VxhguUOIdSmI6avta2s=,tag:RzsZl787TObs5WW2PSs5ww==,type:str]
    LLBASEDN: ENC[AES256_GCM,data:iyE/9WX1+rStmQ+jDf4=,iv:8NKn2sKTEsk6ryUhYW/8o71gU9k199Y5Pw1T6nypRek=,tag:64RrR/78W982UTdfYquUrw==,type:str]
    LLUSERDN: ENC[AES256_GCM,data:OcW3vfg=,iv:ZPTgvvCFqUxHxejAqy2nuunaVFNYaq07Cz0yhFFklsQ=,tag:ANte/Tj3J0rmaPgsqNlNRg==,type:str]
    LLUSEREMAIL: ENC[AES256_GCM,data:88WWLlSxkJvVWWLzW6P/UwOC,iv:q+XUclhMNNGTQ6ySl2AJ6yY2gdeP4oKKRrfDZcmMMCQ=,tag:dCvFecZHitblERxovcAQ0g==,type:str]
    LLUSERPASS: ENC[AES256_GCM,data:hqGrdU0Sn5dWLEUAGrQ7VWDeCw==,iv:fIier8kTTd3gabKchF2vGAQOIy7IQiGSQGqymB97CnI=,tag:Hhp0yejOa9h1Kt39UNiIBg==,type:str]
    LLURL: ENC[AES256_GCM,data:NJutFmVHeDyqpmuHHD77WHnsuyshFQ==,iv:voj16k/78yBgIutkHd163gsDNpQ32u1yWRZWeqb7DJo=,tag:OQLS1m0URNEYMrmR6F46UA==,type:str]
    discordwebhook: ENC[AES256_GCM,data:UucqoiJdo33UCOsfFR1kVB3J+BOF4Rw4zleOy3i6fCUojp7N6etPdhRl0q3XE9iBvp3V6e1+OOsHrhiAQUQLPAdOHOhEzVTApAL8g9ghya4ytGsB6ciYueQtHeU7EtywxUrBt0XM17hEsL3hyhmn5sSlN88YB6YZtg==,iv:yqOnngAxTGKEODQjB44FGFAZsiaMavNyp+defI4rGZI=,tag:5zuYkh3wLtpxImgrcbCLkA==,type:str]
    AKinitemail: ENC[AES256_GCM,data:0ePg1LE2kWe6Lxd+u2yPDa1OGYjj,iv:/cS0lq2D3nobjfoFzow/Hd7r07YUw37uANJ/M7QDV2o=,tag:kSkbDnKTqPSpB4s4iX/Fsw==,type:str]
    AKinitpassword: ENC[AES256_GCM,data:3VIhXV9jVt3VCjCuev8N4Jqubw==,iv:SqU4R7qxaAmem3Occ+Ti1ZTjc+3a8IS+sV+Z8k+c+oY=,tag:xifP9Xi2oI5E0cTuh1Hn+g==,type:str]
    AKemailhost: ENC[AES256_GCM,data:FEEX0Z/8zYgrAffpZsXhYsI=,iv:JJdtNHzwZTDItHcncQxQxlseS1ds/oxXlYAHC+rZONw=,tag:CIu/kr0RP5bOiSAfPQbyRw==,type:str]
    AKemailuser: ENC[AES256_GCM,data:257w57X/,iv:AbMYuE+5g5pqFBwRKSdo/U5osgbeA21a5tn9reMYreA=,tag:2/MMskUZtTWDt0mhFYAA5w==,type:str]
    AKemailpass: ENC[AES256_GCM,data:5MY4FnnaBcbGyWxuC3u4EyaiAB9iz83QZVMDzNluDuf7zTX+SYone8v/HpSbg8CD4uwsonY8UbpGVBi9lFVSBBWZ6UQo,iv:PDNStSORFYBLb6q8hFuXe5w6Iz6kFhvnF5zdesBxBEE=,tag:A5mW0Y/h2yWhwNtuSj7avQ==,type:str]
    AKemailfrom: ENC[AES256_GCM,data:qSFaWMb9zljJRwYwdqd/1ooHBPUAIQ==,iv:MR4jvLum++s6aInbQ9u3URkRkwmo9AYeBYt1qCl8zOY=,tag:tpEUSB5K7GtZMYKA6v1W6w==,type:str]
    AKproxauth: ENC[AES256_GCM,data:zdwUNPKhOtYfNN2UF2fIWHrpVB0=,iv:HJ8RpTTocDo4UvaoN+BCPOFSAIp8d7Wm9XD6miSEx5E=,tag:dQMw0IQvEpTIssilWjUIXg==,type:str]
    AKradauth: ENC[AES256_GCM,data:yoCavDfBQGjkjHDQmV+IgrvlaPI=,iv:cfAVTZIExR562KAQY63nVDUzM+PX84oVnYlSgudAIxw=,tag:sirSZBJbdd0JZpshQojCVQ==,type:str]
    AKldapauth: ENC[AES256_GCM,data:RFB4OIqj8eZJJjCFjyGVPPXdLHk=,iv:Silza4xWnniYwaiGh0bdzwjMV1oZnHQpGjDni0Q9VI8=,tag:e1JOUyrBCuMd99oQleVqzw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:8Uutgw==,iv:tD8e8iZi51rFUxrWza/wVRCy1NaJnPW+ioTVS9I89B4=,tag:SSAoJGzgcrJdWiFau3pe0g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQTVoWHM0MUVMbHFrREZv
            QVRGeFFIOGtwZmhQcjRxTmNJd0dKR2xsRlg0CkhhMkxjd25tRE1rWmNlUTcxODlR
            WGIyT0pNLzJvMkhIYUhMY2t0aXdrdlkKLS0tIE8yZHRBdFNjRURvNnVnZXBvbk5k
            YUZjOWZmTm9lNzNoVmRzckJXMjlKMmMK3sF/jCsCMNK5HrjIrPL2I1Mw8m2mVKde
            Um4P3/OtVLXRzU8MmiX4rBcnkimKhMpgMOsT+xVT++78719J/OcxIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T12:09:50Z"
    mac: ENC[AES256_GCM,data:PN5pxQugQFo6as6KbThw3PSVXcuple2M4flYP0RLW/juazbjS6LCp+2BziJZ/Hzo2YBSfJjFTlS38U6w8SC7hR1V2zQ3v+Z0cjTU16SiKCG5ENZMDpHDXzxqLeyfXXdZXJhpBaiey1U6J5oMnr9GpxzuRz33k0jJLcHdnt1rcPw=,iv:5ctR+WhgtZc9tUq6ubFJ8R5eB6zt8EkWdMk333rgNCs=,tag:B0IgiwjewK/popHe27iZug==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
