apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hFQPdNg9v4YRKS1jiIStLCUsJGApiOxKPIP2uvcCgpzamQzZIMGUlFRj741rfx+soK8RN2iQ2hGt1HaNPSJXpgfB3UeGCTlsvNk3BIwNhPdfjdN/bMAFl5Hi6ayxOo+mi+SF2oNNTNhkDuOPLVj74xygl4B+kfKqlJ8oZ17CK1tfHIrMYvuS/GZZT7LfS1BHKfzCu7tVHbTIqHjSpjX8uByipmmXnNDYeQ9aYuvy9D0HS1Fx9EH0Jq+AYuIYwsJlbNO6erugccdJe+BB0Chuff3g7RoSsOBvIall+ZQN5tMBzE17UhsxC8sYKKrXl4xkTL+sN3mv+hgOXmmxA7kuoFmcy+dqJB2HNh7U/2rCGiwdtWgcxsuKAxS/w5tsLYf7,iv:9nVobMBb7ycPHbdHKlqsJ99aWkHkv3ce34MyGBF2OJw=,tag:JAik8okSBUw5uRpzZsdVfQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:UC1w9Dq97YPBfRmgDkVxb1ErKCnL+Kqg6HAI91NnpCcoUOtG2TFun0TrfbqLiH5Fqzt66F8f1q+Uk5ulMMV+xkE6jBPK+3C0ww2PHgs7vJ7qFVxfIUA50M4gKjDh1NZUcTTz9yol0+jyH5AFiCmsNek2vUmGg/eVDXYgQZ6YrgJ1o+usuPBBoQvWqFmKYKThrLirJBHD8DG45EXNrePaUp27oBmS2dojkVZ3Yzi2ZHr3JK2DcU52yG0ajfOGdgoQY74gzSSI4vWmgy1WLw==,iv:e1bGTRUl4oWTaZWIapbB9YWWzVBoui/ypu+9dTbIYwE=,tag:cZ5mBpw+cVTlf+vPT+niQQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:HYFdcdlnemqLO2jQfItXdMTIcTU4PWjo6gQvShTjc2NnmOL5iPv/Pq0eOWqjpXoFrkxmYho2B1pCObvvtMeP87HBbticOabfEX85Dzj4j8rJ7R/yqEJ7WJIt4iE3W3GAiSdBKVJQX2lHDKQGhMztGexLPyQ2sX6WSxrJhOYhO6vNLDKcAcB8z1Z3ATqsn6qByb6nBL1V0yQKhPLZdWKT4+vv7ev0PB8LHyk6,iv:tGZ5b8blbDu3PmzmwjQZUfHxbQd9EmPGjHOQDcCy2gc=,tag:llYF1bHD8NNDHinLidPPDw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcDlhM2NGY3QrczJMYW0x
            dDU3aGlaVU54ajVQOC91b3h2d3lBQzdYMzE0CjlYZU93NmhGZ216V2pQelI3VE1h
            SmJqa045RGp6TFpRZkRibU9ody8xaUEKLS0tIHo3YUhCK1E2UWRuaERzSGNIN01v
            QURsdlYvOHdaVUprNGNMSlR1UWZZMGMKySS/FbFVqkK2y2T6MjSWxgMYPuxx/G0W
            6BpbuN8pUGfbD9cCjq8H015IVA53DlHioeL3F+JgChnLJ2/K6oK0Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T23:26:22Z"
    mac: ENC[AES256_GCM,data:0BJFeDVSwby3rvbvAJjoAN5hblMfrrwKkVTsiDCHagqZKpN8paRI58a7ia46F9xx/SAJFITeuvp183x8faFSumkRNwQ8lx6npK8WA/6PCaEbcMs5KRZ/Xgutn6uUij+2EdrulhOlXLx3JVRhyIyA8n086IDdWgm8F4I9OQneWhY=,iv:wEliwel7l8QhPcW29F1rQLmDHQARbI+SpBhaKEFzmCM=,tag:iMbmc4slo8bnQmWdhlo/KA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
