apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Lm8DNoluwk8racl6Y8j5A8RP7GIaT16b1OEydDdu4hZmRtZd6TuddHGFjnQpZ21SnTBOHCbNWPLbXCMh6wEaPIaixkHbSp1NY9fjU+MNdpCwsxnGDYjmPMX6SzEHXfuPW7Di3+IHDc8UA4EFfYtzloHWqeuosOH5V/ZFtjSoXx0a/Fagz216B3IgRyaqcMonCNT/8fasnZ4oo91NKcw747JlvCLRtmBpzy1HK9u/Slsy9sE0Gx41DQX38J1hMinhrmglfzkFavxD2uhGZU5Va55Srda7UmHkvF8dDiLliNHEEbFgdmFbp+fjbf0Rh5d+s7oxNlSmZBvPSakhivF28AFF13y/Xu7EWzG6NzfKKPzgpQshK9Ma2aLE142wuVxR,iv:K7yuW9ZlVWF8PdehAJPyHeS3FqeXElxeIu87RJSxkYA=,tag:Nttxm8wj8p8uCBnWRCCUvQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:QJKot1/eLIAkQtKuAnLtC6/QiyhFjZ2dFWAC+yJD1978MPSvPjauK3lgC7P9V5pnvaNA9RekZdzjqDWlrA+GuADqd8rNnVK2fY4D4lwK50HAhfhcMDgAis0/GFGNt6fc7kRQA464tdW0R4ukbR5IevB3igADILmZgmcyWKspTqIaM52913X7jcHS0+Y4b1w1VNVH8R/DYN878F1yL6CCTOGCMFB6xqqEWAZ597fhyDfvabZuotNSCwY/F6OmqtyiP+MSqIkW7ReSSf9xUg==,iv:EEY7ZLxh1woAnjVC2ngabXj7sHiMAMTSfXP/rY5taac=,tag:2kr5wHT5Q1YxF0qy01iwmg==,type:str]
    known_hosts: ENC[AES256_GCM,data:4jXzJs4qitS8zWuXen+my0J4uA8DJH36nERu88gExV4bcDRw8oBIPawL90qgWPbrKYTTKzT2/XFLst0WcXQacqO/ODp3SY5L6DKf/5PtyJS9SXjWWp5VBC3NKHBoRb87rtvd81IMfjBRiXF5SLfL6AT3Sm+LePLzla445j5U/rzh95MuoffG7PvVHIdIpylyeQgmFEkrbzP6xx1J3QCaYzYeDgAhHPvuCDqc,iv:3EoqOY+FD4KU7SsjbkiO5GB9Ydazud4BMVujKQuO2cg=,tag:btA/2lyXzeauDrty9TTyjg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOHhLbHZWVHFNdEJSNk9B
            N3ZwczYwSFNqMnl4NEhXeUU3QXA5UkY4R2xJCmtKZUp1SHdRMm04KzRhbmxLeFdH
            SkhneGxMU1VnU001Ulh3ajgyZU9jbmMKLS0tIGVDYXFWUXBtQ0VQLzg4TkdiMy9D
            ajk2M0FtWkZHTnZ3SEFwUjlBd1hHNG8KvYlN329+u3yl67bOcZkPK/80X7ZFO6JC
            8jwPLuzQgQ2wO7HY1R/qUGQjd68xBUD4/eTQdXtR/keNwqOUdfsBNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T17:51:25Z"
    mac: ENC[AES256_GCM,data:DZTozwV9CsxyNmpvTVRGrAEFc14m05/MBmvbZlrWv/X97tG2Ep68YfIGK6OdXht/zjim+ah6Imtlv9ITGhIMGSMHcawCLq7juqP7cSPGAwZbQnLjHW7VmSQ8SrPC8Cj6dj2JwGslUAS6YNNtnc3IY8kv9+R9QDd2pJoXlVbTXlM=,iv:MBwoGjTqf/hdYdCogBuWj5QnqDoysOzgOtOgr2nTaCs=,tag:xA7pKQest9JbQ/kIW/CFmA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
