apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3f6/8LVUHlWojQNao8hDwrl/+ZCDQ6pLMlNno0tUkhXfdGVne5aKiVeeguadi08HmofBt+rYny/BME/TIb33Oyz+M0G274GV+RNPt461jIK02x6T17sHMwjwaQYSySv96hhtJHTAB76o5hBf4lx9r/3DsXChiD+hg3QOkB2ow0R3Ol0qXRxqkV4hggq6yi/YXkBxwgbOgx3sE96yfwkiUoEA7lPXNZ6besXew8gR8kobU349TDJNRwQimSSjzhO4/x85jibE/X90282j7aUaHs+Qmq+rnGfgCiqnDDkP7nB3QE+ZTZCAzo8+S8mEWCEUhw8h4hn15uaMxuiR5RCjoF0rY1/8Zvjy+5mk8YD1XkxCaZr1aMm1x9T/hr3DtmhQ,iv:LggBgptoT4udcbaKeCVWmIPyCx7WTV1AxSgUwBbT2Vg=,tag:OKfxEOzDrYfCKTJArz8a9g==,type:str]
    identity.pub: ENC[AES256_GCM,data:lnMiQxNSibzVDpyFn/q2HX+zGa65DbtzKVZ+5VSyFYbEa5Coz2DIDY4xgw5g9wgFdnVYDLbP301ywGqHMm412ChjkUtUq1aOrmqhvOAm+sxkpY4V2I0rSDFz4G6PBNqWAbdEpiiMu//Og1Gdaed59rUUstdv5K19CXHvPw6SQnaMcR6eJ5VUZAO9iRWubsqbnmySGMcNEH1m9YB9CIt6ggMuEXCd8kqzS1ATxZ34xE7jLLC3XTkdx4e7OZTVgE/HSAwJJ5urP/5AnoKr0Q==,iv:RmdR1UF5eJX+lBroheamApUc4SpkT99kbL1X4AQYmKc=,tag:lidFUBlQ5QF2sgdlgOGr6Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:rhPVestL5XldKpkZkQxa9Rh2csPNTI0McG2r0Q8Z1dGpBbeTpo2aNuT7EGXRFN1qhsa5yR97V5YwmyhSHxSFBH44XQWTStUp3v2DwvwPuk3HHfbDU8+tmZEUz322smymRp1Jx9eh60wyZw2uFsyKeip/L7c/Ts9H9ZgjDtbULu2MSCIFXhPZiDZJgbdTRex9MZy8wma2TRJsYDijw/TorjMAO0caPTp578Yr,iv:rvsD7j7M6QYqAxQCJRGG0GIKm8XoyQn4FqCUpMm3b7Y=,tag:EYc+Qva5bnlm9nSpdJz0aA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVHQwSTJvQmVZTUs2Qlo5
            eEZQbmlNRjFlZC9rRWNzNU5sZTdWZ0diRkdnCnU3OVhHQ3FqRlJadms0RGdEZURv
            allwMjhBek52bEZiWGttQmRjbDl3Q28KLS0tIG1MRnpMWGRiYy9PZEpEc05BRkV1
            dUIvQlJIOUFTZGczWUZJS1g5ZTM3ZjAKJ4jowN2RDhaKF2GkyKoHDWSxlglfUHTw
            5FVAcPi2+Jz4M/NtH7d+UGGz69llyVuiOA6rw+8VqWVzGJQDkMYOHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T16:42:42Z"
    mac: ENC[AES256_GCM,data:u8s7cxXp95iC7nr5liD56JYb1sKXclUPNgWfowuSgiwt1W3lUWsZvVSZhbiKvqK9Q0uwtor89fqjlmMt39IF1WWK7jEdlkfRLE6Gap5T5mHIEC86I8jsEvB4eOZ1SqdK70YII6SRkPtHotvR/hyyyyPgtDixODk1jBAkbCQUxV0=,iv:C2LejCIA9QZkGjyJxjh91e99zzxGoua7owF10nej254=,tag:SdJG34ThhrAKB+2nDPHOfA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
