apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2/16fnFSDeC6TjtoDFnr25/k2ErCMXhlTeGTjzc0ckI9L9Af5He2Z+jFED+1rVvtIU7qMNU3PI/XUcKbz7fHbBqKPsI4w3y25KTYlP0pFJ/DGf28n6e+7bxyedfuGIne9Uyn50fweaR5GnEPw2b03kLxwF2+8eNoVJgCEVcFIUtgSZTU0kGZJyFoC4IS6o9C9E3Uqv+bhApzlgkhwje1WXjHpGJ2khbGDgVQXbUq+/n+Jgjj8TyDVuZaZaqmgRr7gQebMOyTgerjfLl+/l7g9DE4zYHepqrfYSci2XINjqcieq19ehs6tlzjitsrzKt91vk51duYht99zPTcTLEJNLFGPlaN48MwQ6cwWcwmO5tpUD1SuRw8yAq01zYOE9gT,iv:g9Wss8hY3MxZJPxdnW6sliXSOFyH952Z4KwWGe8RExo=,tag:ONmUJ+3uoforRNTmypf8Bw==,type:str]
    identity.pub: ENC[AES256_GCM,data:HJYCAh9gqLsMoptWhi301ANBiRcq3iztdObfIAhIe9btUpSoOw+th+EFMvdPW6hRyKuCnA5l47V65nC41EuEu69W7Y32duJNz7eEwNPxMbV4akfgndUkzOBTmSOBdTMGRkJ+5OtEmpq5RXShPjjGcLHSZslWosRToEH6IX+8x3gqjBl48I6W/c0DpvaVOgM2N6YAL9THjLmCqkgoYm/2lyMSR5Mz42y2CsI1aYfWabPRWaGNCxEr9Lw7y4KvNeNrH+DY/lfGuZGCVc7GxA==,iv:P17l9CCU85eJbc3X8D3GaMHSstU0iYuvYBpEWNmEu78=,tag:c9/KuoA5GqPRLZc67GIoJw==,type:str]
    known_hosts: ENC[AES256_GCM,data:moOzn4xnpoLuPcUalDcy3QfRuxlTIzY0E9PilKnP8HktvrPioNCF76aQQ6E7/HvjKxu49AttUus6ZpKefQKhBN1KNE0Xs1ZZDbsUzISZRc/JBMOPgUbd0vbDR/gUuIBBaAXNILdLUzilfAHH9UNJvuaqnbSQVbwPd5lzoLegM+8gITa8q05poLDcwlgmakpRT3WEDw0HC4YpkaTjpJFJRPzdLFVOTkrk677A,iv:VEZ0CtrJy45Dnj+38LJ+MpbRUpkY3sqHWLgVWfm6OII=,tag:1HwSD7nR8MDEfhAWIegJcA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ0dCVEpBOG5IU1VZTllp
            eTFJbzE3dC9rUy92L1FGOWdUcnpOYzB4MVZrClorNkdqaGUzdXEzcDhrNVRzeFpC
            aU5BQjcvd1psNWhENWl6WndLYTdNTHMKLS0tIGZyNmJUdnplcGIwM1VpOXd5cTgw
            ZWF0K3YvV3FtdXRud2RieHBxUkNQTmMKtDHyasbJzwN8vGlSTSeFNH9Ou/C6PJ4y
            xYo7FFPMz+mYRLgTod/mffrr2MuSHnB1A30/qDt6+/zDjKV20lFOsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T14:44:37Z"
    mac: ENC[AES256_GCM,data:ZXucH/kH03d+DkdCWZSHg86NrdJzj087BeaW3VKbkaZxUZ2dWMeh/ZPiWfsZ5gJ3m/GGkcLo8DYbnq392iTh9pFTGtSg+a6x1wVy2TwWweiBBm3bSJDgNZmJXd/2mAcIkDRB7v9UqrG/xDDuav/7srMCanGWjm3lsYR3hJaDEuI=,iv:sUDBVe9TlFdMmSLBLdAcDDu5yY238xeq/tnchOHAuk0=,tag:U+3iX3U1A6Jgl0JqrSOlMA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
