apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:srGHD13sbLlqczQc+9Q+TO//dmo4wg8iXJuy+ul9ciyT87fX7V1DJGBUhi+4CAE+hCnJHOy1koXg7VkqK7JSEHo1lXHkVkMzK/DXBOoSD5/Z9I8D+RC+3m4hOVvzuEPs/OG/UxcNAa9j9TIXtETjgQ9X9mswJ8ddLrzHhqu9NE5mUmKyKlL+Q4KPO0bQbgxzGCM+nzx6ibFmUXSyv8w2SFOJS3ZolxyqtYuugj+XCItdYvKc+5ZV5ORZbPcYD6dA8afVWkjqbRzRj1hkjICQIHnWENkWnfmFajhHOhd/EuYarDHQR/LL8Xocz4oa3egtiHmpOYA36pD0ylqmYeKhTj0s+nfQBLEocE7zxGrhZddKdsLiySSwe70yANeWeXWn,iv:wwgd9WkhoaGBK8093m+qclmQ1D5F/c353XD5hmYC+7I=,tag:RTUyEqkU3hMc7hIFlzTUjA==,type:str]
    identity.pub: ENC[AES256_GCM,data:1VgoDB/eBC1cXr9ooZ4iJQI0RWY8Y6Qx09lJpvAsyB9f1YOPq2R45KLyz/DoIEv/vwzsc9I5tJTtKiVHBlTfT/90QZPXPf34UoWu58q5MNEi8cs3MFkhm+5+hsWo2vXpcuqu1QtWib06E4HkRwOf0/ufM5uCnyYXkaxcSqKlBSEMGWm3CaDjAr6tW6YfF3XGJI2DxSQVh9YFNGD3dHDe20vCLoJ4gciDkB4553kHJRpDfUi1/9AqQodGnyRQ5syIQmGrq7BTREGWh4nGkw==,iv:oHTHFv8xPVUl+ornTV4xdfk3pIyGMGeCh0w2/4awCUI=,tag:CgoxcmT5dMyoN1zs88P2oQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:M/3olbGiF8TCO+IE3L4lmufVlVs6izHR5rLh8GsgrtrK3gJ/1ob3l4kBfk1wmDWyrvO0aEG0i4O60m93/Jd1V+J967WAIvDY/qtwe0+5GJ7f99WAk2Hiv4wBMrVBJueCOHbaxJIiS+jV/SkzhTwgtXX7tg4HNBXsnSOnYNoQE9OYopdRUKZmbLPHs1t+1v51Ki1CUy2axSeDt7OhnojrIsKiclT83R59f8cn,iv:1CVK/BpPC1zfmTEOCIMzg04DRr0gbQ5xw//R9rmOufQ=,tag:E0oVdewMG4lWbl0rVd3P0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRUxIcVJsMVRBbDNjSnF4
            NEVOeXVFanJhRHM3SC9MNjVUcnRFNkxQTno4CkUwQXVHUzdqTURSWXQ4YVdvSDBZ
            anBkV2Yxc09lSk9GN3VIdGF2VDdSS1UKLS0tIHVndU5MMklxV1lNYVNZem50Y1oy
            Q2dNNWx0dnRhVWxpM3ZFZ1UwWnE1SEEKFth7i6quZfQ3qmQsJj2ZIP0LAW1b49kF
            TfuUhHGaR8NXEQ5kwnicWw3KOmZOkaXjK3AI5Jgs+w4ZUIBlInN9Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T21:58:27Z"
    mac: ENC[AES256_GCM,data:iSmYJaF1o4id14ateWdChJX/2HrJJks3L+55hk+KFbnDtgqhBPgCglEQb4kNCv7VQ5BTwgE8w8Ba39Dt+Lg43uz9VyXZPPOo1plzT6zRUNc865WLwvEAvVCI5eV77k2Gycqcy6BBMkyj+oGl/3r72b+5NJbq8G3SN50UDndQ7IQ=,iv:nnWMJ1gYiBabYISzdEQyFSPOsH4/zLWbDBEmqOZM26A=,tag:rRCkjCR4IEn2SRrlhOd8ZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
