apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hg+1upzlUzi1BqaVRFCjQzYtGt5kJnx0Dnfxd3D8bGdbwW4GgISOYCAnqKk01pUkrlCybiFvtEREEGDZonVEP78v3e0XU1PxoUVqWhvs5i9GtsikeNs5w/EbPyk1f3u8j1HXi6JxNiPsHAVI/Sz/rPeyMLKbpZiOyZ1a4JZUSWyXmNLXNPS+CzYUSyKEaw/6Qd+EmuY8izXzYLrlIW4EhREzxJ5BFoUwQD1mSUPQJp8/LaiLARNezZraqHZt2iGQdO4bIzA6cumvFz6245XZayWiwJAUnL0BPmLJ1MH/NRjLqSbODQs0NsTmEISgU0yIvLAromxN+uaDc+5n9WcMK6ob3yOaxPpbYJvj6rfkzyg3AQOJmHVUlfEd1PxDSuEL,iv:xmjkn7ZTV3iWEx5wcf4JcL7MiP4z6NzkOGVv+PmwXME=,tag:R59GQzLJNTG2VQ3bpBP1zA==,type:str]
    identity.pub: ENC[AES256_GCM,data:dIFfXsZ4u6ok9q44T8q1GFHvIMs0r3RchdQshJLg/1TgK2OsaTPn2EOtRCdW9Q0Jus9P17ivZC0SCxF+AIiUF26/Lj/DNjwbfh/O5gIH0YVuMe/Ye2AbdWVnfRsOnIwO/gAqdLzJKVohJtdaNsMB0t13RvRVNtBR48EvPAEIPcwPUago/Vn0aXfzkzO6jOePQ5B/y8BGt/BXk/hC0PAktntimzZFnjy/+bW5xVs08pkdUMmULthHkD3uU8kJJlBKFozn9UO+sRt191ZzTg==,iv:b1srbbQNzp5BFm1FQfQNpoWH8pFkgmw+GSI1hkOWdC0=,tag:oGMeHupmZ+9VZdmUPno2KQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:qNL+axdmrNrBWYAFH0ByGiuZ0f01xLzmhQOs0iHwS5ekI7/JjPNlx/Hur5htND6cj98xMCfj97geiOehpdDVzxumID7aq+0uW0JqZ7ucbu8e7yBGzT/4Uqfd8FFaUImPMAeRPq0Ybj/vijIG5EMFESa0CGV69DxLDaX9ax+bc9cmRXYBRYbRZvEJNoyjiCspSIKkbuZHVwtoYb43BDB6grd5aWKDONUoXh28,iv:LSnQPEAnk7iIXYcTRN8RkR3nhM+YmpqU0nIs+vSH8wY=,tag:TggAYnZjDsm4gReUKMD+uw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQemx2ZytGT2gyc2FBRDU1
            aHNpdjUyYzRhRmRNUFlERUFYTk1SQkUxZkhVCi9rZ3lEaTNZT1V1R2F2cnpqdnhL
            TE1LS2hFMXBQMktYTXI5NXRRTFFhaUkKLS0tIFBsL0dmMi9aUWl6VGdiUE5FR3N5
            WURMUEdJMi9hVnVLdm9jaHI3NVRhZU0K6P/8QT/t8TlRRzQcGkGUfv3KSh3qZZnX
            dUlxnoS70uGGkb6zY2YGvTxstJzyYuI0mxm2XhfwjhpxhfC4qP3kyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T23:38:18Z"
    mac: ENC[AES256_GCM,data:GCYdhtExMlAt5P/lfHmE06+z3Gk8XRx01BDH72aMzZQ8dczC9eIE58p1WaKYdf9KWoUAmIsYK5+h4CLf/+Z6Sws9oZSRiD3tHno8XZqHlE9FHBCq0VPBEekMVb2TB3kUgBBNQ0mrtKxhjRQWnKWVkznjEz19hDxTW1p68xxlQlo=,iv:M/Vb1hwYhm3PJjrhlz2gWHzO748B8PSHntbMR1kwetY=,tag:td8D4bS2RUzud9Oklsp/Qg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
