apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1tWbaBpJzn2TvzDCY1kHaQ4ATwAWPCJOA/WRmIMucZLXN/Q7cQKan4rgDm7S2piiuyIEp/Y1l6h7rjePIWED3Mcd+Rwhwh2pyv4jcwRWeR6Vj/Q4Nkl1jIhUTYRNTk6jWM1m9JF42Vyp7HoBcetl3y4CdFSvmBRSqOZoR/LTBD0eFTsWFlSYt4rwaKYIMm/EQa4/WNx4VjgoDaowaIpJvbmyukrzH/eyDFj8OrgNDV6s7hNUbCLwrL8GFtH24oalTWVFWcYdWm3yoSk3FfUL2lqpcPAGp2KSDA3t5OxEAqgsVpDvGJ/0LGq9ODEXF6w225bvaFLi03qfZU4p+3Wyqs6rxE+rpaj2ZF8Nw4gfuEEKkgUZNtpOpslHSPfl1W9s,iv:dKhCQusG3OI0odaNUMKdLT0Nc8D8eIwVa+2UHYl9Az0=,tag:N8N27s5Ok8LPChkULk/wMg==,type:str]
    identity.pub: ENC[AES256_GCM,data:T/QK8aybSmXBxcTB0gzHkFUXSCBrF8sEv88QJZI0RNkbNtkMJ6wVTEetDl6VbVTDj7Fgbdbo1CyLN1MctpcghrBmOpWF7zzhTw53twjI+yFrtQWi9cwTeKcywCPoXRF/UqvuBEevUeqKsCKn+9YdIM1OUzGD2RIAGQtkk91v8HZELJR4djOobpyd3k27O3SZdQH7Df7aRhARn5ITGcRvGyRDoqiaGdNbaWFz1fDcRy1u4+/ACzGVrqt1F5TfTPnhSIZiiFNUWVtmoQOIVQ==,iv:AyoTRbq6P6mJSw2aukUVfXm14kU3c7mV+nLIoMTkjmE=,tag:58iW4mLY2xDDbE0cGKe8aQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:wlbL4tZ6TCFxSpmjYKzdonieDAwkkUeMJ8g7uXa8zTQomy9AY9V1rob4R5ANrQxjJKXv/X98b8sPzrqysbO/+QwPlPbmo2Fd2jrrYyZfjrQkRML/ImmITfYCy2U40c9DCXJnGsT2cr6RrK2puCMVqmWW2CZaEuWZw6oSlDzvpKPgPDj5EKwzV4jF5FZnnQwUWb3OaLPtwnu/AJ+Inqs8dv8koQAr/OHIa+fb,iv:B+mx4rNtwEabidJhmFF3xcxzsBjuIPyWN+G8sVb7p1c=,tag:0XYV/MSNRSsD3tUaXEDc0w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR29SblNHTzVzSysxQUpQ
            VGtJb094QVpwYm82ejNmWDZFN3IvVE03NlVZCkIrSmFBaXVPdHNaU1ZwZXgzckJH
            THVQYlFYOXNDWDVKdXpnVVBXd2FaR1kKLS0tIHNPeDhaY2Zscm9yZHNQTDYxQ0p5
            d3NGVklMWkRvak9DTWpaSDFjNjhRbGsKMd/MRmEpu/q2fcpHedUbmp5jqSAFlXi2
            E1Fe4mD681e87EYB8jrF8o/eJHfuY+c4FSYWef5z7PfsSvxocVUg3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T17:47:11Z"
    mac: ENC[AES256_GCM,data:1p94xHSjfkzMzjocHJ2aH8MlhF0twnN+E9mlwlo+aGupGEhO+XrINQBQcWj/gv+Zb9qLZZS7dcZuvbOAQpaP8P5Un4ZGMmddHQr8VhD3fAWVyngt+aWMjj42HbxZQVAs5hiRhge419CzAyPwKsxrSuT18C3xIcEHVr6jCpjoZh4=,iv:QBIaKzlNtEE7VVrEuvjI/3tjY0OZjf7p0D61Y7Pq5RU=,tag:htpuASGacubo7XHAwgXLhg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
