apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:atJKPLQehd8gB/PI/x8NHZQEjKWzpNN+DoDmKjSrHYcZWnKyWyHeVNPPnrF5/oDHFj50lOechxLS/a4VebnKShiazLzzSYWn3pSvamtVh3WflfVmXQm9Q741ItsymVlGVSmS+mkmLdIPwTY/AJWJ3UVPGdlQVvpt6e3ZFQBUU5vKvI6hRW7Bj9a91hWeAK1w42/JU2zW6kxWNDP/XCY9x8e+82myGbdVpbQZjl6yBjji+nDei+MFuIkAsFT0C+Ts0c+RN9lU2gbTKaSvg+ZPNkNDX8xR+XZQXjaWcw9Bpi3k6tg9VAHD3c0Xxsg5zf8VxslpshPdiXDHoRh4FREz6hKmICNQCYQ+nxxmQcHfRwXmssH3vfY9slR7CH0pBiS2,iv:TxldZY4ckQ+vgsyzUNSEGH2MmsoPM0bKHVptCNDtRRo=,tag:OjafZ+mcMFC4lOa2CtgXnA==,type:str]
    identity.pub: ENC[AES256_GCM,data:L9iw578ywSISiNYZMClyBc9NU+y1PCAw8uY6/YtQB2jwl3cysanXQFV+OFicAihf/Idz5okPBa+ECbn+ajSxhSKLQqTNhHLEro8430vgctqrvWeqt30fWeIwp4NFwIgZQzaHPgFKupNpWcH7qDnaQFtoFabdDw2nziSmuayB886+nJEesM46Tr4ddamJL1toW/tNt61cL6GNVxCMcRbLSvqiOOrXx4SvLVc0nilcwSxWiKtXYBEvKhBan7hrGlPHs8AdXLH6JBcN4vd5vw==,iv:ib0glVuuVx6Q+E7eUyhxHvaDx5tw8OAELEbjwHo8I9M=,tag:XQnciX32a0p7vnH1e4RXVg==,type:str]
    known_hosts: ENC[AES256_GCM,data:rM60a/S+PqKsRspLlEdkYk/MRvp9fkY53Vl+i6EnH9K2mnAtq61dx/5kGSlv4TDv6AgslvVvtKBAc808HSG/XGdmvcbs9xGTcgHRhbQeDjdItaqcqFmVBoAiXDQy8V9aspuvwJbvo9uVfxYPwKskQMaZg3C1RfS+p1aiICZOWqXd0R5jFwMkVK95oXATzJT5zUsebSRQECqPnifNZwXAWTIycEdHOmlOntRR,iv:Tg4RIeE+4jRO5JiY2UyDh1TMx4IsSzbSeudQxAA4jh4=,tag:x9JOrzCwcfxqeTUZ9PHGIw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUjViMnk1YW9Nb0pkaVVT
            SERTMHlUV1dhbXhwOGRDYnRHaWcxSGxSRERJCnhZMUo3aGZRd3gzT1A0MkdEUTlU
            M3BwcG11eUdlbkhIU1JRSVdZclBHRTgKLS0tIEM1Z2MvNVYvbExEeG5qRWI4a3pV
            bHZ6NEhGRUplR3UzejFRWGN2S09YRDgKzSlj8ubk1WHd1ZQGUeFDJarZ3n/5QXgm
            m8/GIvfX/yXguKVIyv7eI3CJ8MuSc3HtThflPMACCqTL4q/+/Ecr5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T22:15:57Z"
    mac: ENC[AES256_GCM,data:lhKlDsZAOWb+ljF4W1zcH5rQW60PzwLXZIHUcX51XxmKHiFwoO6ciMr4G22f14s8QEYaXhEXKrxd+sDjW1Sfktbk3v9tJBh23j1R3zpckkj8WQHo9mlSf6sibWjDeJd5nSdvskLn7ZwfYl8ZdjgORLGVyFWvjXEDGg+pVdtqqkQ=,iv:2/BrROa5KiIU5iiuHz9icflf+JriQyXxZ14DnmllRVA=,tag:BQURkjVHihyaZ9f2ZCWBlA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
