apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3DH4WBIiyvYf6L4e1Sif04o277d/KyBgKM2Sg0iTKfLlzLff/rOoojYkvJT8xXoCG+RvwdnbBRTDk969Mb6fv8X2GNXMaSpm0NEdtXw+jMDGSLL7Q+wp2Ml2440arRj5dnFZBPOg1Yxc1Gx1+5r5AhGECOO1Fsscfv1FGmwZGwySU6NoV9G2KPBKOA/6RuKmjqbY2Vb5i0toejYgndgdRCc657iZl9mLo7DsJMqgV8bke0500omwaooopazEWVWUPT14yZ1OXFX0nqw2rXLuGZKpjMI49yggtw56W+5+MjEC68rsVGhi3vm2IyAC+iF1USKNB/LjrY9s4h1eigxliWdoH1tWaunHNnkkSz7K8lHI4Pz3eqo3w/CDedAvbgkS,iv:mHjujaGidCqmeRCj5stWsMJyS4H46Ho1zU3a35fAdKM=,tag:KYmAJjrrRaknZqdEXIOOQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:vdTkvcOYcG6/i8MoxU2ZUVYj9+RQCl7SAXP6AjkVAteJSdk306ZTJhTU7r/5ppv/6CfGpR31tcmAoPfYZjNGmCk3zqO54wb0nrEhmiFuAf5Hz8Rm3cwsNyAhdnzEhC20wqmAXb5iu9buepyX/aA99NsGrFUav7F6YNMR3u7DyE5Ugrf0+cmMSHHpX8mea2Hqtdzx8dGKdmXz0J7nr2kNWopJJv1paYsG2Lf+nMg9Quk4/FoTsIQ0ccM6OpHpq8kr3l3ZhBub2+mtFzSQcQ==,iv:nHXE7aZ56sJChzElbvrgN3eOR6gZyDh3DDhfU+9R/Qw=,tag:jrVGEvesIZsDIt5hOw2IlA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Kj9kpXuUKKTRVFkyUDCjbQmfTuuWfwzdUOPBognXHyDpB0F+PQ480pJUnFNA/OZvrkF+hXatnRjIVKguUPVdyQDNAXLYkL4tS0WdtJ+nxkonDX12HShPkG3XamyxpHGEyO1O5030WtFPxbXzLIEQgh6CqIDtJLqR1ZB8JuYU/6vR3gn9utVtaiHxo9h531GC4auxt1fnqWjXHGDXdtwMoi42DR9GlYFtUpbL,iv:ogMEC0AQeeMpBMsOm5Qgzr56/a6hM6Lfh0zCLzEp39c=,tag:30PjyPKlSwlGSvIMMLMm2g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6REgzSnA2RUh3RUxJVUYy
            d09kUnZ1ajAxVUwrY1hqZk5jcDA0aEZkRGhvClZ6OVhEZVlQeTZCK0p0OENzSXlI
            QW1NOG9MVmVLWTVlL1Q3QWEzQ0M4MkkKLS0tIFBZQjl2QlhaOEVxL2Vpa1E3U3F5
            Q0RMY0pXK2hkRUFMQjJxdUVTcHBhdlUKwPyrmfD7Rzr64IU13/pedqGmrstRqU/V
            Oc8nSgaqQUf5yDQgy1veJuP22mLPGMHxvEbsdKzlT1kPEOrAm6LIWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T22:49:14Z"
    mac: ENC[AES256_GCM,data:veY1r0ubf6t/2bnAGhVNk8w+Oudg11wP/49yyjYQL00fIVZYjthk2TmO3jKPB3ijFkaLUHMcZ/WTw2iH0skSa5VqQSRigkPtrXOOy7zX6/I5f0p4CFZ1CWr9M/r8XtZfAKmQkCJOXHo/FnfbxbdlGs5GMGiJSjzQP5Wb5MGvVFs=,iv:ncdJp5vGiMBDljgp86+G20n77/8dNYh6e57KatZrqbo=,tag:sH/ChpAt3AP0FD5mPLpIPQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
