apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wXQfQirIkdAwAT1+9iRZ0IqXWxiLZ2ViosNu8mOH0EMcxn4ks215Wmg8bcFwcZQIITDJpQj+mRROSigicGwv6hX6Eusf3ylpVUoddajhBgLmTW6v+rsRtszMhldVKWDM3GvcAPHp58XwX+YEMkVu6A/azJ70Wvpe3ZRVrggfcMu4x1DxYHVa5rI+fvgnvWmyRyBG1EQ04E42ICC/gU0wHMYJvsMyTYJNrqN/TRS+4RRDU3DQIEHeSWKHymmRuMavz3xRCsvdijfc/Guh/lq2jhnpyy91C+l3hJpiOcEGgoH3Fo2FLXWSYlmIEK6OlkqUxidr+a/CZ0GPbA86kHepeIgC6+P6BI9jDhhJJT92usuL46oR5CWuyyHW8NIa0pWL,iv:wH9I60/ponoUlfYEKJGJtfZ71U41uLYYzVyOC0ei9R4=,tag:2klg/n+9MGMlL2mBaLyplg==,type:str]
    identity.pub: ENC[AES256_GCM,data:iRoTiZJUMpUamt0HIII5dO2pVOuZVn3gAc1N4ubHEx6c2RYlh5tprXWZElWnfBEzFA3z1eRqgScIZjj3DJOX1obwCxkkkWfQXeRpX5EZ+/8IekUAHcNquA+heIYr/tgnCiYwCqsWDYSx1H7EKJLGdt15gO6p/CUfYOHYhONFxBEA81z4JBtt5Fn5UjG8z3MN1nJrax85HDEGjkprM2ZvswXr9HRaQV/l+FKmUCZOJoVvPcWv59lCxUL3xRpFlNuGw0h1/hOhglTYlAU2qA==,iv:ZAZu3/HnvtEutcduzX7kKHXxmiro/Haf6xrOMGMYJhg=,tag:1o2cSQTkPq+CUc0aontusQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Q5Ik4ofSeMrD7FWquff5yUpD7YTlLtEbjh7umpeuTZFp7qcqTi/17NeSsgCj0pxfaogP2BNpCED/Ur9yD+n7RwmDVnXyMGhTu8rTU/XV3ZLWxZV+MfGQUN6AKuMqKuoPQzXmjsl59pjz94pD10sLv056biyETA5vUjLD8yc4qwege6F0YBxGN3zGYlQl8p1gGrz/yGX7udwuM28deTOH1b3/uPUT/+R2bO2P,iv:ApSyiGEpnGPrQO21t0KdMxmxbyeocV+GVKkKnzPCmBE=,tag:tjs7NrIlBMh+i2o9ruMQIA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ1BudFNuMExFd0NRSHhV
            N1RuSUM4NTBRNklsZkFZOFN6RjAzRzJHTzFVClp1T2VwM1lpMUhQYjNWc3RlTG1Q
            dFF5ZmlQelRoN1h0VndaSExIV0kyWm8KLS0tIGRMM21YeDFpOXlHOTgzQVYrQzJ1
            aGxGUHd0V0RrWUVoN1V5d1ZkSnZyRncKuhRg0NT0kzjBvfWL2e3JDotsSVgblDfW
            412e+u0FSC/s/PEfGhvhmIvVVW/jlEnrPSQkjXZtGFRpMQiTdtlJdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T23:06:16Z"
    mac: ENC[AES256_GCM,data:n7Y7zgiUc7FJ/0tq4HpXqsdN41EbfO09Wgu4VHOkkLizIZXkBy84jFRDrbZXgWevuKIKqLU8qh8fCu4+0YsAg9TWytOUG8TW830fvAiA/7HZdNZIeCbWXip/+fGH92skPyvI58LbwUvy1caoZHSoQMhmpjz9UFl50L1gdVSGH7o=,iv:0eVmF6uf6YemnwbTz3WJAyhOlUx3VuDb6uEYo/yiGPU=,tag:I+BxBF5n6Ckxh9mIMmFnMg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
