apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jGOXVsCyj5q2T7LbDWVnzO5KaeZqZNUBm/LCV9K4pUPRdx9f8FOX9zRIBY/uAYkCYX4k/vRa7hMy9GPLo6/z+mNLPawPLv6zUyAgfYn0xd6qu5IiB16se2l9o3liBpL2aFKk0f99Aflnhkat4hc3/yDqlWnajypsfqCMlDyLcUhKasb90a/1w6CB7Dsj7/WMErpmTpuUfupGXnZpaWH1UA8ICRJXugL2NLY7MSdZRoBYcyWewncrIAWEQZ95fnabI9kCmo5mK1/e5nmAsCJt9/p+tbdfFoR7LI7Nps2+dqMc9OUvP7GGtehxNF26EW2pbacFiD0hze78d9kFOwYhqWx5NYHBALPWQoDEnQAv7uP3qhyK3oylb1QfNR2KGLYj,iv:avU/Bnl/VL5BJI39HnZGDSKe9MvTI0UjOl6TvuZ283g=,tag:9LJ5Rfj6FHLQ8/RQC7theQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Kc3wWywFt7RraS/HCSJ+BbRYZ6Fd77w5tf8cB4UaW05joq7GmrVvsG/eh9rg7okkZAJxiZ89Fu5YvBYR6jt3adR1Ox8BHIFsN7P6ssfPc7EbYu6DzeVDkgyOkrjgvTUwpTwldjSYLRWelTu6BVor2XihtI5yZJJpWAQs7z+txkvRLtwgOMRZ4A7DOepWbixV6kcH55OlqvK9mpDAqHEYU8v6E678GGbC1INEetyFceGT+1EmiMX4dusL1PXlSj5755ctQTYgcUeYfrFdrw==,iv:yM6uzljKbiumxHUts3Prmus2WRJYF36YnfKv1UriR3g=,tag:B6EBxJvyVaWL+Mf7HcRINg==,type:str]
    known_hosts: ENC[AES256_GCM,data:gZztSrX8UdTkdRDsRDh3Z9v+fUVU3Jz0wDq4e5pbz0ndQP01nll1FfxuNhSSFbM9/KxlLhmY0SXAyf61JkAXCQC7+Q3wbcmmqkkuPq+Wf2MVGV3HH2lxrrmwOsAX9tipCtIlLPfob4+XwQ55IEjrhbnG4QOI+9guSnD6dC0bSpaqVaNYgvPu5F5kpNGEQFx/dWYoK0jvKwqoM5Romk3Qk2KyKPQNXFql/zet,iv:xeG86WNVNobFskWB15a1up3LINkelY6o1/mEr9ATvx4=,tag:Yw9L7HtOp4LkJzc32riHIA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcjZrRTY5RzRseUY2cWRp
            SFRqMUEwczliSGhuZEJESE1USThSaVpjeDBnCjJodXhoU3FKZ1VKaFpVRlBvaEow
            cnc1R09tVXFBcVlhRUZGb1BlQ1dvcEUKLS0tIEtlSjQ1TnFjSkI5b04rU2xpSExS
            WTUrc2c5STBVdk9sam00cTl5RFZ3MGcKXBTS+dmdjH5oppSaaFRF3PsMrTAX99kr
            q/Q024Lv3tE1jwd4BHZLXbgubUgSmNsoQU3vPZ1GX4uPggx+FZMFRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T18:28:37Z"
    mac: ENC[AES256_GCM,data:gfhBVOfw5fglGHfpt9yU8wZF7m/ypEA4BuE/8h5C/DweiBNFRoUsGmBOpSslvNnVgjx/LWIhO93RIYTdlUkzG5aJjzA27ln8mJ1bp370bp1zbrkJd195eq9bqe8HDfHTTfiutA7zUoE7WHW9NJu7fwCljrNBuWk073UdXcnH3D0=,iv:2a/YyNuPdmOt0XtTIbXNZ9I4Y0hvgpINHlB3F+bm2Rk=,tag:U+DqdDxzuLk/KqKPvv9aog==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
