apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MY0bphsrE6Rnxwgxz0hrgQYQrKczOilnJZgwvSSz5oqBVnnDyNQsxl0WSySuNZ9ko5BM3+lwPNyl8D3qVRm6xX3mMv1aSyYwAIiLacXuH8rXLgLwb+h4x6MMlcB5Kax/mCHAVukJ7tAyuDY98HpJ8YMbyUlmh05+EaJKCxRZ363b+80F1757HGOm+YKCbPe1csV4s5FczgBeblrD7kmfe+iUnmQH6e9WOXqgldZzaUaDzPhGoVXxhpSlCbY91jMZFlJ2nva7IWH5d/QYzzyZfgMM2TftzyBSsEhHt2DM+dGkcTos5D0+h+uyJC9FGuOXAqCJr9K9vwmRT5zSh+5Id3T8M9I1lN14cR1+YWpUN2BRxMlZgY35ycL3g7eon58f,iv:EyYbgysfGTUSLN+YCaucW0/LA7FQgP104itLXt1w23Y=,tag:K+oI13Wiv2+JjNZLLxnGAg==,type:str]
    identity.pub: ENC[AES256_GCM,data:lNBCBa3MGYbMNpCXFZqIQd6kUIzbyrxRQVDQt1e46nIU5tvBk/Rud/f7oreZISBYjQ3fxhLjqL04lqR9DSy1XGYUUnAnGdIukZVB9Xlxhn6vgJ+5ZAofb69nwgSuHsa3udrFyjuYcyLy4lRxgUmFa+J4wcNJT0fGIv0SYirOMniJ0E/ivYGaM0HtksKvctJpvDZcIdKineqJdfhvsq2H09I3Q94XVxAL7fWyCiFdtitn68TMz9Id/qPE6MtAeBodkzJ125BpbnI00ybR5A==,iv:9ijWqWnga4pM+TPW8eR1c3D2333vtVh+qbjJLlk0koQ=,tag:IBqorHerLVFOs6hTUFu7vQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:rsw3MH0LNz06WbkHkHVPo/y+gtYlZF6UmDCB5XUoFNXYIGR2aVVTieKPQzNSOgjQhoJdXobPt0+Lwd7PvvpdpwrW9QjDJpzkEinKmtfy62HGUhJkFx1QxfxMApGwYSQDMnCdhEbB8RxcePyIYXKjPSGZzQFXFn+h6lhkU6ZVfrOcq8inrGQEzKkjj7kZnQkShnczrsEoRe4T1NmPvyhDxSBk53MCkTw/cD1p,iv:jrCyuorYdJddUGc+xdcKFDnpeY226tjz1bmMj2W5Z70=,tag:J9oj76o5SLtObndtwIDq7A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SzVmUmlZQUpUZG5XUnNO
            ek9UMmlVaDhPZWhpY1lIei9FNlhMRjhWcFFBCnFyZ2h1SDJTejA4L1RGY09ELzdS
            VVJaaUdLeUZnclpvaThpbkw2ZzUrTTAKLS0tIDdvVnhzb05DbG1zYWJ0QXE4MWVr
            bUdvWm9ESlJEaWprU1grTHB0aGJPWDgKKcwdsNhXscrM29LTXaXJ5IpFMJ7XQtZU
            I2iZ1qGDYlW/jyKUgVDhn9wVA80NlTFynPG/Lo0dUP+Z8JCHnaJwOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T10:30:10Z"
    mac: ENC[AES256_GCM,data:SCO41h0I2P6XGXBiG5K6ozUF0iZXqsbNoUtcEvmd/i3cBTwRTpDErZGtuBB66qoCs4r6b0YlcLmv76kvUDfiCf59TPMBlRpB7hvJ/6mIxqhga3qH9tXOd23j+nhHFz8sxykLg5cS77IewnzXSCK1eOwZGMeVKQ7ATh6glo5eKtw=,iv:1mv+ympztLBe720Na3nyN//+XPhUjHtCRSVBRC2QNk0=,tag:OcuBjXK0YSsT4bqN9VIyvg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
