apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SG6n5oFRQKTZ83aUT8IGz6tsQej3v2B0PHbzqjZ1B6nxnwgdu3n95JAzW+fiAxJWa8gc0LLy0/2nc3qVeFRdoN50961JH4mcSsuEQe/Hz1tb0070wF1TrFkM/TgZzRQUPrYF5AHunVbBpIX0fpRMDZQR2KXTDlnaaQR46l/ZYuYaRNzIcIwIaiEIo5E/4dVitn2wO+AmGmYEqA6o0ekXn+nV8ByryLiVsQ/4HRmhPbmr5d7VgP0gzM8eJbVdvAxNm7AgXweE0RMZezT/q3bSwq7RhZqFYVibuHldihf5+uCqZZdqq+vFux8B5vIkkBNQ7ZVjhjJJ/9znCte0HIsX0pgDU295FIW68nNvNJzIP4aLvSrK5NUY+u5o8AkqsSw+,iv:PioEhyz50z5/X+G9ySguPac0mmnzae8ZGdxVCCarqkU=,tag:6ipuUH3BqgaBvgQe64iUFg==,type:str]
    identity.pub: ENC[AES256_GCM,data:a1YXGRCeQAEOvvbtk5Pj6l3BDInL9Zh/JH2D603WDFJV/DHDy1sBoUt8vgIf6LZXlkxYLtZgJOs5yf1mfccXfunpwSwxc2KW+IZXMEYPnZ2ezs2RmVBQfx1q3HeM9+nDm2WyCCfZO2P62Y66noF+gFn2uEUjsKgMyyjlXy9lpsLuJaqpCmQotDYKPYxTjLLvr59QkxxPwalKXEM3F7uVSphvdtE8n5GV72k+ZSsNVIk1DSptodAhcAoHiV1zVkXWkBYYA8cCPrqo2CL+sA==,iv:YKnBXevCA3Hwo3+3EW6YD/4owgcxtsI0ywi0jMThf24=,tag:Xj5C6EVia0glt11sFGXllw==,type:str]
    known_hosts: ENC[AES256_GCM,data:tkuIWuQXCcE+ft3A1J1sAaFDhFIUuGl0nJ13IQl+N+wfvoHwLkTafonz+FMoQzKcedVDtsJ4Oby73wzsoAMUf62UPko6iW3N54gT6gXkdXXg5GII5M1l5G+GJUifcqs1LHEqPnyQP5xBwR6UmMp9kmEUTWQ0MtZdZZ8nCEYzLUJ3pz81s3kCYWHTD0Mi8HGRA8rM/nL/O+tfV002YzpFusKQ322SEgw5yMt/,iv:8wuSgkJYzpD/qY/p+TfVqIuZ4iWofEIQv0fS+HTrjjY=,tag:bbeBZ0QU6kXf0keFAPXSlw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaG1qUXZINkI3azBWcXhE
            NGRtR21vd0dpNHBxdDh0c1ljKy9rYVFvOUN3ClA0Q2N0QVVvQnA3Nklka2gvbnlj
            eXVpcWVRYVhlWkhFR1c1NkcyTkN6WWMKLS0tIDF1dTkyQ1pmZ3NkajJUN05uMklB
            T1V1UXh3WlRwWWFiNEpLZElnZ2ljTFEKVbkaM33tFBuvEwtOQnEt/jrEM0w7LnJt
            7MScU6e+IY71lvhjB4DFPc7f0++sVsoLOHNvjIOhdZ85Ci4F+pNNpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T14:37:21Z"
    mac: ENC[AES256_GCM,data:Q7L/baMO8/F00LKaYbJ/gnRUqnPXJuyzf9ZCCxuujZ2UvDNiHAvdl+V5sszq218REhwpiKbGtly9wPwC8FQivoI7TXU6k2e91lGQE3UK6h56jorPc1QaKGklfEn1L6T1uX7Ptn3L6TDs99igY8xy+c6BpAR+JLKbnDhP9qLD6k4=,iv:oRjMKcPnUuizBqhHaC8tFSgjZJwqrh3WTKMY/oC06HU=,tag:W4JnGA7AWw/eWL+jRP1dDg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
