apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ez3WAazNbJv9dAlwjVYILmMpAUjlqlL6ryvapq9OzZd5fH3dhGHtRcIFwP0TEQmLd3DBprRdqzE37fUrh6mG2SRxYGUI6QlM8iyziXsB/kJ2PufdaxCxYi9d++uMufL7L33JALYf37gPKcagoMK/wKMGNpTOBfDQyjMdHFns7Iwl7uMOR6f/sYxiYcsS5emBUjCTm4VWFAz+NzF3N+yklkUIJDjRleRo5AChivwQXDPlv7Ian+BTHVf2sDjbz/I24KOxtR8rMYjeElY9MC+9bC3BNJpndPHjNxw3c4XqWUm65aNX6CxN4bhQDpQlvdnfRUalNXQ89C88uh3dp1v6eXUY1jRwch6qYzciPufO8bMIPTNCA20bhT/hOiuMAQ7/,iv:5InsfbEHuopfmsDOtMVg3rDoNHbnaQp2K8cbpYyIDj0=,tag:+9vyCLS8ya2L9SitDd9cjA==,type:str]
    identity.pub: ENC[AES256_GCM,data:s/chNQ47FH8zF1CzsnPVlQx3pYathQxFFm47Uwey4FqmvrVW4CbEs/u68vQI/uHrYjEwlPFjTktuyFl7UwncHVmFsCr9XjkFJTuaUcy8fPPgnYp6iWfGM4XWx4MnksOi8ndvCuGoZmYxydWV0NtH3kv34ghjrAlNM1A7VaQQP7yh/BL85Gj55bXB8WiuIG6D/5vMQFyXh4678LwxrSuV9WUECWinTHNrbDHJASlRX+ddijDnT6znwfuFAH6+I4Aod0RFv1W4hnYSOZGENA==,iv:MA1+6PjKJZVLDz1ywc1NK/FjRLJ5CIo/Z0QXtODndD0=,tag:A9cWD5FSZPTFYpIxSsyfyQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:01PrAeu0jvtYqVRxSdAmbioqgLNo6+zI0yMlN1vLbgGGmLmQ4jtMmZa+S0zVQrApipQcB0H7wMsUv9/dRtxlTcQgT0DYt5K67MFZzdRJD+Qv0GmoE90Tuui+eKdqPHkFFiFY6Dsh9iMbSLSbG0zuu9E/EeEMMdxUQa0kQujuBCPiqhdUHADsStmsQWKz3RyGNzryKFBR0fQcc2H8swQmGUidcp5C69Vb5M+Z,iv:cL1O3IoJvj6pIV3NCj4mSlzkOPiI4zK62edDMzCIhfk=,tag:pV1XvbtdAk2SuQhJX+SCUw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdEVTeGszRE5GdkMvanFq
            OXA0NXpIOXlmY0dZRSsvaEZvWjFnckNaTkhVCit1YWI2NXhQZ0JFbUl1YzFrR1BL
            NENOTVNYRDVyUjkrUjE1UzZvSnNRZmMKLS0tIEcyN0d4VDJ6eFBubldLK2dobWJX
            VmdCQ055TU5vaTlCUkk3V1QwNndmSG8KlnH97ozzbK7ObyKjJ+OPunqdF72InJzg
            2oQLZ2pTFcaSpQrRGiKMJy6Oqif7mU7HCMqvYr88URedr7W6A9lckg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T18:06:50Z"
    mac: ENC[AES256_GCM,data:QGVvLrIkYp35FrKp2LAC7i6tCCYJSzjRbN44hV4OthAU2At3RAxRKpgYeoXvHpnOzEGnnH2g6UjvSXNPVj+20WbdejoSC9ekzSV1gDm7OmiC7TCOzJwCX5AbDfhsIo6Xcv3HPvlwvBC5uP8u4UPWFiVl1hGeb97eI78E8V631eM=,iv:dcyBUpSFsVRrwCU5Ai3Eb5WHqP1E8YMqP72+cYJCPbE=,tag:Qi01oPc/LqqX86qQC53npg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
