apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7kP/PMckyayL3ZT+NF/qbGUWFHhWyO4EMLsJeuvyH2j0ulbJBADEJqqQNvR9ftuFjowj+zsrOzx74TX/TBUxb6+wvyxqZj8qdxSQTl55Vs6oSUM2RQpLJIlwFICKfZXzEidRhdzieXrrJzGRD4W4rqrS3x81TfJXUoV6stnHO5BfG2icH+xGkuUR57A3NqdKlYNaP1iliU7NTqsqLD+hKIoYTHDtBzw/XU8OsfRaGIwlxi3pnvB2f2W0+Gp1m62DGF0B5da0rFNTy58l14PukHGr3oXZY/VHEk9FxYcn0FCWrvjmU8nmoznLM55As5qm8+uEeaVWg5bsi6utMFcWJEwum+uAuLmAXrMcT7OCwLTLGQtidbgNmIbxVQYkWP0k,iv:2TaM57sqq4g4A6hugCBvKpXdhtRJ50WrxyuxzyVilO0=,tag:jhiDMpLGY6eflhsO9CVTZQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:cwCyMJ4U+u+6MEX6QPdxB5oHwuFKnjaBEwcTa/l9kfV61aEQ5DD3lfqgv8bR4rCgJ6rM47yTqKZTo6nsKDtGFWItwr0nnjeppqTd0anPR9irk/iGuntLhuNiAzUQo83yEPBeGnJlykQaQIbPyVg+JzzgsqVx0N7Cl6DEG3wlhLx5LhdaDRIzdjO708zXKgg2FglnaDrZLgYvG2PCueteg8F1YK5BQwEsIxf9GOLv38Zn4rxCwUiFKQbrrgKO/PhiPPbw8VnDimUG4PaXLg==,iv:RmG47i/5u4soUrQ7Gc0DUf1uyLPaaBtPdwzCt2Ad9SU=,tag:LTWsq3Opg+o9TIEJhJ28sA==,type:str]
    known_hosts: ENC[AES256_GCM,data:vwW/D4I+mR6pZA4AlSulY4Ba6jqeIyMQUlwLR8PBLU0gKm8Et3Ik7DKHGCIF6C1MP1mOmnB+dfyvbQ5Kks7/gzNMOEhbZoiR/qRQRd7p3Wlvnp8UT/strLOJqzIbRDTX/UHWYMDTl3GVlFV5LejAoVcX4zTrq0epbS0fwDVUXCD3yl7t2Mp7PsRNF03Z06ELeD10yCfWo8CxSLKkgfy53U3cFAxkw7ynbmTc,iv:1UVhC+BOFwh//X0aDHz4/WTBE7O66GukFjHT24HBxB8=,tag:X5mCUEzzwU0yARsjmDtBsw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cm1sdS9BcC8wVXpYNzZv
            ZjNMWUdaS2xvclBCRHRXMkVrYVlyK3M0OTN3ClpvZGFqaDB3ZGJZUnB3SDM3clgv
            ZTRzZTFkRUlKUWJSWkxVZmNPS2pwcG8KLS0tIEgwSTU4NmttUUgxTjUxeFcxdVhK
            M3UybnZQNG52bitIbGk1V3BKQlR5Y0EKcVQvhcZr6uInvfjSAdXOuU4X8JMWidjU
            WI6mhxAPUFEnfJcPpznY+xZLQ9bLd7IXX7iJU57zz9zeAiChBYvRFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T23:14:08Z"
    mac: ENC[AES256_GCM,data:oKWLNl7aJVS9ltQDHTL11Bp48HVWsbIDwenmrfGszUQuVQOkJhwa0dE/uRoqHHv/Yvn5NXMLZROQ8lvbmLCTxHKCm/00yygbz+8FhypxrfkG8taukYGKDtpfvPY+S3q89je6hobeU6Oi1q9bAWcHmZ7N0GnbPxXaB5BTzg3g37U=,iv:E/culYA/SIjYQ+170G7fEH/EUBQXng5z29ljxCNGAQU=,tag:xPbFVvvRepsJwKYO5vCmtw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
