apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6Ey0DwrvVelh+HPomCyXdK6x/bJiUDJ5J0V4kUMF3qAM9Yp5hsSKLt3QberSp9nuiAKLsmAGSQ/CVrIBhoxLwhacf3Mp0GMGDuo7q59d+7YB0v0muqtjXowe4CB2LVtGisMfXKpI18PgTGVDfHjzLa3WTlzy2XDDQtpVYKszXmg+uc0bi1c2DRMs9K/HS/Cua1dxWvfZ2qi1VwEE1JLM9QRQCIQjH11TCFqjMkEraiASFcraWHXZznSgZCeag3k8+FLhERhLq6mASEm8IfnXGGEu4zXVMLDZx7yj3eDaet/YCO66YaBcgixUkFmlOUazaA/ydOFRHxBosL7bCfSk6DdQo7M0teqPqDWLLCjyymkwmtYy6xsEZM9PkuDwYJm0,iv:HCrpryIMAtiJtiQ3um+BBX+fj7j7AaBhFk+R8uy2Eps=,tag:jq0bLwT6nY6mphtiV39VJg==,type:str]
    identity.pub: ENC[AES256_GCM,data:aSTYcBw05k/XHw9C6iY6svU3gcV6otDFJolXJ9+JoEIeRL8y852az2r0snVLV6zi1c8cfGYOiwQ+vvPEVG+ck2ZtiSfZZ5DLjo+IqPeQlBJDvRfqmYsXIpLlCLt6snXY4Nm75PD6W5hEstq/dQkQwC5f4xhkilM0HcKtkbb7Wd5KUJAARvfSb5d7UNLyfbuGV+RW3HIvJx6dQXXAE7zkZZMLiNh7oLGgdUv/ZZjWb0TnEPlRn18ih8Gpwncsq89bLJl2Ocueq8AQ5QVSjg==,iv:W/QYaL6DXl8P7jd2AOFd392BT+3N5HBZRX/79upR0BA=,tag:DeO40uRSbpZEscy9iP5uQQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ahZYhNm/KRTzaoJuXxgdQDsWWC12KYQ05zcUV8GtTQ6QXsPA1+bNQB64qDexzIXJOwl46FJy5RsYostsLXQFXb1jocolu+pDf+unRJc6JUaCTvJ80My1+XJPb1BpFpR8COQQDzI9VWb3bHhHv4XlzEHyUJpHJqjjOK9ImVbZHWhTDlrzEPtrQVbCy39TBtHPKb6T0LXKXvyTQNwZjF3E7r5d7cFkSNlQwHAF,iv:Cyba3GBhCElwk2DJdUs2pNknY+vgNAcVq2Ofov8WmNs=,tag:mfF4A4Qx5clW5BZ/xS42Mw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOU9hd241RDRSeVQ4OTd0
            YUdSbjZtUDZWSXlwQ09KVGduc0Z3bFRXL0NRCnJ6cy80K0VxenNSZ3dVdlNUZ3d3
            bjZ0ZkpoeW5rODh1TTNycHhHakxBYTQKLS0tIFFLcmN6MU1EOHVyaHRCWThUVTdS
            eXJsenM2ZnROQW1Mdkc1Y0dRd01oclUKEo0QYA/HjqsjNBGKbp/AT4iI//d/qP/9
            tGZDblIFCi8OTJUuex8Lq38LG6urPO8YJuxEHzZPanrvueMNWOFvjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T17:28:08Z"
    mac: ENC[AES256_GCM,data:kv8WIuo8fZc03+qWhZSI6nh0CsH6PGkx2FGVk9OYBnhgd7jL+5iT9Hw3aQoPSe6JqYIYXCI/D5Xp1ibsM6aLBYDaiAZ1joluwgm4qAGSAzkJu8kb99Q5/GI1hHW+nDBhGT7pTqWkHDxD8Nc+eWhhxYj+JxD60NvAIepQ9npidq4=,iv:LbSoYHf6/xyUgrl9kVVqLBIGfKxAAfdm/e+TVdnh6Y0=,tag:rzq6KyvRkbr4bSRZK6IRWA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
