apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/WJ9FppONeLaZDkFP3x+LoktkGdWwlR0Tjs8TdnhzpRrxWwaRTlEPBDu9s7UPrECh5BisBamxgAt9evdFjxeo+SF4cc8pt28GDDF5EwBx2XlP831l8qFdqgo+WGkJU+6ecw7He53ms0rukYbptvjjZhzYGFyxp2g2csczKWdXnhZrc2V3HJ+5vCV5R0rwCn8bSodbvGywskRZxzxfIsIk3ZxOiHxedXfRBJaiACx9VdmYM/JI5bT5F6zOMfm0TFdSxjqdL1iec5wJj4D12/FZWRosPPC1fTFwN7+GHZHXcgkCSWpi3ZVI5uocATDA6yGQCbJtlToZ541nxgBB0Oq1BZ67g3KLXNE/vwF7yZy1QfJ0pYb/cOXa9pFNmDtXPq9,iv:WnHkkw5V3A8sMTFLZq18nIsnunTe5eg9ucKwH3xoYvI=,tag:WMo1DoLYr7xuHemCHEr5cw==,type:str]
    identity.pub: ENC[AES256_GCM,data:EUPXflk9Pd4Flp6u+HwHUmC9IoDNuD8TXD5KrQvGFs5xeBKEO5QAj3efCtfAR6xe8xDTC+duWOnH46kdWqEP1WGrYfaswlNKohywK6uxsoHQgjeZeI1vFC/lPW3vLNXn6TDV079VGIpTZ3tHPynAOKSeUNl6m/TFHlKQDw0k0gfE0E61LRbpSKrWuMGJ04Io8eIuaF3ApC6EYhqussqgdTucuPy+Uk7+Caqvs2ApDjYLH/ekuEC4SG8BkH8lNJ0jqD/RGU/kL6DtCFjZkg==,iv:bHC+xYs3dGtjdKvzKJxXWEX2QYKAzeGRyosFBaV/+ls=,tag:ZNUgNTVBpVh0zQ9EZ1AsFA==,type:str]
    known_hosts: ENC[AES256_GCM,data:sIJRK0xyuKG4R2eJWVJMIDVB7lv8vMGHCnvpzGRDS9VYy6J+YBfIY5FE7qANld1QLUQAswHsjywC5qcGtAVG4pyFxbC9rSExBE7XnxVNjaW2mD480lwFZHRL9QtwEJKKIi3kYaVPgHjNuZUs+dsf1AqD7EkrjljUBRDD/33gInQgmGPWKXQ1xDJ18k4JoAsuPMpqIAKEBFujzTWVHLym6W2WqeXkZ3qv/PAV,iv:GAZX04P8gAWoWgnwYRnzILHGVR2kxMb96rvv0/pSUNg=,tag:Trz0ilrqxdmu5RmSD6dnrw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZzF2SkUvWTRUR0Z5a2VF
            TE10NmM2YkJUYy9oUTFOWEJmUHJPWDhZdTNvCk5xK1JpNzBGbm85empyT3VLblZn
            NkpWTlZlRERObGtsbnp5RENaSWp3VXcKLS0tIHJqcmZzSGhJWWR5Q2xTV3IzUFNT
            VVRDRVdXMm5ybHIxeHJlUlA1Y3hVRGcKoYPJX6dA1/zymw3W79pFJDqr5mRV3gc2
            pleorxRIlJuSbVpdExZ3HyU5ShE78uo7nPOGXumjdmPlnKlqhsqNng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T11:30:54Z"
    mac: ENC[AES256_GCM,data:TZVaBOd6wQ+eagUdSWljT6gb3nXONIcm/wQArV2JAJtfwoBi2AithSgZ7sg0JZPXwGDyGTeHxsBG+3K5Nso7JwMa15Unm2XaMoxzCv8axKYDVwsL6I1ZP2LtPoXvgHzQ/xMyg4hfkA77wDOcOFZ3aSbFe5jK5bYak2U4lbqrWbg=,iv:du+a5epT0HoGu8iRwxr695zTw07czFidqbVBXmF4lZ8=,tag:VwGj2xVT48ZphMv7v6xO0w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
