apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WqOIGyZ3558jq1xoWLLeBqrSlOHghN45KxcwFnanAcbXfP94i3aQXGN3irOBgCrsSzxKFOLQaqCk5w59kMJRD81q/J/rzDgiGGhECEe11Jc0kuCEBQahddZ0+65vp74MVYs9zWzHIImeFTAT2EbASu3DOCTg4/era1qnb5m8q3RnxDABao9k4xTZNDRvcbL4RLtXfY9CbHLYI7S23hL808fm7C2mRMXU6YF5kitfsOXTtOIc73Yex1meR9DFardnJEvf17y5f5gW1zLqVIfWlzyX3J2c98grIDAaKqU2OvkFJI3/Pc0c/YhNZi2x29p0wkUfn+XBFgASBD1PgPuzksjIjq9HVPv4ldscifYtwQ/Q9lsaqu7RXrhf1mJfpyn5,iv:3bCfe8uVZQY3EUUkOrl1bMIyEC0NGudbEA1rEyn1qfk=,tag:zS400VJnvSFl5yL4jiC21Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:bgVNUG+/oOd5Yjm2wdZJcOr1VybY1qaSgaTqSEQfaFFeQQOqAqgClGLm8QEBQ2S2436+kkJ8j0vSbH4ptfcZHjRJWHY0nTiD5VL5H5/qpuhhBufHeIcaSmiQBBXxmmK23Bl2AhaEJGPu+oEcdjuC0sLHO2KHxhMdp3QEPX4qgSgIDYCiGoJk05d6eF4Pva7X1DdA853lCAy8ejnT9UlEl4bmh6rPUoqZrra+PylZ8Sz7ChtlQI/kQJaDwu6kcBLFRGBy+r67KRI/RlzKTw==,iv:3u0TcjHufCJ9gC50SWaYu9Hk313GQbSq8WDFG620/Uc=,tag:In9Q9QveHj4W8/pF1s6+9g==,type:str]
    known_hosts: ENC[AES256_GCM,data:kyGNkESpdYQyJrq6TXzUqvFIcXXH2/7HM1XhFrExo3XQr53Ul/l53tMjLW5tYfqdnBcH0tSPrmL/5v1oO17FGhh5JVcdi4UkbcOi3nVZLwLv9YxMyJZGzMS/mtcQWf6HcmUurv54iNM30jolmvsfl80PQGkPvNlw8ji91qY1f7M8WD/5sg9DOROLvq0zb7vB8HwGcnQ5XvQh3D4LCWwwe/z0E3OwfXL0JPPa,iv:Gt9BdabUNDM5uBpuIp4vXPMRDLM3U7S0iZppJGQ0D0w=,tag:khyZkFvePuSKZptlTte+gQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSnlkMjRwdHNkbGZqb3dQ
            aE8vWGg2WlV4bkJBbytpYjI3dGtlZEowdGtjClhJMCtqMGtMb1ozT2J6OFNvNit4
            V09NOUhiek5YVExQeUxFSExWL0wvVzQKLS0tIFNCUzBBczlYMS9ia3B6bTNKdTBn
            RzY5TnBDcHZTa1Vya3RZbmNHUWkzWGcKorMG471MuKux3CCoeAR6O9zB/v0aKP2B
            oxf79KMAz0ex+qE7HsfOlNWZa77ENYekkQlA4sObt5DCAjjAfHNg/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T09:17:44Z"
    mac: ENC[AES256_GCM,data:8hw6UtOkoDkDfFSRf3QcOTwfPzpUXXWx7FyfMBLhi9JF7nQMOULKknnA2Gct4EtJ9o6H/TABEcedQ+cSJprAUlbPYCdhTNTnefrDtn8KVW6HjTYJ4zdbHUCJUQRrCNIgh2/awb2eJVpcNlqLZaCXV1fYItybfa/eA0dfRrMNpKI=,iv:qtZXv3iMlX59j0Hg2PHzOaFxmbzE+MXzHsnpW1DfVdg=,tag:uj9Sy2txBATQlR8ADbC2dQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
