apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Uvtr2BJgwQkwaDihr7uvqmIK8qV0DhikGYFt903f4Grs9eNWWwChTUJ4eMsbfr4hyn6I3jdHwKYMq2vw2We5HsQbh6STrqMRV0z45zkZaYF72ac6DYjPQ2jQSIwV2hizPJEOyHY46F/STXzdHGO2ZTw/W50fNqzAOro8MMtH/1b+rL+74NoUpmpc9kwFsUqi2MBBU+tU6IKf32XT5nDDvX7EVKYo++6EVNEHdVUCOu4v5lY5p6Vj6I4Xz8bUSPhtZsirDU0gY5eK5WyJ0UHAOx51CvUUyfV9VXsBbwQfMH2yUOP7uFj/gzns6Fiuzyrxbvh39DVaqtfGfZbDzClfoaqMCclimmz4w07wt24erOpK1fNzZeojmS2fNSOHtpp1,iv:hy5u4rD+npaohuufqbNdiQ6rKR2MH1rzy1tnaEM9vPE=,tag:437PO+CW3Npqby5bAMXPVg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Qmda5Qewl5euHxJhxOlZGZbLtKOiul6t4kFUbTAWgCRmZcgHBzuVQImIVQ3le/0FMBWs+uowJpMyS2uHc4quzxrNXSPPS5VjA+TvXC5d9Idaejcz611EynrgrMCuROjV3LZVNJ6hITWvdJoF9nrdyP4OiyayLAbaT9NmwjrYQrm8dW4+/FHLvxPZS0MS+XjvXvaaA1Bdk/j2XZibEJ2kW6jnEJo2ZMjxsCy8VBqmtADttCUHH0y7JGt9aV6TzIRT1Y34Vcb7kKURY/J/Ew==,iv:o/mtc/AKMpBvje4f77oKYJPqwHT6fIlsSWc7SC/dW1Q=,tag:UHF0d1EEABER7gewIvv9hQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:d4hgtqGNixxjTYH4Z33AOFd0pFNCj0InfcsPCyCEFpd/TegX2ts2mcXDMNhvvshu9gqbGXvYp76oHb+EygviczA9+TVU9hkd5t1DPSsFNFZG1h2pd2DYlb4kW+IMMzzkYWsYYLWHr6Fzy3u88EdZIXJF2Vl1Fu0RdlVA2iNb70VD1SQwDzzzDTPsr6c6USky59rTLrezFM+9jKaMfvWlEymhBCn8PVDAwdfs,iv:9CuAHqholpPCvrB1AfIBbmboS2Xbj07V935VwqAIORc=,tag:1eqvIcv3ee9QhI7DqLdkmA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcDR6R3ROazZVWTc2SWs4
            RXJyZXdrQ2srUnJWTldqZzByYmtEbDltdUgwCm00b0VGaEcrbWp6STVPMlluOWZ0
            MlZiVktMcENaK0xHMWtLMjVCNThkTUkKLS0tIFNYRVJwbmQwdzRZeTRXK0JZaVJK
            OWpJcFY5RDJ5RzlETmR0L3J6YnNucmMK2XxfjwBYoacuaIU+woaSs5aCf1nGparT
            zhA06oG5aN/QRab/b3mpBwppxiIHWRvhDqWEkaJgVVjBtqG6AUOVCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:35:30Z"
    mac: ENC[AES256_GCM,data:yjBFVSIDsIfKoP2prIVGTuc9o+Z/nIxCmk6dGq4t+hACtlV7t0nN0zp61VaYkx1wU/cpkNu57agAuablYYhCeirlqAIyZv3lbVwDoj0v9GP6Wo61QPnAz3NxW1j10B5UlRLfsisJAiDwZkZdrhdvvD171kCfrwnnVu0k4zmrhKY=,iv:CGUy/Z/0tJQ1E0l0UWZGfrfrQoEnE6IWChaFpIIGfYA=,tag:tUY6GlMAANDXi7IhTWDhrw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
