apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HFXzamzijd+npbUi5hnapbkm7IAOsp48F3YLW7ZpAa5LL6oqndmgreNDJGOglkNxs0iEh7AMQegNsG+Rq0VFeIiEOuoIz5yL9ENk4mQWGknDfPOvWIiiA3o3nv2aq9S0TrO+yLexYYpyO4iYCELWrxO3B0/PhFgiduXPkDQL6LFlQAoX+HJnfudfCOF3leVETK5mwYuSKPgySnNW3yCX3f1+NmOYMOqgomzXkOMxBu+SbwALDW3FiYXTSlKSwpKxh8HmF6+qM6NJhGDBrlERASyz+5QAxjaUZoBDe3UwEmPgeTK+pi2OokrD71D/Rb9a+jM9mj/9pVj0FjKutFyfgojaI1D6GVUXYQsxGwrrdlLriAoHWK6wCTRrn9/sQYOx,iv:hx9CTjHd+YVgUGfzJ13YB7BZ1/7xferjpU98WoFDvcc=,tag:84QwGUtkLQEbFCi4dqRy9A==,type:str]
    identity.pub: ENC[AES256_GCM,data:5n9w1e+NGEZZz2qT7ETaj3nfaQ0L1qTqnxv0hMU+sRDtOl8jYic0xvdK/WChT7qtU2rEY5//Z6KgFb+5hMf8c5Ajme5SCIrRnkKDIqh8w8ZsSsoDERi4cJctk/GLNo2hAGcwmeUKlWtaV3/6G3WN/97Sprw1UxttfRfNrM+JNiU7Gcd82ZKCDqp6i83FvxrvlLccn2QAlYtN0aDVp+K0Hm1/Gewsg132vW4XT9m12Jn2Rt0cdogCvh9OIh68aud/MUFM66BHXNf5r/f5sw==,iv:VpBrZ2pIisAhQJVkmImhClf7ul1C4JZLod0OahAPf98=,tag:fSO14IAtSOM1z6Abb+gxqg==,type:str]
    known_hosts: ENC[AES256_GCM,data:6hhLtE3iDA2k2tYmC2qgrEBDKoPAMcdF6+G1kfD7ATVfwC6MtoICpz8dpDVZ//scIz3jBj+05iPn6oXewdGio3DrEAOpq3C3wnT09MOZ3cYYYCaEthcVT8IYEfQWpPbJwUCv3pYA84DV3bE3nFOOvOATIdSYLXA0a4K7+UU8w/qtWl//XMBFK1/KtxKFrAfz3SoW6vbgYyzSdUJtn17BJFBGOLyY8YaG8l+R,iv:HrCxDxsaTycXhC/ZiyyvHa/WohNbPX5wtc1jz/E6x70=,tag:WGmkSQ1aJCDBM9RS0tPXPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eEZ2UEozMFpWSjZOenFn
            K3JHZmZON2FUcDY2c0ZTZ1lSTXk0MXdmRGs0CjlQcEdDR3NtakE4NTJlS0oyVnls
            NHlrV2pFaG5rTWIvTGd4aVlHVDlVTzgKLS0tIGJJc2pHbUZoczRaWTFmUHJzdjhm
            VmdqcGZENVQxWnlPbUszbzFDcmNWK28KGIj9KQ5P6uQu+bEbOCr1eUWOMwgptLyz
            UnSTwBGtnOT25JAaQ0WKoO1L5L4WpaYGv/SCtOHu6PRebqpArHd4KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T19:10:38Z"
    mac: ENC[AES256_GCM,data:ggDQppX/EqnZOv+Awa4chMuG527W92yvutWKKBuE/PcVnL0bdP5WdBQo7G9rhpvvTI8MFu21NcFdj3iZQDTQQLSD5MOkQ6hNPujql6qyMprLJQB5ylpwaOBsCAwPaT38gfgdYee5Aesd+pDRzm86rAnrpYyjJsEs75H14mAsS6Y=,iv:D4Tq65ETmwvgBnuIIjq1hBhUpewtHCYpQvSkrAUZBBM=,tag:yUIyYqehi9yPzdqGrVCMUw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
