apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1tkNlDACqCdl8zzyMQursqsy6JI7icO3Hut61I08n8BxPyo5WWrJ77DiM+Q5hEXIuP+SVz3WcWhWMuMs8fT5ltIA45bDDSkPuOLT82z/LugywtfZAY3wEwdaxAIQwNxtLJ7/IfJ6/yDlPP4YC5JFXk6lMORlPeXgp2FqSAPcjYgdGsKVjT9noJ63Dn7FZtZ4VW9fkKw6tQx3JyrtSMMeA4VsSqL+ohOv09lmisGgxMFKBaBCRovvWCvWZynKd7RRv/O840xRpW/61gmMHFX51BqH3Wgt+ooOmEdgCxk3ozwEEVgQ/vllywzqhJs47XntbjxSjndwb1nWy/7C+f2bJyIvG4tFQ1Szh/aF2+NR3s91YMl91ixhem3gkhn97cnN,iv:OP4cpQB7xbEnIIRZZ4GiQBXYHfkK+TrzkfqPfgSZyxg=,tag:x6fX6EMqFc7SrKLakjrjbw==,type:str]
    identity.pub: ENC[AES256_GCM,data:zl6h7e9GDlW/bPg92QlYirgE376vSz55Yrs5wAfzx5asVtCZtwADlRrizByTqFyJZxAs067z2BPLPGtPNsXOkUL4AQOhpcGVl6+peyh+BcqW62ggLp29fEIDjymFF64u0y580V3fItWY/IWlRPUK0TK+g2aOdkn2WuZIt46OY/6sNnyiLrwlgBBgLmeV2laf1rxCS2UXpPru+FLecIC5/wH0oDIfYy+VIDsQ0VRv4T4VaH/2c84GcTzcw2kBRRWD7BOq8xKRL9CvAIXqXw==,iv:V3en27m5gH0evXWv31OxcWDfbWIvZb/5V1oTC0mRCHI=,tag:ARWnjL6jLMqudRsY4FHhww==,type:str]
    known_hosts: ENC[AES256_GCM,data:N+Dva7xOtycFvjpR3IEiXRC9GgpLRCB46bpiTj+UJhzBwDEdQ28BDppiHFa9yk+CYA67cY6mgmE9lLUpKtADq8R1zjq47Tw+a5VMMqsFXkPDDeMLC/brpkShZpqK25Sb8xLw43GnNuux/ElY+0C0s1vSO69txHeTcyulasQuGkY7+OhLq80KNTMwbx1l43lbVaSYm7FqCln7yFWKt8eZNQVi02s8znfr1U0c,iv:HvO8iMPPP1v+2HrNkKvXipVM0YhwCLm3e1jCxqCsbPE=,tag:DT0W97AEp3QOph+6ODxX0g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSWR3NWdWSm1rS1ExcHVE
            SngwdExLZit6Y3VrRWFhQjlkZjZ5eDBWaFRrCmxsK283Yk9LR1ljVE52ZUdiQUQ2
            ZHdRRExLVmo1c0YrR29NVTVKand0eVkKLS0tIDFSdTlGaUJxQjY3QXpjZ3lGMjVw
            MGE5SGpseUl5RzhvelZNRkwxZGtzOG8KjgD0SLfF/FyNbTa616rjvTrGnZRvSrB5
            GVFH/9oqs1f+5qh8nATJhF/SbiMLoeMWrdV1WUwDus9x2xzFdo/tWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T22:18:30Z"
    mac: ENC[AES256_GCM,data:x8Ua4DKKLYUiHDJdtPt5/3rCe5uzNrz0WX+6h1McINLLkOEIPkgOU2/dVWI5UZyynMJ+GRCHLcXhW7mYCWw/uY+cUdIUzAC8WL0cUMjUC2oJJALRvtfGPdO2MBDDLgGCD47a0CeBRZcPvzjrrlJfBSPb3rsfyDDqSB5wfpLyPus=,iv:NrLnJZye1VvxL8oem1QInSO+bmg1+Hgyepwz8RzY604=,tag:neSEWslZ7APlt4HFvXEPJw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
