apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8vzfv4rKoaqh4MGbUJsmCneufdNqhhrEPs+i0TlH34XAhUO44hiKetqL9VpwSL/yDZJbNFy0oWiWQi1AvQwIN9A9rjY3BqoA5oluw2nKEEL5lpmdgV+ZzeNtF0gwB+Y6+sqkzmr9Yez3VDY1N3yLR5S7AHpHbVw74DdK6H443Oukwd/2pW5Z4mOvUO5+8bQjZ6+0VBz6XvBGqeRCdobhsEcLHStVLFA5SsMOg/IL5UVxIOvCruqjtR1f9P7LialI1FMOgu4GZTJAoek43VCLXudpqtpGRUv6tHKe92gASwUeRQFiBwRcfTnQ4aI4Nr0eBOYad4N0wmo/q8VClgYw7qIM0eYJr+lsNFe6hhc9CRElP3qkxd8HIbxoU/RN6w7W,iv:qAxZp5lU3GnwkO1yXEdSa769LIQx7iiHwJ1iYTWsuaU=,tag:ADhlA36Oacs58RM+q/NjYg==,type:str]
    identity.pub: ENC[AES256_GCM,data:eiiQ5qOn7WoQTS/Q4oJ52lZQp4hlcnYGpEhsahMc6809RyQxBZW4iVrxZSjSpkFdriThWEzSm3rnKig6QTbRadfPxyJF4pbfiYXUAv5KY4pf9mAFj5CCUO126TeaWYJn1zycR5q7CyWID0kD2NkKy8ggvOJhTtsaBlVHBm66zl/qDfgEAMBqMzNcvDuQ8THCLtSAcHw4/PS45MR8qcaFYX9Q/Tn5KOII/0MagoGkfuCKh2Hol+/xNEe+kiG62lqLBXvdN1rL6fQkwNW/vg==,iv:tEPLAuELl8D/J3WrxaEAk2vKHKnxP+a3nFoq3uX2z64=,tag:llUox1RxJe/BmCSIqko3Gg==,type:str]
    known_hosts: ENC[AES256_GCM,data:RVHtQc3POTu7orM/E/mq1V4molWOH4KXY4LacTznwAgYim1g1xz5OayAcq+MfmD/kcqvAL0cY1imHf31mnjO2HLTINw9ClYnpGz/M8o+06UDrdDbjTQFK7LWscjm0LBTJj9rPplGfNQXnRT+l5mBiOhmKvjxmbjxQT0dBelBMjOQU7Bn5ujsp3ykAtBZH11iICS+0o47qcY0XBuxhQhtgUucMWjLd/VccESk,iv:JilqsgreYouj0VAOtQyL6+iveopLVs3kjuPzBfHtRNM=,tag:62awdRaAikKLXWxaFw45lQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQVJ4enlRMTVlQjgxcEo5
            WFNHTjFyZWl3elhRbkF1d285RGY0MzJrYmlJCmN3cE5YQzcxY1JyM2JPZTlqWjFF
            RUo1YUNYMTBPUS9TOXZLN1dpcGJPQWsKLS0tIDk5dEVOQU9adFFBcUxsdGFuL1JL
            dWhoVUY5VkxXZTBlR0RzdmtxeGI4SlEKl+3jwzRM54DuNBmz4DvT2njVPEisTp/v
            XY61Yw8eOBHxO6Edi+WuCy8ML5SfUoWhEmDJBm8sipkDftVUkf3POg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T07:30:50Z"
    mac: ENC[AES256_GCM,data:lIFOUuchFzjffckEz2Izw4jppRpGNlDVgaavz6aVStxo8jtVZuJH06isc80Lb8Z9HjkxXZGLO9ZjcRE6lTUYFbOe7Q1X7aPnHuWiIBWRNSbBRYmirG5kJgm5yNnKTFNTQLpVzgQ0jUGpUMbceXfAyQ3ItGzN/e4/3HnvaUB67TY=,iv:3lWo0Ze/pSMvS4iiGF6+LBTmhyFdi9H607fDRih01Dc=,tag:kGkfgW0LTWtS1qsZs+0SSg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
