apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:4Qe0XTqXWnH4RnQA8ngyt6eUDPVOPsdSiorUCMuEIfHCMn5jcjwT2wmHWF7vbz4qbz+oD0Z0aqF906ZCtY7+SNq8euROYb8ziui3PILBBaBgaynbZgnLzAhvshFCyFsTvvoprPBrbFdCDOSN86Fcm+Cka+nURtv8tQ==,iv:gHIkfp0klYRBr4QuoNb8TpfvcJBFg7reXafIfiw6R7o=,tag:6aRxVoi6wRF8UEWC9Do1vQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa1BQWU1mbGNCVlB0UGt0
            bGVwVG01NnRSWEhFeTY5bmRvdk9NNzJZWjJjClFzOEVZdVk2S01zc3puc09yM2hj
            aHNYUDdIdkFGcFJQaU9wSEdDVmhWeUkKLS0tIENDK3dJVEY0VEVMQVhxVWxnVklR
            TC9YZTFNNjdZZU1qTEV5am0xWHRycWcK8kE6yxu147ooRPGBcAmhrxqq9mZMZ27D
            UKkUeTR7pSJkQBLZHtIj9g1qdn8SpU0Z6DUtWo3iB1Ea7Qrt9ARKJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T20:43:15Z"
    mac: ENC[AES256_GCM,data:Uw0wDPYDgwEJHo6AobqSMlk7YSBs01CamR8shsfa50G3pwQg3ahLF43VdacEO3x+LzGsO3aUwPaRsdGts0H3IXwnBIrMtclP9SY9Lkp4J3cwnsBsUQhqJ8lXvPSi5tnQJSBhkLx12UTHaj48iyCkNp+hPHfZt1mWnTB8Lx+4EGg=,iv:28VHtre7PLqASQMZVGlKvSVF7wLwxWJMCKW0Y+ITjmc=,tag:aaizH/g4uBMaToaBGjbTWA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
