apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:pXdYUm6/7AuKvPtDkDi18zXkHw7bF2XZBsnunDesiyt6DRuYg+m2qc+2qeSqlB78aP71/Gn4/r3G83ngwof8Wvz4Kz3DLDH9ydD4ej/Ql5tE7Y85WNyUVsD+IB9VVMkQs6TdOvPuv8nxtysGaUQLWlOWs86tRaZRKA==,iv:UE4G6z32nl/QtzCJygQzGySBZt+BXyzVdPASICCnZhk=,tag:rgbda8sCn9UI98U9VNKcqQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SEVUTjRaVmtPK2IxWU91
            cDhweDVWZTRKTzlaYkNFWFd2b1A5bmUwdHprCnpqV3MyTXhWQnlyRG1UT0wxY2VV
            WDQ3YzV0V2JmRUZocHN4SlBvSWJ6WE0KLS0tIFZVWXZFMWFweXI0Y05IRGRYVTlO
            dnNNVGxCUFVSSGlJV3RMcjAyOWVMV2sKjw5pM+fHAnathU3o3sibRN/M/oTHql7S
            4Zi95ToBPPCm8KkokgVbh7kHtKFepRMu7mSzMCZulnwHQyzesbSuJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T19:21:44Z"
    mac: ENC[AES256_GCM,data:4XODL4m+azMeS44E2E3HxWfL8p4rN3dU8wnBRiLJp/3U6hvZyYs0QYe1GvkNkynqjAPaZKhfqqoJiV0Qumr/dEtUFgEFNJaExD8W+3QfUiDdZzk4XyrHOddQhln0Exvh9iot0X7fCodWj/4iAoK2tql/hsmxmYpRgwzmTLCaO/o=,iv:NgdLNr1ha85YKAAfhIqvAzZPnewfgeVpkLgUbmeZ+To=,tag:HU0wMdn+R2OrBymgRX5lGQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
