apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:EGJMmCBECaUMpmmrFMXb4mxQyIl+sS1CixWMRtKQWaYTzm1c6R/buuQkgOCGUxwX3d7SrSW3eQw8WUoo8mrCd5syxo55FALUw7WWVBXq14/143JSuDLmQFftUjg0mpB8nbJBdlvuQkTXjHrn/yEpreHOLo/UDZmSfg==,iv:yzSDIkJUPmTT6f0yHNoKfnnt2ZF0mDOcnJHWKp1QoHg=,tag:XJffN2PwKCvkWcQCVHz7og==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWWF3ZTJDeUc1Q0dTMEJq
            YllWVnh6cmRka2ZoVTh6QzRZYTZ2cVV1L1MwClZ6eE0rbzJDaFJMS1FZYnhRUkxU
            SSt4QU0wRTBhaGNvenMvYWJEWG0zRkUKLS0tIFFOZFcyd3VWcTBPTzdibGNTSUFa
            Z1ZkOXpFZVoyNUhQWGN2M2xCdWF2OFEKgXSRDtTRvlcnCLwDh1k3PdSizKUqIwnS
            Z4SovvRCKlwO1AdINRSsguivCxc6tIRwOYok6JLa3x6bXlxHtj8t+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T21:10:58Z"
    mac: ENC[AES256_GCM,data:eYjM+FMQ/eBffZRSWc8CFmDYH/hYykIAznxYP3J1o970Sq4t12v5LSWaR+1B+dgrBwe6VgBIUl22KqoDlj14WwLbin32AVUepohRyA8KimbwVvk8SlcYMndf3ttmd7+09L6D8/sz7ydzdgadUsSrr3gNl+gdyXVq6tRnQuLAzVQ=,iv:0gd1I+FWOB8dihrI9l5Jqdpg5azHG8cjTHg+2iO26kM=,tag:t85hizZHY7xjIsRajsNy+w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
