apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:p/tGdhu9e0JQqMAP88TkzUipnWuT+h2UzyBPRxKHbkQ8na1m/85XireoqCl09Uq9O2qAvIEFOMJomSq1uWEUt1JLlRqNthFv4W3vGaCEn5hhZT0C/NsSyYhQtrBRBEOKitLuW6uX0/+lFDbBIyRbei062teX0wCVAQ==,iv:9u/a7/ycuUL4gjrG96tYaNvwv/f8+vDHTye/55n8F78=,tag:Pv591LlE41qsVMh4LMlIcQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZXErRzVaQmEySFN6bmJR
            cVBTeXpyTFZsbjhTM05LZHF0MFh1aWl2TjBvCjl5T1BkRGV4TmUyMUR0Q1pIVDk0
            OC90Ynl3LzM3dEdYcDV6em1WTkk5ajAKLS0tIEtiMFBPd0xpWDRQQVBuTjcvQXBs
            TkZFOWZJcy9sZGd4NnZ6V3Y3L2tPeTQKEmmjaIPr/D2ftafdutXrcMlwImQGopru
            sBA9rAQei5zodr9/x9Wp+jNwEVMijMb2glOwRuUAuuGOkC0icF+aZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T06:58:35Z"
    mac: ENC[AES256_GCM,data:wXTx6mqSI7mu1irQPHnCq5FVy4f+93eGki/M2Vqw844EK2fVWKUtJ/QfgXFW//9GvWN4k+s3ua57MeoIEV38D/kq55bZ4Xfh49O8ApPaee0SMqcWNLbnk4KfdKiBsTpF2GAFZAEc4ozsRDKA18BWybVhF+gnbAvEwjeNtGny3ps=,iv:Ia/zbqWyLv+o3IC/k3CH8uhPy7xETISZJ2cecdC+QH4=,tag:N5r8rPU/vDily3hMIEpgvw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
