apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:YYvjPXC33/nM4cp1AItWhNQDLakEDgwa8IhXNCw2Ax4MsCrmIPxjVELnS698loof5fIwWfv2GMCtpbUa/t/3SD9eBtvQjwJ/O+A41lkrIRy4DQ2eugbTJMDg/BwPxLnUs1z6OHuVpQFu03ZUaonyXMEcbJx8VingsA==,iv:65Ah5tVAYgSvtlz1G4xEvnGlN/Kocyl6rV/Q768EcGA=,tag:ovx7kKw5h0ta/2UanaEEbQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMm93RWhvUEhhQ3Q0eWlI
            czRSZVV5czV3Y0V0RUM3dm5ySG5tTFVaa0dFCitwTkYwVFFqVDFidEtQUlljcG9L
            LzVobnpFdDVPQ0NPeVRzKzFmZXRKZFkKLS0tICtrZUF0d09JUUhlenVGNjQ2cFc5
            MXErZDBGSmUvK0xSNSsvbXgybUcvcDQK4hltr49MSyqfycPP6k8aUBUOsOMxCz+0
            56fk7tuAiuyhyl3WttykUn1MEgD0BtJHjoerQ5B7FBs28nwHdGjbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T20:47:31Z"
    mac: ENC[AES256_GCM,data:jgL7jaQzGhlcDHXmBR/T91s3OJe0bU9+GRqTmmVHatGdJT0oFq5mpFwhsSpkHhIYG56j5loxIRymv72jl/LgMmQOOyL3DaGjIDQXkKeq60Gn+gQBcuqIZBiSVIxKyktapUpO2FezTX5/SQrVYnuIHhpMUFYixnPvmn8shcpRLmw=,iv:mYDUFkVthMqG8c3m5dNgFkc11OnJlZQ8ZHiNxCxjHbc=,tag:UMKWDOymJNgWEIzJPri9cA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
