apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:UkAf4sxuOOpuedpVcXfI+PphLhmJA4GwLbqzs/aua9AxnsH6oWiOokI4uw8cucox8i71lI+HvC7JWNAe0mRa+is6DNpz24LHNfabSaItosovDFtPdJRx8rk8WKjXVudJhEElm4F+QjqjIt1bn5xM9cLkcvTMxG7LNg==,iv:moFRbamtozES3qAjgv1Q/j9DQ5tTWkNjTlLQjvwQOvc=,tag:ZCip/fPYlHNwI6ivh/pS7g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcjA0ejJWZTRHVnFjNkxC
            MzlKZXRBT0lWNkh5SlJDMVNUbmtYZ0J1cERzCjhVN2ZYZFVZditNTStIaWFwbFlt
            MVZRK1NUUTlMZ1JiU1UybFdPZWVGbXMKLS0tIFdES045ZkoyMDI4eldRb2VxUm9X
            bHU4NktzUjZSTXRNL2JQQ0tLbTBzcW8KeZzNhkMqUszEecRE0k2IPZgOoXOMQ0eL
            iSkcAZH06+cxaLVXXKkFdHs+gG/U+6xRSwBK31sCKfagLkngoqGndA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T07:30:50Z"
    mac: ENC[AES256_GCM,data:K1tiRHnojzGwbKEpRhgX34fhkjAAc7zPu7zS4/bBs9a6UW5tgomcUPga30oQMqotntw+ansVQOtNVJo223c2j2y2n1sAo4eRsa1Md0MXcOtc6PgeX3F4oomujOFQk30zc8NajEyBMq87L6NVKqKN3Rtu1o/JVwKHcXmy6vrOHcc=,iv:4n3uUBUIoM8GyZwXSToxXlWgKn0EIixpSHRla+l9c00=,tag:tObRbrkoD7d+pPmZXl8IgA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
