apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:B4YPv/XxVliZd6Ribmx1qb68CfJI1OabIeT14APpO72s3rZGBwNuUCMZElgPxpS5Zq6QnIntLmOb/+0ogr7NCN6vjb44kxaXYa99hqb/CFYjXSVlZpSSCVFoQ76QBfBx++WYstnIX7UOfN22FJyZv2XInpbaRClTww==,iv:3JMMkkrvFiP2F3WwiAN4SQXx6KuAiUdcsEEb4P3xdTE=,tag:DBMcYsU3haAsC3dXfTUBpA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOHFtU2crQnBnYkVWVGc2
            K0dJYTFHUlFCd3Ara0FQQ0RRUjlTRUNJRFZ3CklqSTQ3a3FIb243a0NZako1MzFC
            aUhBMHFnUi9MSU9ERHRDQkh3VkZOcUUKLS0tIHZQRmt0Y0Q1N2NyWDVnUGhVQmdH
            bkFqZWpCQ1UzSUlTM05KYUs1TzUwbTgKL4CLV7yfE0K0b3CTWMTDeuxrK+ppWQwu
            Wa5KuWR6AkFqtzZsfgX2lytCCxpF87VpZHff+JfUXuN+3UPozXWY+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T18:21:39Z"
    mac: ENC[AES256_GCM,data:H+giVrjJhZHFymgD9+zrmg9Wh52CZA7hkYOaL96UJ2S8qaj/XDxoR+fQ/2ykUJa00OeWyuK0YywHFIo1V5aE11D5ftkNKJks0k/y/SfevniqtQc/OMUrFdjSsw+gsoPrlFG2NTpe3gQRgTvUO5pGJwa+0AGdomFBJrZhTNaKvAM=,iv:ClZqQuNW+8ONKCORfW8dEH4xDlfHQ0D59KwSmxDp+6g=,tag:RuvzY9Nhh0cN5mKX4YZZKA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
