apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:ujdkggFu5VGjCzFKNRS873sWo+xA7kmJSN5/iHP0YNZrPdYdy4tkJNHRAp4FPpI4028Ve0orentug83j5AAqcr7giL2FMxXQIQd62rZDhp/8iA/gycYN6mIKxYs+3zkF+si0JJy1Oi7Q8ruJRhb6fJq+95suE6zwOw==,iv:kGfyniLIcDZCJysQ7GWJVYCX3Pdyeh4xZT4CnKswJHw=,tag:Y1u8Eq+dXgoI8Pin1o3Xsg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SXd5dE96Vll0Zlk3Rmoz
            Q2tObjJsT0MyVnEvb3FZSmJQaGVHc2ZudGpVClhNbUhMZ3lxMTRsb0xGZjViWUd2
            SDhZUkhqM1pYNWxlTU9GUnR1Sk9HYXMKLS0tIG5IdFRyWWg1OGJuaWRBNVBZZjBV
            emFaWi9IbVdWb09vRlg2WnZyUytGY3cK73ywR3AOmVk/i7D5OQGQHTmZpgNsnDU0
            K5QwNRjw4OWhOnPOQpbILgx1glxQKNyNhT4cACn8HLCyP4EI547mrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T07:43:41Z"
    mac: ENC[AES256_GCM,data:f8x/9Xz82K8Oavxz6B3P5cJsHLb5O8bVyTVR7IFojFxLCxTX6i5LTwbhpsfHFDSO5QTY8x+PAwXiin7BMk9xgx6vjLit7gX/eA5HfY8xvQgKUNnEGNmfQdlrczCbW3MJJxqP6VQ/HAy0yukeEqIVgKlpay5vVxyGqVq8/3KP+ss=,iv:h9LKdewtNb3uB9Mk+i6wBLYpq1GYfJcXV0uIKhoC/lw=,tag:LUCUeXM7qYNqvF5FcIp62A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
