apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:Dr5HvTeHwBN0ZYzxFmzu5wZSfdXADnwqWUBcgTkLXkYrRv/o1jpZNXWxrhFyvebNkyvDm5FQDZkrfh+WwyDyT1MTzgd9W5CBtghD6mslulxhsQvAi5v3uqJLQBF1qF0KBaOeRONwqNI1fxdO0kdBVvRFYkZAvE5aPw==,iv:I+GNokU81dLsX7T9fY6gS1RsXh2BB3StelRp2M++a0k=,tag:q7RRF86Ec9SHCn15xPMbMw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmR0JyL3FidjZYSlJuNDNF
            M2VzSmZhWmRWUFA0OGh1Z3kyeG93eUFrT3lVClRhTG5SeTNiWFBpUzR3VVlDNHlm
            RFYreE84RVQ5WVlZTTcvbGNmRUQzZlkKLS0tIFczeVhMTWVLYTFDREdTbDEvUFZN
            OFJad2hCS0Z3S3FkaU5uUkVBL2J5OWMKSZ7+MoKy8mUp8D8kFCdKOlukCgD3sxmY
            dKTxewugi5AWyYTxOXKoUkeVAo1//J13lTMIei1NO1BfeFvj1UTacQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T18:28:25Z"
    mac: ENC[AES256_GCM,data:EUPWyMubafu+Q6NxvkWL1Xyx5pVl6CDB0mYet8xrUACMonjdLbrokXUlaWezRhNt6h+xI/xBjyiTAtGH05ot3sb3G0TEzljoUWB2weMkGShtmk8Vz4Pb3Fo/nxl28thbYxuvbvPBKpt7aFscsJoHPbIc3ASH6K870bkR9EVscdE=,iv:/1tKNs2sq6kmQpduniUg5gQaMkI9sQc54xP0jAWvaSQ=,tag:mzxze1Lte4DkYMgVMStqUw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
