apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:JXhbc1LLj6gFUp2endXsyJ2HHeLp3ODNjSPRCFCb/FkrY8u69kSkuOnOnXHXcJE0IxDc4G3xN5i7sGPsxlpCmy7GPu1pAe62sMCv77oBS3C5P2dQpgUbxGyL+yY2K3sVQofx8Uxm7ZfiR6qvclWW2MMePX6t6cIyVg==,iv:z21FCt12HQEsJIXk2ChOzg6BLRtxAzCahDWq+U8o/k4=,tag:38iRQR/nzSCF8KECpusgWQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q3Jna2dGdDNvWW8wUHZy
            QTQwVUNPSnVjWHhRM0JkdFdQMU9GcjZBVDA4Cjlxdzh6VDdTSXdYUUtFNlVyMWVH
            L2lmdmZEamkvY0IzSDNrY28rSHA3VWcKLS0tIGY2NmxkQmY4MFYxU0xtYVpzRDZL
            SUR4dERDUGEvWXpINU9XSWN0VWRYN1UKSkmT4tQ87h8eFXKCAydBONsy+okQVNpy
            dgUP8cc4ThVeYqd+ZDCmycJjr/vcIx1NrJA8jytWJObVyU5UQkMtlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T05:36:23Z"
    mac: ENC[AES256_GCM,data:LuBrJmrcQAhe0ua7exV2KoOjwYwQKFzabIZOM3Hpby3hWwSOszO0ATpgR4+WWecxBMMElIshrywzYB/0O3p8O4P5gmFwPgwFTkIKRX535sDZuH+09vk3cove8iHzXGGHT1xRD2nqCwYmvTeIKmqPtc0BJb5mC8dtTlRWGFSdJ6A=,iv:CyFe53aWuj7LiSBdT4cGQZnKZW1IZsPwSmOv4YUC4pY=,tag:BeM1HOR/RLyJBA6umrWt3Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
