apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:+yMqosAXcEc9RpMQ4ieiSw0bhj8n6ihumG5JccD1EOouSdSjVoNQkL20cMugwp3rQftR/QKzmcMu3jiwdlWeLfh8lWM0TEUfvGritnhV0fkCw9tlwzqlH6geidQq9eBR+ZCvgOlmWGVHD1kYKuVeXMEJaExzhqTd8Q==,iv:cKM9XuX0VPMXFYrFf4XCLCecWV99am82vro1kdEcbVc=,tag:7EyNw9rLmxzQg0PemkaAqQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWFBtL3FCR3RDMnZ1Tmxw
            S2VEVmJLVWY0ZHJtMG9neCtuTEsyOXp2WGdFCjZ2NVY2L1pERG1ZVU9VeVJPTFpS
            bmhyc21WNEdPL1ZNdmlxR0xLV1E4a1UKLS0tIEN3SnEyOE5idndPYmtsWjR0eEhz
            NVlSMk9mL1dXRE1sQlVlYlRhUVlaT3cKMq+gj78k7ViPAGmC3WrsMfVBb0OUezn+
            dlu9f4vgC0dMhVTWIi8Jy63OXvtYiHDwp/X32zEmkuPvGE7WhMye8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:35:30Z"
    mac: ENC[AES256_GCM,data:/eDnEhdnGMfmMXXIHsT0QHi+5KMndljT93Y+VXPdR0mnc/aXMHQVc6QKmSnv0Q2C8HAzW1tgrYiDv8gTyeuAmqCmkAsrGzt8yi+NuXFV67wbgTmq7GbnP+kQvgBVFNYr2xOBSNxm7nErgoP4nCne8SNJPWrX6DfNqwVshlP69EY=,iv:SL4N98PlQ2dAQ1VNMd6v/RFXPk4MIURQLKjKiD9R+0g=,tag:ij/VN1/YG8kO0zUfFyA/mA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
