apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:CSlPDHoG0C1YxyYe7QTeWGuGxmK5EKcDoFTvJVGN9bJSCMxv39o1XAX0HUD31jeuCTnwm0LlXapUJuanH2NJXJQlaXMJes7JaUDkmHpnZRlP2oi1+a7/PZran8qysdlDY8ihmDkbCl4UpXtIbDa4uzJqMyLCXpCrLg==,iv:B8euIqXUuCHTrvu7+2atEqEoJco9pl1KmkYUEt/JsyU=,tag:QijQKGsVp92iUJ3KnZJx2Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbTgrZnRSTnNqKzRsZUpK
            eXYzU3VrVWlFVmJLS2xhK1VlcGpBRUkwMGlvCjBFTUo0Ym82d1JINWRXUENhT1ZV
            bDZuTzVXbEQ2dDljRm1XYUs2WHNZU0UKLS0tIElXR2dmcGkwblh2YnNsYnhCTmhH
            cmpuVjExcGdWQUtuUVVzOCtobmc1T0UKdGvSTtWa2JiFVCUBqM/IYW1TCljU5oNK
            pjeOJ5eg1HqZS3QRuvzlmhI2+SxgAyxMrUJV0cpvAmqK847JCa+hXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T21:54:07Z"
    mac: ENC[AES256_GCM,data:5ONcnwElvA2xPueTF9/CDeJFAPkaA3mLXgew8JOFtKc/ZLvItLyQQGeqy49dJSjBJnBJ4lpn1be3SFr2Jvqt56htxDaaxcTgx2Nvu0tLJ75LoyyOafAVht4ms8m3mAKijhfg02A/5RYz9zROG2Gt83cLzm9aQukxrZ9sTTpSxr4=,iv:WGPSl1BMMN82vPYvew/LJkIOPR9hX9Pz3p1JKogqcOo=,tag:sozyech9+6fgi8W62OqQwg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
