apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:TTcLkh8ypt3WD5msJ7tvHHZu8oZs0+78LRTSbykDyUBpayatfv0/qgu82o4ucqpCKw802fvsaD6+ytkvAZZ0U4LRYe1pT3oI4x9t+bWghZy+xMuG6EymUwhA+GicPLZwZ7ko+qp33C31Z1dCFMk4xMrRberZeHXD+g==,iv:nZ29mt7iQCwnbRD86CX8cU/Ux0nMKAyAS95rJla7RGo=,tag:5qDDXaAWyyOsEowptFVV+A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbGcxK0t6VGlsdUxWUlhQ
            RXFBUXlIWm5udVBpQ0x4K1ZIa0w4WHJoNEZjCkMwT2tIUDZXQUU5cTB3eHNSVlk3
            RG9neXVSU28ycFl1azlaRmxRUkd4SWMKLS0tIDBRZjlDZHFyWnBFVnhMc1F3a2M1
            QWsxaDR1bGVxYysrUTZIQnRYNkpsSFEKH/zUcAyEoZbPzZOXM5vUGgyjhItpi3M+
            OLqPNX8+zi8WAIaHFLIUe6LLuF0+b2MTcXr7JEVVLfviVDkASZrrnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T16:20:07Z"
    mac: ENC[AES256_GCM,data:ce9jANLO3tjXyq/+C/ALEcbhhPgBYyFPUVHRNkwJ7/dPupWyBM9L5dvEUBlz1ROegIAbvx9T3aTgumsxUELxlAxMO/lQkNgbxUfAQCivsZ77diruwLN8De3f4Hp2QAcCCfCmGcRh9x/NjEdgerxtw+yAfx1ZJYpenbvXteuuW/o=,iv:sPM0gQF5u+HE1kcFDVl+dNoFiXbB19AoMijZH/4zqZk=,tag:6nUlxMiJlNTvXYiKdey4OQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
