apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:O75CfrYw+b3QC44yQ1tDA9SSKq3x3u+ZIFHP6D+m7YpPSWdVbGPhe37HRCMRJ32L1GCZo2j3r9d6SLxq33+Qs6hMxnqaWFWO4DoN9RMOqDkmLmsbuuGnDrnNIGvsd5onIvpjQs2Z2o+MsenN6Zs5CpaeGGLRRVmiAg==,iv:hsoU1B5VJukQdKhYcgyYsF60ORoTV6HqlY/VkSeZoYM=,tag:4vCeqqI6gAj/5cjZka9ohA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TlRHRko3VjQ1VkJWV3Nr
            V1dpNVMrTzlGcTJ2RTEvcGJQdWNTM2ZuSEE4CjRBSjE0ekdUaWZHZFgwTERId2pm
            NzBiMzhlWnVNelFZU3hYdzZjTlhjeW8KLS0tIHg3N2VBN1dDY0REYldISkxtUW5O
            RkFWd0tDR1FxN2JMMmVUTmNkclUwa0UKu+Sa9+q3txhoh4DsFOAYX76LzPrufYHc
            Vo85ub5HUeH/exBfhORJZ78+W7hhfMwNq7oQ+asL1PnVoBclGiSsqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T21:32:49Z"
    mac: ENC[AES256_GCM,data:Oa+NBSRfvqrcHMB/82CDi/CuUTBze2rWvcXlSfzN4uTWJ9Iz8N4Miyqzoszj5pBqTv6Q/LuYWpePsGvHVA707t1z7+IvW4m9WlDV3zGaicq7Z50rEFL3Z5STgHFk5A0f1wh5o33FJlUAcXiYft5ujIXx1vXFxjaMXRivxdKn6Y0=,iv:l1OwBaGeUXpB2hwxSOH3prBuwtimgHN4QS1i3Cc6+K0=,tag:fHISOsMqDuncQmzbCG021w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
