apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:VB2WObADYLQ6NfRciq3G9jeyKHSiSDiPPv+NVJehxzjDFtws6htkHCLruRvZ1pIERRG8us7G7FLn/etcJTWBKfXjsLhXWcYVQc/ZyyxygdBrgfozy4zzu1GHJsrZnPgAA+WYliYzcgkphTgvR2VkA+eY+M2iCeQRcQ==,iv:pv8zm9/AEH8roIZygmKiudaYmwthQYiHHIPmxyGPWPE=,tag:FnKyWE1s6mv+S0q5eEsTCg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVUxNYmswK0NLcUwyclpR
            dE9TOFc5R1pheERiUUMrNEoyMHRLQjJlSjJ3CmRFQVhVZjcvSTBKMjFxUTV0UnZq
            aHM1SXkvWS85djdzSHNoVm5oY1lnUTAKLS0tIEFBbFk2UTV3SmFpcjY5bXMwazBm
            a04vTnhxUTB4cENBSU41clpJSXdRU00K0K/EBbdWHenRrjZ4MUzOX29Ak+euVEh5
            PzkBLZsvwEIW/SSK07H/uHtRYGYg3FXhZOvhQYZbxNVwciMIOLu6Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:34:02Z"
    mac: ENC[AES256_GCM,data:CKdR/56O80OEZIpGHkLRKDtuW/4SlXZtHsH+p2JMJrHgbh7JgDfWYd5YyUSbiZYZct4XA3BrVqyjXhh+qVNrXXTO0KMt1tKoAE7UoMa4TsmIYq2qTI3Gk1nFzB40zr3DuCQXLbUzoD4jj8z0P152loGeFDZQgGP3r7EwGFoQZug=,iv:9PLuaolJwjeeioQsvcQzKhQ+8ju7Mn1ggKgxHtbziOc=,tag:fZGBGGln5ksDhPP0wQ1QEA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
