apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
data:
    address: ENC[AES256_GCM,data:if3mhRSj6jOruU/JcxlHmGk65MOJZB+2JEI+CBc4waum912+6h4aApzAXGv62F4UAiFMctOWIB2OnLpxFlggr9rKosirSsigfSTQplfi1fJpKZ52LueDUEUoY6E8KBainmIiIrRWlgGn0mFXKJVSURNuXxCJee8AOg==,iv:kc9zl4Mszt3GIJS8A4LcGWuVaQ0lFunxoWvWlJGmBuQ=,tag:FpMrDumm2//dih/hMj+rBQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RmkvMmRra0VDZUJHT2cv
            ZjNpUVY0SE53cjNMa3FyVDBBRWgycU9USDFrCm1mMDNjL2RkSU84SlM0M2Q1MHRW
            b0wyOXpTMy9uL1krc2RzdTM2Qyt0TncKLS0tIFgwUXhkQlc4N1N6UFlzdEx2RmZH
            OEVDYSsrUEtTUHR0QWJsem5uT0pBQU0K2wepOS4jSRX0zP5O+ZugSSbD3LcIFUl4
            azAFi/SbeSwaa67Zgrogh7Ps00WHIBjIYqvleYYqbiv8SMQww7uQ/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T21:45:26Z"
    mac: ENC[AES256_GCM,data:LR8dM17zJfJ3y+YEh8sw8ZShA8gDU4KXeQJvDrJFEIERZkklukQZOfnqXgqu/rZo/8jX2yrEDbWWydoOujJRg5FgdvvLjEMJbUVqNPqPiFQkj45WfjKDH6Gq8bUF/SfwbRJ4DbUHsFdCZzaGR0Zy/GEUf+PQS+aywBJPqQzgKIk=,iv:+lhhKkb04Aa1XJkSGvrIfriEK3WSTSGcl09IKL81K00=,tag:WW2CCtR25UU1WaY7QQmM0g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
