apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:Bb/+yYHxC6Lj2tjHW4HP+1g6z7BrorZwTkZVkqXScMed6oaGAtiKrXhvfqCnO8VsGqujpibbnc4BS6mynrldRx+SS7nbQjsjeNZ7o4HOe7FdLNBcQoMFQP0t7LO7DnYmK//OP4xptMPt24a13PNneyXVaxuk+/AIIQ==,iv:GIBRfftpIpjh6qYRUEI8MPG7F6ZP6v+KI5tcPlVW2U0=,tag:QMhL6vyQDilyOJuGSk44pA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MFNhN0o3eFFUM3psUTFH
            eHhlMy9NM0J0SlhhZXpFYzJiVUh2MFI5eTEwClBHVGpDTGRFeFdlVTlpMkVVb2Nm
            V1JCRTVmY1U2RGhWRElmaERyRzhsTVEKLS0tIGRFcnZlcnh4UXZpV25OS2xBeFg3
            dDFxN3Z1OGJxOVQ1TnhDb3d0dGhIVFkK9zYFQcHaNrztQUZcAcfWbXKM0dY0K2LD
            3LdAlaiU7s34VvnvPKrIMdxKf1+dJG4bRDNeBW3+7h28oUlpKMew5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T18:24:27Z"
    mac: ENC[AES256_GCM,data:4G0CqfQ8Ot1coMDg2Uxj+NACfa/TLKf/MXAtmbzMXoJTaopMo9RskV8M/IeJWsM7W3j0kTFuJkwywzVPN7yy+PJmJ/urmKHw//EulhsyU4ygpV6W2rOeCv/IW6dxrGDQN1Eye/nORSaUP4Grf026SbF/EyjVgUtWvCYfAdlgBaI=,iv:lak1xOuD8so0WHDg/0pIivdzMRO8xlLZ8KNce37ol6E=,tag:EBZp1Tz8HsOWZooRUgquaQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
