apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:TbW/lan+Zgj/M1R8Yl4tTeu4ZsW+8wIRX7nCkVB8rzEq+NeIvuiuAmjeo2iho8o1M3c6cBaHkK2ihajNBJCWWuQwgogG9/+4PX1PmIdr3MNZs8iBgwY+RlP3cioN66lDwT83DamB/AN1SRV/bT299u89QFL3HLwQHw==,iv:mLmIi6HDsGTYIHLWi0295LaxCt80h3WREjg0BCxOY9k=,tag:p5FvykQePTVTPZCM21rp6Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOCtPdDJnQ2ZkdGtKTUJh
            a3p2TzFZOWRmQzI3K0FhaDdyRmlxVlkzUDFnClNFQnJTb01JYkVmOC9FUmcwNXJ6
            cktOT3BqcjZYUkdsTStTTUlaVmMzdEkKLS0tIGt1WktGc1JLTUpibFRQWlgyQU1O
            eENPSU9KK2s5a0V3ajBMRkQzUnJmMFkKX+FaC3/0DPkvOqhjYXvOzoT3/YFi57aZ
            bz4oSRyFVtdDJEr1/P2r6mVeHJqXc1SfO3rWYOFjsVMsnadqGmVnHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T15:33:33Z"
    mac: ENC[AES256_GCM,data:by4kRHvRXbNBsTMsnDMbyQRp2pPiTvTm5VaHPKP1cbVXaR/oK3PmbhUzirmz2h9PJC/rJJD/5RPnA78Cvt1XgsWicPd+0GwZWycu+6R+nQUu4DVM/BqZoW+0r8M7+X/ceYYDge3mQeu/xMNPu5s86VjkimQOyzAC6jnI+95E524=,iv:37ggzCm9HWZU3cJ/5U62ngFUNRb5CK9FlJ/sEbgkOiU=,tag:M2u8f85buIuXRMWzVG0IrQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
