apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:2xZa9SwpDSR8ERGzp154uzFZXZxFmsginU229p7TGpFuUbU4hfjnxOmwLLnKnSO7bJepiebvz6lQ1tkkfsUolRRqpF/8exX6DNxtsfl+dblIW7H5YHzKoJb6fpN9Ue9Pj5Rj9FBhgTIhO0/hmi1/amoDSb6cvIv5Ew==,iv:qrO3bjoHnzLadRBFTU9vY8FvB7L+jh8OtYfhYXM0c68=,tag:Hq0zG3X0YLsAboxsqzDmqg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWalE3TmN4UXZSVXkzZlNY
            dnJxckY5cVdJUXZCTVpVNlFJTzVkMnBBVFNVCkcwRVFjNkZLcklqcTM1SUxpOVZt
            UXBJUHNqNHExYWRwOC95bzFreHZFMG8KLS0tIGU0L3VXdE5aaGMyRW9VRVpEK3Vt
            U1ZBWFU1bjJuU0IxdlhDWStHb0x3Y1EK8Ckft8Y9P0uLeYxiOg2Gev0khFSEem6G
            IhDigPGxT+ogv0/oU1AtEe1MCIheQdxfAvJeb5H5ErE6owvR40i4dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T22:13:34Z"
    mac: ENC[AES256_GCM,data:3M8ga/RT+yQvqOzfuOanm20RiTjEMZoD9JDDmmW9XcFkkLCiWIbRg6VMsybbNZsms56sE+memvVvYgaAmahHKdfR+m7GralD3OLSQQBZoME8mWt0scsyNmJZil0kNM6qgV9ib48Aezz2SOe+Ae2wmRDaJ2yzwAC763KCqd01Zkg=,iv:SEnA7nRhS29F+kTtgRTdED7iSgw6FQ38Nv4hzqfcykE=,tag:rqaG0PWMvsdMSJEDuiegFw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
