apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:I3ftYCfyMrWxCe+H+SIx8P7rryy8dKMqCOh78VU52OjIpo0ru1fkUJ3Hufr0fOgmvwkJw1M14NH8ucQmJiZ8hPg8Dg6zmc7PR1CoMESEvVeEnnE9hNmMDF6J/h5UezkaSzFAROIjlcWItmbvnd97YImpuSnGVbMibw==,iv:F9Th2EuVIEu6NYMh7NCdhRgJXGdbqnA+g0JyyWeFpio=,tag:Pa0A0f8x0Lv5xHS+npnH3w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYXlDeHJzeGFvKzZMSjR0
            VGtLOHNtUlF4ZHhSWGFYQWxPY3IrRjNlWXljCmc5N1JXK3NWYUdZbUdBck1CR3dP
            cUwzRS9qa0hHdDh4bFJjcHRyVWhvbDQKLS0tIGwzc3JjRENkT2lMVnJUSTVRVEFD
            U3NhWUVkOFg4YVRHcnVKTjV3dEZEdkUK61KAD0FB+4mABs4BOD+FK2IDYPlFyGea
            8EIjjfMQuCW1bZRSh5cyZBnUJ4s6+E/lckld1Uk2UU5DV/utc0FPcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T09:17:44Z"
    mac: ENC[AES256_GCM,data:3bPdqR8nPIk3P1QJOlUqdZ6huwYuKWgojoe45VVNk0iz0vTojBoioXGu5U6CpJZPLTZ7dMmE7IegWyrA9qZxE13PnXhZzcc2C5LkB91eabRql0ZSHvdouhL3F0Q8IBVusoWg1D6jDV6Ne17WFVAIUZkQnpumoVen4ZPdieWTV+w=,iv:IJwElsBSzu3ni+pNkD5/RIAAGEjl8sj1ma1hd5onM/Y=,tag:XgchUBqofFn6NHFn+QC7dQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
