apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:kInPN3dBWwQv8nazW+2SVdI4ZORMpOxWRpZwVjXcYStL1W1g/0zDT43EH4HxykjqccCnfgGtYM3DAG9WHdQH4egTeLmHI/SxQYLwyYCDN/X6sKAVM2An3i6sca/vVie1wHDYpm2r796onzsqE32ygw/Wgf8UTwFlDg==,iv:g4rhJs7sbMt70a5loqcX713/Dz91xXEbJJmAK7oRpMM=,tag:vkz5GBKiHDGfuVdoUmqToA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqckd4UTVNRzU0TjdWU3dw
            OVNxd0F1MlVFbFRWWGE5b0p5MUpQVk04c1ZZClQzczZwUmJSZkVHdndKK1dIazVW
            YnZzYmZ1U3VGRXUyZ1NNU1ZRU3o4cFEKLS0tIGJjTFI5RTh1aHRTUEZHYUVqYnV2
            d1FFQmcwWmNHckM3NkZkQmdBalRoSU0KRuock5UDS/cCVCc3C+TI+kcX+B8sjlkl
            ZrDqt8TL3dzis3yQKQ3fIetbOSEabiiC1inj2aNu25Je5L5JjQL61A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T18:06:51Z"
    mac: ENC[AES256_GCM,data:+WrsXkPLVBpGhy9RX/gx44nViw4flVLL/MMcFNPjGbr091kdzGMZSXKk5hG9vwbITx17yD1XfMnkmib50yhwXFH9z9PdRkrXmZDjgWGbBYGCHhi/T5RuHOXBIQ86fMAGlO0Pb0lIPGkIcTDQapcGKwzIWU6vR3YCKUkiN/mwqeU=,iv:cAQ4UB9bggOwEu6MPDvdyDdcMP4+exVmsZTRJhMYsGc=,tag:S0M9dzjK1afazCI15l3JXQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
