apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
data:
    address: ENC[AES256_GCM,data:WFcs0SarnqyCXHgP05ZLpk1oWcSFylg/80zEkSFV0+1ih0lTQlsu23uK0IEf2kE1MiQkowQmDWsvKDEHjQP70nG0Kcpe86PKruPgwo/4jG289/AEh6aYmXASY5QNOqRhRnfmt2EI0TuanoDz+juuuIBtDx3kM9IDgUw3KRybYMugnaydnrD9BpuvOfnrNDCmkvWHc0MwPPMmiKSy5J4jW9guutM=,iv:xnwx5VNvJpoKjh8XkDOJnzajHK5/dtxEjFDU9mt93UI=,tag:hGKQoXDs4HY7rZxZIL010A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc2FrdUwwK1E3WlA4QXpF
            WEtTSFdueDNvWnFhMmdPdE9vdVkrd1gvcUdnClVLQ2VqYlMwM1FmYUpPN1dCKzg0
            KzJrY05uY0dUUzMvOTJNOTJuNnROSXcKLS0tIGQyTU1ZdjZBWGFwWXF2WHpTdXcy
            dXptV25KazNaOUhpdnlPQlZWTThVN0EKf/VY/N1Ib+oUve3LNc2AQX7PCxWa3Q1W
            qr2EHR3tVJCa9KcSljRvavggbI41qs3HSuzQhoZ25z7EVvN+FC1qYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T21:48:52Z"
    mac: ENC[AES256_GCM,data:mOfuu9/8jl5A3GNiND7dgNM2UuY+T5dcEXlUDWcTxlDmWnlFjrcNJGIvHa2toCj5hvTqSl7GNR+lRTguhWlABOJyvWMOn8oKaLeSCoTPh8rwrujIwFqLYJ+8N0R90y8KRfetaYb8zRVY6wzDnl5tpUALbm6L15ErvDB55ypReNI=,iv:0E2jiY4kIkU7OM6M6Fnjs22lgDAB/lgwZttaf8+6g7A=,tag:uz6FGw0wFrvzL8hzbvfM/g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
