apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:veNpRiohutPj8NgYu94Hy2kFapp+nnxDzd/1X1O9rnefB/X581Mn21w1Io2uizIwg9XBDZ7rizKe8iwyX3ramaxn9RF3q9omzra7QUbS/sCAlCvhZ5Hq+xCy70jmjz859jVLprQvMVBQLufddxS+D0e7UP63gEWv6A==,iv:54MulLk9fDOlplJ6ck5mJmmP6lN34jUWKrwxuG6hq6I=,tag:4Zu6DXCOMbd1ajT2/fZxmw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRkFuUUEyMFV2TnZ0ZnFa
            WWwvWnRkd3lxSncwTGo0dmNpWXlyblQvNTNvCjIrSU9vZ1lqQlZ0clNVeVdpTTcy
            Q05WT2tIV21yT0lMSEVheEZWVUlyL2cKLS0tIGI2ZzF1YUhvQnh3Wm5BaFAxZGtH
            M1hxQ1lMVXQ1U1MxUnF6Q0ZmMmI2aGMKQAtZj1+fa3oa7aG4jFgC2TtZIDg5LnNZ
            JZwMOkvxzXF5rK/t83aAmFjZU9NccmSCTahr3+WNMSB90Qui8uN/+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T16:22:06Z"
    mac: ENC[AES256_GCM,data:C5e2sYpCED3qDKePAJj5HT8/gKMLSLwhyGT8mVKiirV4oYT99tdtlumhuWoOdIwYnEW/kDhdIrv+o4gmiD43ztzL7v3M+656oVzV9TT5JN+SQznRa7+O3PhM03gTePSLZpBG1HYijRHPtPd+w3r+39gL0yjfxyYVl9rqontLxkQ=,iv:YhMb21yTP/rWcujq8mSSp36/SVwlTLBN5vaz9tQ1Rho=,tag:i/bdu7zucNHZ8Tj+/aB/rA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
