apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:FAnku/VBILwoWzwVlSLeyo/YY2V8/AxkbWzpouaD2xY91M0lss3PNZHyj3q1qVodZfckXz7moXzoneRISwe7jSYfWEwO/FTU8MFnY5aHWd0OYaUe9XTl2ToNLUQ/EHbVUhpkOs7j3eobdXkLkHfCaLkWnAbL8crgPg==,iv:mSC7udXZHnIRFSOhaEzDbyAcO/7O0j+2vUgaThQUEwc=,tag:36qhw980EGfJ4HXJMKfbXg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WDlyQ0xjNSsyS2JBa3la
            VXMyU1psRXF0cUVLUGYxdVF3YU0veEFSdjNjCm5KNVNPbW9mWDh0TXRhU3lvMVVN
            b3JJNDJCbHhxaGdmTlk3cFlHOG9id00KLS0tIFVWS0crR09jZVlFWWp0T0JHZHFj
            Ukt1RDhLV0l2STFkdEFtczdVODJURWMK+IFAxBtzjpP42V1+oMnzFpjRgQR59c2b
            5EJfpZbwJ8Foof+Mvo5mDoYY0/5HfA962vYEk+VSO1xcjL68AvCH0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T16:06:21Z"
    mac: ENC[AES256_GCM,data:RNasp92X6CJYKx1pmDrvwhPcrdo0v0qg33RDL9PkehuhOeOoqz43FmYo09yKqLFhCqIOeg8gHWepKVKPyU6s0glnX+gsqi+sZi1tccVH0U/mTJyvl81F9iUb3qFvKP80QdHLuHxd0coZBu3LLkX/5uv0ZCphbTjgVBz97SVOrIA=,iv:sJUhZkGSNQrHY4scyk9EW9rNAec5psy+JairXNIjxN0=,tag:mUuihTyc3+QBsNAqJq96wA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
