apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:2Dy6X8YqW27NMOV+Bb4LaFSCAHIOlKDVLYgL/E0qygQfDaDd/+A1ukjNvf+LUwybN8J7GhnchyAqCZ3ztxUmX5Qp1Syaz4+k9SVnKQZ6pzS2slaTqBrz9MTMO2Nb0Oy6vbE4D3I/SIuGZf/rqbTg+Y/OgzClvrclxw==,iv:C6Qjm3XJfj7WUpHzfH1P2QhnE2d75FAGiPa/DGb2d+M=,tag:jTkLoxfoIeFtVIx409C9tg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNGdEQVV2a2V2WTZIOVR2
            MS9mdE9iYmpnRmxBN0pnVzR4RlVzU0N1Q25RCmxqNDFYbkxKSExEN2h6aWF6czV2
            RVJoRUpTMHNtU1YrUDRLMWZEKzZiN1EKLS0tIFc3aElkdEY3c3doU0tsWVlXZHE5
            akt1YlpNUXFXWVlkS2lVTFR1K0ljZlEKb4U7kfpPCdNyvCNYK2hnWgs130cp2IiE
            tSQwTf47Rr9eQwAQTwTblRBBM9Svxl1oKN54LDbqhe2Rhg4fggw8Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T22:51:11Z"
    mac: ENC[AES256_GCM,data:WLBLc+Xccbfqs/E10O3q7v1zRmuCsZOIE+jSUmR7bhG9AJ0jqBNaiqErugO85KMm8KaNEJkGAw74PISKjpFzwqb9C+QzJrKAG0iPOSggDTxZ7HjfhIFtL9uEbVV/w/v2Dxg0eaXDzm2cUOcjtuLNU2wnyi4OA6Ahrg5Hdn56vAE=,iv:iSFj3rsgCBnZu/Bm2ePqX4FOpMwvufw97WDYgcLyCvo=,tag:ev1Axq/qwTKFqfPj/4q6Sg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
