apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:JA/STCwtZentpNrkyM9ax/4YBuZ34S/Njs9N1OsHEIiNdcOK5lfgLkJya/cIxwDW/YcuynQ/igBZvw4pZZqY7ON7jl+9cCFHjq2xsS/6JmWL1/p9zo5+yCGPT5BfpDgEPIaY3FvFPrnSSnGgEOrNe5CLUyx63uAGlg==,iv:qxXltlCgDUVrTbmerw0SYOhSW2ylIE8+anlknEnfQZ8=,tag:sVu+h4s7+XcF/DY6RwY5Dw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV3NhY0lOdnhzcnBYTDl1
            dWhOQzhNV0NDc1ZJNi8xaUZIeEJ3YkFMdFhJCmZ5N3U4SnlINnNwQTV1L3d3T3hr
            VGhxdzdjV1dYR0pSb1VGcUI3eXM0ZjgKLS0tIHRNWmxqOWVvc09TNDUvN1V0Sk1V
            elUyT0F4cXFOL0xrSk40R0xtZzFsdEkKYXaRFM0xN8xLifQlnNHMwYq0uDpcPDWy
            aEcjkNleTGF/aF+Y0dwIlPWPNghSqzf1erqh9X+3x/IanF9+nbZMoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T15:46:33Z"
    mac: ENC[AES256_GCM,data:pPVlgB9s9G1CrxPRigFnds2cZMlhabbQLdr8uiSq1Z8oBKTtazeqkd0LmkIDVj2tT29GVrItHyc+2+AIHwPNoq4wwfFiZvcMq2X7HrlrGSuD3o2xlvUOw0iy3jJgT27/WmhhH4MJcun3apLq7pFgPEuReshRadNIsjE1CeaWFLo=,iv:gPE/41xxNQsGFVCjQCPKKJn1GMoyk6TsswHV1TA8NvI=,tag:Ikg5ItfxHKjnq0MkQkxVVg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
