apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:CqgGhGFgh+AyRlnJh4qPWedQ4Texmu4nlCCFWHQlrg336py42SsHFaaSAq+DexJUAPNNyuz3XxfDVg83lzCbc9o3nuMhP4dg2B2Bsd4qA/RgLyopDK5EcAzyECdz+GzZ6OZUsH0mfKTsipx81c+yv0NBqA3Wny9kHQ==,iv:ny4HtQzNrE4GtzKtMKDhrRl20Ml3DluCaYrmeRU5rtg=,tag:uD0AYbgGn9YpyGDzmXX6nQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MlpsbXFtdGwvS051K0ZG
            bWJyQlBnZnp6T1YvRDhQRVVtTXNzai9CWXhnClMxa1lVTGxkZmlGWFIwd3hWcHpx
            ay8wbWZTazBKak9WTTVSb09LWFVpTU0KLS0tIFJaU2FKa0J6QzVJMTdUbHhyZ2VD
            R2g1QXY5bnhHS242cVBJMm9MM1o5ZDAKhisfstmFN+A08ezh8e717XH0UXQrXqzg
            2AwRJLt/Xo5EMKv/I2ymV7zn33rrEOu0tFYrPDAo4Ei64R2i2e9Slg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T22:15:57Z"
    mac: ENC[AES256_GCM,data:zzin7YpF8MCufOFWwcGARoeZ/Fe9OpGxnVFQ7DyhjYAYc3Kefcczjvm7vCbgXjbMtCRh0ZNFqeNj1XpTjkSgzlvhKfmdKuoSyRjLAQxBbW9rhmzAnS4I4/juNiiymUstLM/pWubd9sFmLCH+C8vLh3ibmopry+XBtrALj2jRGhc=,iv:95gm7hjiBa3ymazGGfVBXkWX5pGDOvQU4HK1MvrDhrs=,tag:GPVMHtAQTfsl728oGTmXRA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
