apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:Tg67TGYtTRb3jZEm8v4EzZOf4uXmZhBOscCpAw2LfHH5xChjGD0jSuAAQjbeQSik3hObnw+sd/kwQ2UB2ZroDvNBXNlNa3IZPjUw3xJFZKO18uG7HqYXAEngHqAN24V+bfdG74CRGClK/LvsR5+vdej6MJWbd/aTJQ==,iv:5zmmKytwOyobTaA8PunnyyadBzk/Xbv6V3F0YIY9+GM=,tag:CGNMmxtTZR9T6QbTNSPi2A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT01IU0JOOGJXbUpmaE9Y
            UkNjRUZNODhxTVF1cFEvbnIyd2NTeHZZRm5vCm9UT3FuUWlySENhUFdGVDUwcjRG
            dnFQZkE2cHFIZ1YwZ2RuV1JSeUhMZ1kKLS0tIEtjL2JxVER1Mm1uYSsreDZKSVNH
            OVU1Um9JeUEvOXZaQkpJWkFWVjV6b1UKSk+mk3BOryH5CvMvgAptw8ny/CtFj0Bj
            gdeAr6hVBLcM3kmRdPlYrIQNQaHvs0ucMmzspg4WpmnnRqLIxUsZnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:00:42Z"
    mac: ENC[AES256_GCM,data:NRuH4ev2zVNtccO0C0XfyekjhvnrpWQBM4/wuCbyeV7V+xBObmMy4oE5k/eCjc/34mV5mCHigIvQHSjoHkCxaArMrgCU/elBdtgWFsvNcjNsjBhRD1mmkrEWcdei9l/AW9t46cilUwG3UoW3RsaGhX/6v6qpJfgj1jOigyagP5s=,iv:oTxszcoAYdfYWJ2Zwz3lZcmn9uPHpP2SzVRO3GimtoI=,tag:7YtBEhVefpG5QBlWt6YV4g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
