apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:utwUrmg/dUKH6R1E,iv:LOkERUcQ09knMZrvzWBz5cYJADz3aqS6e+nBKmXXFU4=,tag:Ohr7tvFIvTxGsybDdC+ewA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucHZXT0hSV0pYVS9Zc3Y3
            K3FlUWlCN2l3b0xmTElsM25hN2hma1A5Q0gwClNwL3FVcTE0cjNlaFZHS3UzZ1Jy
            bTVmR2p1VDRreVcyTnpFRktxdHdob1UKLS0tIHBtWmJsN2RnZjFpOFVJODc5WHBM
            VVl4QUNqRGlreTA5RzBMVkhUYnREaEUKWdb0mCKzyo+lhV/K5aHP/H36lDPNd7cu
            Q0I9VZOvg+NXX5tvGFdPF0mp1awaTOt3Um9lBTr14rd3S+KYdoH5aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T18:21:39Z"
    mac: ENC[AES256_GCM,data:SUEBwU/AAywg0hdkBEo44PMyXTHxdgPLCM1HnpufNFt3xPzAA/ylxX/3pQmugJXWCYHlrrDvAm8IqxPJxk538nfvhlZT0Qys+9ReEk9xyrracq4j2KBJ+SaRjAkfRuQIWeJ2U88vQ4z4ib/vEGIhS/cqG/R9QK7rzpObzNkmNtw=,iv:dmDhktoQlimtYXT/d7icYysOfzYgmT0vXBW+JGMe/qI=,tag:HgdsiMoam3NDggbtfJUXRQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
