apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/K9Qbf+bdHseEZvn,iv:DJ7uX5pfLStyamyFWKl4cvoHBf53NmXbmuRGjfBD3yg=,tag:d2GFXrgT9s2nyvR/jLvNbQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUXdsNGVydmtHbUNqaS9N
            MUZzQTNmaHlFakQxUDBTZDZtSEdmd3ZNSTBzClU1TGEwWUc5QmMrczlwVmtRRzlZ
            eG5GaThmRGZrakhvNnJJbjJ1akFFYUEKLS0tIGsyNjBMMTdvb0ZaUjRWdDFDa0Y0
            WmJ5SlM3bnZmTkJaNE1OREI1dzN4RUUKBBNE4CdxVnT0DYC1Q19zMWvpc6M6xpb1
            8r6qkDlVjVLtmnX5ZmwxSiSUjQCZEaq/2mptkluaCvFLw77hcx5sWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T20:43:15Z"
    mac: ENC[AES256_GCM,data:/fWhbS9tpy/rsIkv/vV0jKQ35OZMeNdFzGhPOaed7s++FLCrFhQ3L911vgZwkJ+VjErE++SirYFQojFP009avFLdI97KfBMzgryXdlMrBqiteJC6bV3xiLKgZ5LeCOaZtP7Ih/Ui8V9KictvakKOAuS8X5fzrnHTIHvLMxN232E=,iv:P2dDhFNK/RtX5d/2+EFYAuQ52+gB9mO9PSdXq+A7UxM=,tag:sTALkvqeJgkzThB3znXctA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
