apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1ZxfdzuKRBJVYqXN,iv:VeVKusWJiuxkDxYgUBfccBPJp6msF4FLD5oR8LyXl3g=,tag:1ZAHqW6B/RVmMW4I4nJ42Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMk1jWW05K1JkQVdDWjZN
            T3VSQWszNDVycWFPV1RDR2s0Z1lLeUJkeDBBCmlGL1A3M2cwOTdLNWpjY2libDJv
            VW1YME9XbDl5VURjV2sxZ1VKdndCSkkKLS0tIDJseW9oYXFMT1BPNUJ0MjJyclRz
            WENXWmxTdUpmRDY2aVBsZkY2dTI2U1EK8LBxRXwk/w5AJqrcw0/6ygKxvpp6/C3g
            CRL6HfzPyftTgzuwhbDolCF8Pbx45+GnRNyUW4liMIPWHyNu5PTXgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T17:28:08Z"
    mac: ENC[AES256_GCM,data:ty37kAtoUauQFf7FcaKQJCg8d4FbLqzhj7DPGL36fVrKEIpSbBUPyGahoT/x6o6t2n5AT0brNoQfbY94IQgagXW1eca5MDWN9qcYSvOaZ+YxpuvbQjBvzxRbUwKJFfFK5aLp6a3ElaPdv6bAuk+LYd2xTY5sZeBMo9mCJMkpjc0=,iv:UTtP6sIBKDyV+b9W062gw1UYbZ0d/DxJb5KLEzw0DOY=,tag:LyBxRYeWJa1buI3sXObrtg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
