apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RyZdQ3H6seAYk1CB,iv:36909BSxJUhAMaFVskL1i3CW9MwTAnnDO4VyimBvIqA=,tag:z5g1e878qJkcjW6v2KSjiA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WWxnVk1KemlqRDFRd0hS
            c2VOUzEwNS9XVFFscE1LQjg3YnQ3ZEZiR0UwCkNiZENHZGIrNXg3UTZwTitpSitt
            aDQ2S204TWt0cU05Y3dwNWEvZHd3emMKLS0tIGx5WXAzSDdudG1SdGVUb0l6OXQ2
            eEdFdTBOeUtCMXBJR3dFdFlWaHM3VDAKMUIRqeI7FTOLRui3MCs14TmLx5JsbYPa
            LhafzO5k0tg4GTOhl9a5DleWEDek9KtjiqPanjvhT0E8OA4IJAca+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T18:06:06Z"
    mac: ENC[AES256_GCM,data:ogipCGu/oION4602TsSJ1x8eadRUXOND5bVxXPZFG3qz6mwIu8sGhd4WIYsGS/09D35bgmlmeK6B4V6okaw64Q5LHLQy9+x8nl+LxXZL2xnJGTKaVNPWM71UlYRC9uE9Z/GgmD6nccbwNxKwssPV1GRcOzsu9gkwnA1CMkMS8aU=,iv:IMd1o2HkWLKCTYkogFrQbD5uXhENYP+MOqe4spP1L9c=,tag:ZBZRAbHhtNsrmOYXptENkw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
