apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:JDvftEKW4vfaHT+n,iv:nCiGIf7rRv3dDkHDy1fIkEtiGY7m29lAVl9q3pivF/Y=,tag:3gxAqpJEg79F+loCSLnRDw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUWNqcnFhcHJBbkJSaG0x
            MVdNaGp3cUJsZ1I4T2xFZGRRWDV3clhGL1RBClpKSGl3LzBGNEV3dXFRSnJZRHBN
            NUd3cmJuaG9nRzlJRVZQUjVkaWVDaTgKLS0tIFB6LzNnMlBLZlZReVJRVFlvd2Vl
            ZmtMSmRIbE9wMWxFU3V5UTlrUTdndzQK/8CMOuPRvirA3evlSvuMWMqu06I5yLHH
            VBeikxjdEItJU6PF7rUJmaBhwJxjpuuJ85YwoRual3gjMitvQBZjuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T07:30:51Z"
    mac: ENC[AES256_GCM,data:xfBy4dVqoT3XPnA3KCXVxZ9OHXgJtIUcYDfBaOBj6LDY9HsKvkORfDRkq3Dl9ivxnGMj3yrqP2fu4NtIJSKXybzeWg+Lqnn74ueylDuiPK2jVEjCfGOFmuwzp4FHfwjz7Sswh2+NYQIsFapEO7JtAgIOhKO4SdPQZSYgKxX60mg=,iv:48N8NbyWnBA7aiLmQSX87oQKkSZ7q0qI6OpblKWX8pg=,tag:knRXua9jTcKzZBnb6WA73A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
