apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:EIP6cTGLiaa0DG3f,iv:KiamXNpCOBY8vyWfJnKiYaaeITxPpXkqK8+gX5diUlg=,tag:Bt/BNkRBc70pE5MdtdxpsQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWEl5NStDTHVwa1ZEMG4x
            Z2UraVo5NHZZa1Z5L0ZWL0VROHE0YXdXT1hzCnVCZ1JiRTNwVkdqWmxJazlESThM
            c3VwbVdPVVBrTjFOS2xOazZkb0NrVWMKLS0tIFBPWnV5YnYyT2F1dE52TEthN3hI
            ek5TMityM2l0VlRnQXlJNG1CbkhEMFEKd6iLIL0Vyvtiukilpucvy7coCqN9vAK1
            rgm5fn+t8Ab/QoMv5+iNjK6Gv+wMYweZM95Pg7FJwSw5K2qjlJdUVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T14:25:05Z"
    mac: ENC[AES256_GCM,data:vWFdIuHONhX7dnMnwT7yFgjrvNNVnVHBIyV66RHf9p5azJEpmVR3rUWZyviPQpEQd9t30vdDCRW5sW93oprL+Vr7TWWt4YSi8Q59h7KJhZFQNTHIzVWx/ioLoE42RETjRLDPhwFWvhhoObq65iNg4mac0JkhDki4M2/21c9EeDg=,iv:u1NhvVMh5drloOETEgbbyL8DCjHdvnKzMQaqS5c1GIc=,tag:APepg7voCLjeEGe5BEMumw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
