apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:82IqW2XZm7P2PuqS,iv:tTrPZc238COjJ7TKWMXq1voXqyBHJEeT20XJ2/aps6o=,tag:SSAg7JS/8Yo2syUa1EQYgQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMjNCc3liMTdnR2ZkWHdh
            NXZIRE5BMlpnNzBkYnM0a24zM0tWakVhd1I0CmVNTVFHV3NuQXhHcEJNTFZmZnh2
            NXZMazVFWW9iQXpMNnFiM0lEU0o3bDAKLS0tIG52RmFSYTJaaDBQVm9EYm9NK0NX
            RkluVTVpUjFDeDgxYXVCbmZwaHpBSmsKCMr0YR/CCn2A3AScnDMgLZbBiwwcHqiZ
            5UJornFSQpOgR1jigVJIAyQGwebHlRAMThphFOH6HiwgO/VtCSdLug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:34:02Z"
    mac: ENC[AES256_GCM,data:j5+8UMZC2+NUS2Wdf+6IJ+capFI14+cGFmxC48baKl5IINiIj/VqVU9f2/R8+36gmiwAFOxkrzSPc3htDFyiIlY+y2Dt3O78oqDSxghmUNwtAqM3f46HRm98LKB9OIQMcOf14fN9ldCsXUDWMs0JwDoyxGIsZ611EkinRIRo1yE=,iv:Sn+kJFKyubYhFxj4WeIYB3c/+syhs8Di3ydDv2hrG0o=,tag:fJVMk6sMJX6suU5f7u8q3Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
