apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7lNRHYlhALSiyTU8,iv:8tMvaY/0q7Q7NURDPdCNivnjfusLteiynn5l9qKLcac=,tag:FanlWnLR8ej1PZtm7wLTeg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NlZuQVdkTTRNUkpUcEg1
            Vmp4S2tXbnZkZmpDczN4c2kwS2tBNzNRV2k0CjBTOEYweDF5c3ZxSUFkbVp3d3RB
            SlAwY2NYcUNXQ2V6RHJVbXpNdFp4cUEKLS0tIERHN0kwdDY1QU1oNEh5MkdhTXVn
            VXF2RS9RcnVXRy9UdzZMbGIvc1lrVnMKJFFCfU5JQNciEAXdd/hxAegGCuNnt53O
            c208nOiR5UVdzoexL2dvw69hG39a89+/Tiq8+T/DHoENqHWQBaPFWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T05:36:23Z"
    mac: ENC[AES256_GCM,data:9fEnSU66z+zUVvxmRRGDpn1TSG/OX9CceVlLv9Wx+usOSsTB9L0BQltSINnoDoyu6Cj/4H98OWy62Iu8RCIx/JnNAmcximhFBfm4ua74ytpm/+Omi7wiiYU2anTxWqC35bhzRJdaZxzKW71ObSNhjru/CZIPDhetJ09LBppXVNg=,iv:eCD9Bq9DoOxjJ1B+ClVCl4sZznA0qKcGFljniWDKf+A=,tag:9WE0xcjQjdv+iaVUbVLIMA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
