apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rt/cg9djjG6S+Zca,iv:TYrZhsQkmNcDMtqMiBEWNCm/LDzFJ2c4EbJ1KyLdfKM=,tag:a7pbw230srlyGMw210LLyA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRVMrWlVkY0JRRWgwRHkw
            bVpVbEtlV3lTd0lnRWs4WG1GTGVVOG5YZkFJCjJvbjBMQldWRnRZSk9TRk9Pa0hr
            aVlheXFaME5LeGF2VjhNeTJaVUJBaGcKLS0tIG5tdmdueE9IajlQbmtTZ0lSUFVv
            SGR2WFlrOGlCVnl6dXNLMEVhNmVsa2MK8faVkCWQvAEPemMZZ7c3MMlDEX/KsARp
            mBGyxw2HSDTXIK2M91DnRjAcPCCcg6BPhdMzs0OXTXHUEDNxXFc4ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T22:16:42Z"
    mac: ENC[AES256_GCM,data:ul/2FH63DCRpzmmPbRxud4K++wAmTzsOJEGg9CUGsd2ykGE5gjBAI+JjHv3kFCkcRZQJ/+eyHscDFNlhyo/64PmhlKWt3GJkjHI2tlVll3r/RWWBdf180v+T1EHjOkd86ltIMpC9nMcc5kaiNoqv4OKsHYcV4LYhM7AjoSfapE4=,iv:tclD+MPydWwSLaDsH8rHGifh71w76huGhZ1w+IFd2qA=,tag:9v9CgBzW9dKbAK1hXL4xpg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
