apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7u0uSwepJ0VxUoKj,iv:pxpcNYfv3yZBuj/7TmOFVcXi1b6pW//vxxPH3wBg0HU=,tag:JCgUV0DqL7iF1KdWZbpCRQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZGtZM0p5cnZXRW1vb2pp
            KzN4UktiRnBCWU1MMEYvSzZJb2d1Ky9VN1JFCjJna2ZGOVFidDh1YTh5b1ZDQmxy
            cGxCcXpXczlNNkdaUFZSWDVIM0owQUEKLS0tIFV1dG5NcEhGWHM4RlZCbnNzUURJ
            bmUrNVJLem1HWHVCeFFGd3p1ZjJiQ0kKltNJU9H+1Dz6fBxeYwythrjkuQlHrj4a
            3JtNHkXj3AzSuJU/YvasQLD2YP/z932lt1+ijkWWGv7JEU9y6/7EVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-27T09:17:44Z"
    mac: ENC[AES256_GCM,data:HT6KEDz+W93zoPlFDeBtjoFQK5kO5FcyAt+30jdxxj08140pZft5b+EtjqK4HfrJzTwfPZnw8Qo+Voq/phPyJyHDkRSHMkaX1we2mqNpgH4vmN1BjpZx0Iv1T6CnSDaIyWFnNUheLJ+8JoFgAolzDNxJZVWDQgD05CHarn7TGSI=,iv:lMyHKg4czfyCm5QTDTDWag9MtOia7Sm0cmFFD2Ox5EU=,tag:nGc73xQL5IfKaypWf7bXew==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
