apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Bhty3ILMrXuACGHk,iv:kpJXwf/yfBa/h7ppjWwAz92zncA5pbQE1pQgnU3n6Hw=,tag:xQ2Gh7dk4Ihw6zf2RBs8kQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUjJabVloOGc4SkhJZTA0
            WjhMMVlOeUFiVDlQWVpuTWFMK1J2SEhjbnpjCkRGVThkQ21zS24zYmV0a2pUTVBJ
            VndJR0d5MFhDR284eVRHWjdIWXhLSGsKLS0tIHZMUVJtS0VKN1R3amhKaktvZUo4
            QmNDQ1NYY2VTVWxsc3J0Um5WYUEweTgK6TYYhbX8XF4S15m8Hj8BBc0TCQDRMH9p
            00STe3W3x6qJkMerdxxfBn1pmVCp/u6EkPgH1rEfQnvoO0XVDGwnAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T22:13:34Z"
    mac: ENC[AES256_GCM,data:xhCBQUqfRdxqQX2qZbaU1ShuvoHcYFAYABSvJ4wRi1aMPFlTMd0Ku3OqP9E4gsdUSez+jUgES0TX6wEv6e5Clp3GJOAzGj4nk5fxYXAHOlUt30XZVMMCiWCgp5bDxzFRP+c89enIgAKDmNdXo6ieiowk8080+mM6lUvr5Pl9aUA=,iv:RdwqdFP14ibSLgdXgbWDj/J2OIfnt3v4h2lDzHdtsxo=,tag:vtBJDHQvLn+MgXFuavS3hg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
