apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NqtS7LjRwI0GJNXW,iv:sDDyi2Ezpkep/yO7UJz8HPlcIe2mCc7mCpUZcHb3yGQ=,tag:yVoF1sO3/otYpsYOS6bIMg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRTliekpoKzB5MEVIOXVs
            SUhObjM3WTZlT2RQeWdYZlRkdU4zMU1mekdzCnR3akw0RGM4c1lnVEV6VDA4MW1T
            TGFyblppbHY3YlFaUEgvN0FSQUxxSkUKLS0tIEtaSmdDcVVHUitvQUpjRlVLUXM3
            S2RYUmI3eUgzUjdGZTIvaEROVFp2cUUKuIXuVsj60cKhuaMWo7cz86WIZ63D9+o/
            YDb5b5qDiulPblou6PYyAoUkixe/57ci48flF+lE7zX7dZrIRwejPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T14:15:40Z"
    mac: ENC[AES256_GCM,data:a4uHsUgP8HdJ6AA32AOY/ylHP3gUweyTTWIeO8oChikNJwOxH3YZboi5ipjSgDuTg1ErWr2nVMGlaM33xoQRrLXeNKefaoGaWokzIGotq2gTvR/DmRisJhjVArrjyip4r6tz0Ae8b6SVL+ED0wqht4/uhmZjlpxXaXlLW1DuT1E=,iv:ivmEJytszczP85iSTvNRGwYhvYa4OeeDKivU74F0I0M=,tag:AFx+C6ceRWsy9UHwnKU6qw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
