apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OQedpmKAl1Bcyrje,iv:Cy5kESwcPLrANIcKVx7ZaPiGLNNdLZhAk3ZN0GAob4k=,tag:Hz7dkJCr3FGn8qel+MkDRQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSnV0U2dhQncvZUQyREc3
            Q0U1WUcvcWlNWkVaTTJwUkxRMDdWQi8zelRzCk5kYThWS1VoWStTWnJGc3dyd3J2
            c1lxM3p2YlZoMnJjTkp3UWZKekprbjQKLS0tIGdqQmZpRSt0N1pVVGpBeEdUdWpV
            aDF1VkswOTBCTkgvOVMxblh0N1R4ejgKbHRpf8iUbSFigb3GmTvhMmukWUcxOhL3
            06aoMwUsO+WxXeqlET9nScybbbZezUc5JzrpYg0naV+qbJjDLxz4Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T21:32:49Z"
    mac: ENC[AES256_GCM,data:Msy5SrDLXpEP4Zy9zglJPZHvYXtaUecga+nePpZyy+4DgvBzhcdknA4P1Mx6MLMwrK/du34uUGWgB7DepPA0TGhuGeCdAeUtKPLXrQNHqJuUUeujy2sWYJWueWrN5L+xPu/uohhsGwnbnZkAbgpXDLZnaeo6btj4YYQPk5xD840=,iv:qFI/hfunARfn5O1we/UhD0OrbOu/CgALjmmvPsBSJq8=,tag:+lm7C8krNqTSGuA0yuxrUQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
