apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:XOiJ0SFEqVCOr7/8,iv:TXyE7PY/PH+ZKNboSY9huaPkfQzG9WSlVkesuOFtTQQ=,tag:2h//VTWmzHgd43/bB9ypyg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MGNyUVJJdVIvdFBKdVlm
            YUppYnF4ZXVNOHcwendWWXJHQ1hIdFVQeERnCmFZSzNDTHB3Zmh1ZHc5cDUzaDhM
            NG5LNkhaWnhSU2tHb0FJczAzc3BGN1UKLS0tIE50OWxHeTZuaHV0R3ByQ2NoRXNV
            Vm9nNUh2Y2xYbStRb201RXdibzBlTlkKi61ayMBqDOk311RhDnmFKIgnDD3B03mW
            40L385EctCUnnWeat3qvTu52JXNUSRVqGjeSWQ2oIvqlk2/Qsl/FrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T06:58:35Z"
    mac: ENC[AES256_GCM,data:oxRe+MI0cnq926UentEKJN/UYOeVAOe3JWVR0jngNhCmht0/w9xMo1JLmMjs4gr7epVcYvq3oxUPMj1xXdlYIXzORGCAyCETVLR5QUYkRoKpq/cZKRQvm2JKu1PX8amn9KNUajsZuDNjtJs/HKgXWlmcIZ3dGdXDjguqBGi+tHE=,iv:huuu7YVj0EJ2FZUGjwX0vL5XBCaKUIKdL+ZND8s5GQM=,tag:9lQV29ijXyrJAs3HF4pPWg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
