apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:pxM1v53cYx8TdRU7,iv:mXHk2S91lPtiNE4+YQvLEoxEZq4cxaxx5ZVzy35xEj0=,tag:ErQokqEDVwW43FczSI6T4g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdTk4M1hUcldKSW5qWnFO
            YmkzbkpCMGNaMXMwV1FPN2ZQWXpsdU9zZFRrClNJUEx4NTVrVmR4VTd6WGl0S1Jr
            ekorRmtnOGY1T0k3dDFBNkwybkp2U1kKLS0tIENwdFhlckNWamllV3l1OW5KeDRF
            aS9rbUU0S3ptSWczbjVWVE94eko5ZVEKF9kmYNdRvutv3hFzq7DHBbNQoui3FYMT
            BYR8NBDjUbZAOmWzgiMIVo+zfDKciUvSKcpi4+1QeXDdFeY7Okud+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T15:50:38Z"
    mac: ENC[AES256_GCM,data:Xm/0oKHzf+NzJnTI2b/x4mBVJSsdBZi5u5aErLQkDCOaM4CWjC6e77ht/iuMG8DuSTmPMlxqJmpXtb7XeBxixlUN5bTPijD3nY1R/EcpOkaszwIseUH51u6nCqog7APiGFf1+Ve1NZBZVui2FVGcC3U2sAsqxEqlMHYfALIIQYE=,iv:bCSVH/QpXE2+BzdJLTXHNMxlaMPN8euUIHzTOk0fQAA=,tag:PPMPrl9qQAc3SD7GRa0icg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
