apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:GsX3M190JPDrPHN6,iv:eWKUookbbxS1gM5tvGuUa0bDUkrPbdMLVWA6vIM3Pnk=,tag:ESPuSfet0cSfVJPbuyhlOA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZTc4THk2OE5UbmZWNDQ3
            WEE4UkErNUFkdkoyYVFFT1o1cTEvcUp4VGtzCjRNckJMeUF6dHZ5c1M3TjdQRGts
            YVo0L2JqWmQ5NXNZMWZ0QTJObjVLcU0KLS0tIG9JL2xrVWIrS0pEVDZaK1ZIeEJP
            Zi9TVFhLSzJjZ1pETjBydzNQUnpNKzAKDXraff+lJm6AS/seM3heQ2wBp+km8wlk
            u0GH5yFFjAJLX3j6T0G+Jj52lnKsTAZdvoJ/hcoIWttogarzzz0R3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T18:28:39Z"
    mac: ENC[AES256_GCM,data:17TXFqB4UZEYwzQItyMvcLhazS57VdhjhxKizK/a6G77DRFPD++HqCKBFdwQ1it02gM2/LLNzUWfnBX87BF5ETWIsOWLalXKcUoh3H+LeEQYSf37ENlQzcZ50cXt0+fIzLG6mTqzp8gJ4o4Pmok97hetrNNlLQedUi64QJ9qse0=,iv:Fx2PAgWQeAztzwtztSRgvaIfG07a8NzWGgpRVpqGneE=,tag:N2eUcRKCLEYR1XMtGiKEMA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
