apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:jmICWVY/jXQ9CC4g,iv:0IHipbqXb/c4Nwso4l0semphs3Uo60+FxDuj3l+FUmo=,tag:jIgh02bAeducI+nJrQUlJQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSi9LTlBMSXNFa05lM3Zw
            K0dFR05neUN0UnlsamJ6MGhTWk1UQ1hFaUFFCmJOTVNpYlBJQ0NmbUM3ekFxTCsw
            RWJTMWVEd3lDcW9aRVRMV09sR2dOUGMKLS0tIEV0MEJsVVcybGtpQ0JMQXB0Zlhi
            N3lyQWxaNjhQQjVzdUJ6OGl0MlVvYzQKAHxxeLDO49KcnN9QAc2vMASwiQtjSeW/
            0tpFaTVJF/gaEZIOchBrVReBtmxYDRuRZn/kR2jCa77VczWohT0JqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T22:25:55Z"
    mac: ENC[AES256_GCM,data:bP0OkHvKDY/haOCcgwJ+9m5xCAWPFlC2tnQOWty77QdlwH9s4a2DYXkAIpR2qvPxusQweDFzG+fD9jqIDgZp91X5o0hXJmRU2Mp+fBR1QQn8kwcZm+CpGE/vg15PURgs/rJiKL1ogeBreeSdTd5uy785h+6XWl3Bfh4jyHNFlSw=,iv:FpzXFeRRTZoNEmCNXfasoSvOFmDMUaF3q9ex+478B6E=,tag:z0R6SL0IfvNy1VoqHw/07Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
