apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5lSNTEkBTnuQLrYL,iv:3kDyYqrx9Au1xp+sqDrPeleP35D9keplzlZK2vz0AQI=,tag:Ckb3nL46bn3IWtn+QOSFtg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQThCbTd1UHNobDhmbFRF
            N2t0VEwyRS9TMG83TERURERHbjRVTGZBTEJjClBzU0hXUFlqUEVXQXV1UkpTTGVR
            S2VVeEdIVW1qNGhWakI1Z0ZYcnJTd28KLS0tIEx5Yk80Nk1weHhlVVFvSHJWZlBY
            R0UwblBEMEdDUVBnamN6dk5HTzNsQTAKlcP5a0uuxNom0zFGTsWb2Pr1xBYNZAod
            p2G2hkx4ZTpvxL5MyJKRO+uvDDhWmS2WnLBpltt86IhxXe9rXpikUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T21:10:58Z"
    mac: ENC[AES256_GCM,data:RqAvATFCfB+FdqHOLJpGce2u1FvtBGuLHGDuAseRoi/pksEzBQHh5fly+t7fCGOImsUjVqNxr8GYLzc6d1DZ/xwEtWI6NfZkU0IUhG2lpUuIGxUBssgeDhWVeqhHdAvp4bpS6YJlFwhO2/dOfofiRJi5fZczhsE/TdP+6ndMDGU=,iv:OfNtTFL78GqJ8TxPKckRHwGvZi6wdBWIOH2A2sTjtjU=,tag:AlOKdJcbdlL9VaFSQ0MdcQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
