apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Hu7ePgZzExEderbK,iv:NLPKe7V8nSSurLpG/XZo2oIxR1eW3zr9KSQqL50t8Og=,tag:kTg05ReFP2eqocbW4EmKrw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWkVtZjBIMkxTQ0NFbjBk
            cm9zM2dscEFabWNyMzRSQmZucThBeFRLeUg4Cnp3Z3N3Nnp4ZTkrNG5zZHlvYzRT
            WUdVb245QVlvcDJkZzljazMzRFA1VmMKLS0tIGlWZndiL3pNdEt0QktpVHR0QWdq
            NVZBNC9KUDRzMGpWZ01MZXk0cVhXUm8KnpqupBUUmlyFldRSUbfnQR1AOJtwEjIQ
            PVGJRfTUB0azLDAC3EATZ+Hp99gEOnXpi1c6LY1IlNBjDg9873hu4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T21:58:27Z"
    mac: ENC[AES256_GCM,data:95rUSrki1DftvDkEYegPBFNAYvY1wvc5aYrLYnqb4m54liForGsMogSyuTDVx+PuciDACYD5Q31Brdt23xFJrn6i8rcrLFG2qkw5DMDt5Zufru6uQqzx9lJXmWqEno57a2LFeVWGWFCE+kQTJJ3wTryE1X87TMHqiYhixwvU6/M=,iv:8uTwt3Dbd53HTeaXZdMxlVt75Jv/Y8aLujPtg8bU5Ug=,tag:XhwUjkeMz/DIBUVpaQcENA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
