apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:R/if40o7br4otUKM,iv:SNvDxwOXiGd4bgnzd+xjhhTdeAVNP2uEUGUGDDhSNBI=,tag:aMO+2gCfhFcYjVDb/B8Ezw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVnQwWnUzaGxvckNVNkkr
            YnlBZFdxL0pBVE1LT1hudkN0Q3NWYnRUUnlNCjB1eUJTbnJ6cGhsbmFUb0dwQ2hu
            cSt1VVdYeXYzTDJPM3ljV2czVkdNRlEKLS0tIFhCSkJIN2psbzVPYmRqYVpmTDBw
            RDRVOXl2NEFBenJiUWlWaU9EOGRyTWsKsCEbdg9JUxNTnRrZ1oNschs+leQku4eK
            8O/KV0EdZZTYNrWxa1jxX/q2vTCINJBV3TEqVjgtMXViyGkAWxdbyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T18:24:27Z"
    mac: ENC[AES256_GCM,data:+iwlDRHEZ44mHTkvtNYD3zkCtmzT73RsoMLQZDo58n3NIhwxcDguY7S3+DuuZbVaTDaY3Hlwf7WaTRBXbPuzgPi7FBGUfEJk88m59EnesFbWmOgVSLBRSCtuoHEFGu5vidojMJTEz7cz0WaIyjFkI/0pitr6QiFnTut05glVqn8=,iv:JW6mt5+Cp7mFQWAjYnrRHH/GPoyZ1f+66ewC2R3ECFU=,tag:lwixuh7tgM5eCz4y0f6/rQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
