apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cTm1/SE4Bhy/JVt3,iv:h6dcDRmLwVhWdzHhsq51yooNqgJrtVfJMVfDM0uExjQ=,tag:lg1UwPJcYVFimbxeBJ2hNg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxazZEMytWNFdIQWgyb3dV
            UG84Z2hEMEo1aFp5bElRN0JwNm54bURqK3p3CnF2NWxLN3diT3lyanRPNTRPNVpq
            U1EwTDZmTDJ3NXJ1Y2s3czZJM2xtNUkKLS0tIGZsVy9nTEwya2dWYmxpajJVZHdz
            ckFYNC9wME45aVlDMlhGT1ZtOTcrZmsKsuvVsyGz5vIus5ysQTNCHd1J8TA9ZA1q
            +Q0cY9UlUViy8uHunM7ItBeExeWzM1GUKxbdPSvpxbEFlOj6MeMYUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T23:38:18Z"
    mac: ENC[AES256_GCM,data:ZqI1UFGT76Z3mmIWzyzgYLaA2qNHIPv4QjPh/0dS5HrG/Dc/GUVnCygWtdTiJGHZS18PQondANN1al0F4if90UWN1amBJS3inH9nYJHbuLvcWQs/tMc4mC2yJEoW8eR/eRYHDRPecoZs/cqK4Dzty/O9zYBMiHAaONtJWUzaE2I=,iv:AX1r81mjNPwAZacx9O+HkbPFEDYKhyaleqOZw+bmUFU=,tag:sRBYp3pUkHpgc9CW03efhw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
