apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tgEf3W3WXCrI87Ew,iv:XxOMRjZ62vekrX58nxNzHqgXb75DRsI3euT/wAm/yos=,tag:ojkf3xZUAOBwnI6h++HnlA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd0V1S0R0K2c0SVVwQWk5
            aHp6TW5tMzh2UGY3WG9ydDVqcExFcU9iQWp3CjhPbEFRcTBVSmVnRmtBTGI0ZXgy
            MHhjT1VBQ1QyU0lUc2dIL3FwR2huL2sKLS0tIGU4dVVuMnFkallENkxXSEhaUWIv
            QUxIVVFxQjdlN205QS9EdUpkTnZ3VXcKQxJ01OPBVyDjjtBWzGMD0g9hDhsvB7rQ
            uc1rJys1O7jmTaxL+D352fb39IBtkGUtLX40IkduBMZ7P47vGLsjxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T16:22:06Z"
    mac: ENC[AES256_GCM,data:7zE+ZSmAAh2NMlqXpfEPx0oGx8J4p5gloKEZjLki9oitZDjgZ2DoX5gVsJArZNVL1C5nEzTrmmVneVMtBU36b7TvQmoolK/N7AH6ZP2GD1vFR402yIDP+iAocRoB+eoK1L5URXyuMiVf5iSx6KPKOZbOX6VCYvPrquJOFo5AR7k=,iv:l9lHgvuAzdEm+rA6Th6BsFynON9/cb5IA8M/Bq/e4AQ=,tag:Myxevf5Lv6LFIvwG+NbuSg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
