apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5b0EVpvsdCcLM7dr,iv:wqJuzNlrjlsWPC4ruLM9Gb0loS065jBkEvdR9WCVxOk=,tag:6NLs5OJmS5J0R4FevsE4GQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OXA5U0JjeHF5VUoyeTFv
            UEM2b2RBZ0JVQzV5VUdFTUFPcFRsOXdvR3prClVOVFQ0aVBRcDFmaHJORVpJdUJ4
            RmVqY1d1aTNwOW80MzUrRTJTSnkyQmsKLS0tIFZnSTF4TFBsU25DRDRiRkNXUWxM
            M2hxamdyVHllOEZkaXR6NVZPbE9hTFEKFmo5zwuqNrQuOYTSknWDWO9AGliY774J
            1+e+5jh3NuIvcXuqWwCmaTgFf//zSsSaAq0SvswLRz1lV/IJIfKoag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T20:47:31Z"
    mac: ENC[AES256_GCM,data:5MkunY0qxTFEnaD5rXzcN63YHOijxsPd+z5E1BV9F6eR06+OI5u+Zhrep6/2YN2aipVl6n9nN4fDB5aYDFclgaAnf0qTaRLUzSopcu6TVaURvWb/dVZAvzkrYE1SXV1NilvBmYUBhNvVUb0A3TAF/sZcqhoxV/AuP9dndMprEzQ=,iv:Om7SYQgalOmH4RCWkk3/E8pEmZkGgpgb9fvTlOLfmec=,tag:nNWSuYULAC+DDAQ4kAyIMA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
