apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:KYVUf1sMAgTVblYC,iv:z5Xj1Ie/codcLnamIe0J6LNyEGjFbv/rtWWuTz9MUOY=,tag:riyIEfjtzF9fao2iFeBPhA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cHZuK3cwS3dEM1VXMXc3
            OWs3YXFxRjBnY1I0RnN3QmFuRnNuMzlBOGxvCkwrUEFZcEl0bFBYampUTWJ0aC9Z
            a1JrUEdQclNSWi9wSVpiVnVGeE04MTgKLS0tIHVIZkw3V3FQMjZjUTg1dWltOGtk
            N3JtWnZQWGFBWUJxMVVVUWp2OEwyVTAK5DbeiIO2wZF3s4Ywqn9sznCW2aBgiES3
            PENMracXCUN45wPTSfEXp+WJ0v9YpJLSYn0L8w6WNwLyvmwDtsAWFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T22:51:11Z"
    mac: ENC[AES256_GCM,data:KDVGMLD8qiEsHjrnj7NDLoeYwqwhZ1jEHMuQJFJxI5ewCoXi6xkF3uTGBYvhofqllilribb1yRwfBxxtUV/ajtG8j+SPhWbWkyTz8p+lJRcnvDXwUvFzapQV4si6Pw5tDecvU5wIFg+r3FdT+B18ADyFhnxIg50oyn3UKG7Xmuc=,iv:ZUG9GFnTKTAHN1/YObszKLpwMGpCN121Ot+lIbMtDBg=,tag:j7hJ/PLcx7PgZZLLVqwJjw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
