apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tCIKE/D+pnAVkVJc,iv:4/ygJxjRsvcok31dT6SXKj4B90fkZMYT7ObdZBH32Ug=,tag:KgiBZrFTM6OB0XDe2hmwQg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bEw5MXVHOVhRNCtSdGUv
            REtHQjZxaTlTVXpLdXV1ejM2bnZkS09MZ1NzCmJQWDQ0MmxsVldCcUt3NXNMNTJM
            bG1URDN1TDdqWkNuNmZTMGdQL3E5dmMKLS0tIFpPVXVibkpyd21wRnF5NGNBRmtR
            UHZXL0c0T054cGFOdGo5OEV2YWNFTTgKB8cae03x0d9jC164m2luJGvm4yq8DXMR
            CpY4Trz2WczH0EB6cqD5GIVEB8nJ1aAUoYMOlkZhBZCphzmXEvpUSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T19:00:26Z"
    mac: ENC[AES256_GCM,data:T7XHgWYmueP8ZTU+pRZbK7yg/2Q2EtMGgxVFQ/waaW8DjUBpYjDTXJ+7NSrrNdbc5aGCzugwPAG7aDt6jHSoM6j9YnbbdcH8pgf1ACwBNKs69+oZ0cPeSkVpddoarHuFtBV9QlB+5S+GFD49Ey1r0rZfo6c2vJ9J+n+/LJ3sQhE=,iv:uVUIv3nrdDJZw+yAZXdBo0/f5b5MqYv12RrneaYbC/Q=,tag:Dlay1jXR3dW2HEgmgs3fyQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
