apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FTWIYSEkAniHKbE/,iv:qYdX2uDZM/9s+X5hgdWWOs73KEzb9bLkDzrdJaPJwIQ=,tag:6/jhgckMCFncVS2Ia8Il3g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY0JBL0hyZHQvYk9oN1NT
            OTVkR2ZVOEpEZkUzbm1WdnExdVljZFA3VFd3Cnl1OGFpYTdEeW05eTJiRmI0VlBX
            eVBFN0dwTEVBdkxFbmVaK3YvN2Z5Y2sKLS0tIG5MaEkrRjdVQS8vcW1ITUJqZllU
            T2ZpT2FZL1o0S1lOZFFNMnk3Q04rbUEKetjHeIr2u7Jg9CbsJPXk2RF0yK9lWJoU
            xg+WVljpUfJ5qczb+wBExNXcylSIK8dy9s7NZDnnqnnHlxsYyAqF7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T16:06:21Z"
    mac: ENC[AES256_GCM,data:SCUmKMCBqPptXw2l3pBC+KSMaH8FK581mdCe24eXXsUx6k7Rwt5ecnpquVgW0Kn+EsULb6DaemhJN5ebafuKTR1P/4X3xGaz22OF8+76AoiQrmeARqP1VhjXVuxL94fbQeqXHYSCAJkTojj9ped4e2AUqKRmrwxVBsc/wZW3gg4=,iv:oMu7XL256TibWer/YJXOMjMJm0wt6nMI16ZqQg1F03k=,tag:8ZuhHIlrh/H1kID8Tjz6HA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
