apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:jtI7QGeRldXqDZuW,iv:vY9bBD82HwUwn1+N7W2jfh0KXXTxoVhtvuoc3dkoMmw=,tag:6PLAf3ct4nF1JgBOivlCTg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV2JvY2JPTDQ2TVlUMUhY
            VVg1S2FwaS8vTjdXOWxCVmxoa0VObjI2RlFFCkNaaGxVSU1hK0haL2Y0TzNNWklx
            dWlaNFJRMU5scmdUZDVIZ213em1ZRkEKLS0tIFNjNUFOanVtM3RMVDZhYzMrSnA2
            ZW1Ka2dVeXNtNm0vVGdMWExwVVR5V2MK3gofrhnDhhKYQ2valF0JK6h5c9eZ8v/3
            UV5cdfb36Mggt51Xc31TUYPCHLUSb0O6seTtZ3yfEVEbkMl9eCAr1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T05:54:48Z"
    mac: ENC[AES256_GCM,data:YzZHIaIdHCzDs3ArcW2brlTXMyLGHmmoadVhc+iT+rWL/td66gJ1LO/mglyKyCoPr/iihLO2qEVwPAUKQNyzgdV2mqmElwkKbj0oT6o88GygGUICFFSdnDd5XkdldG3TfRMCIlF3ennEHfqGDvvNoI3tbRO2RhAbU4a0YgC1yFk=,iv:7AjucFKkArSKdv/i3dFlzJ0y6EpjEEsTA9cp/0JIyy4=,tag:Uf+iEQXYvQGrMq5StQ0SSA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
