apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DsT9kcsVqdWete2B,iv:mouCz0GZW6PZKgPZcLubu7Rh7li7xfL4G5aWcTny5EA=,tag:Aq7Yi9hI7eQVdkrPTRltjA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NjVBOElyVW1FV1RySndn
            Y0N0SkNEM20rT0RweDAyZDI2UmxYem5SZEdVCjlmQUtYY05MWU92MDdYUUZSQmpw
            QUVEUkQzWjUvUVV4WWV1VDdoaDIzdjgKLS0tIFJkcjV1K0E0elV6V1diaFpLRnU5
            SzBlK0trNyt5bGQ5Vy9GZ1M1MmJxUFEK9YhKrKbhO0CHmaN4MAO2SOqf9+0JIeM0
            tBUn9br4Ijwqg7SyJobOm9SGa2Vmtjjv183o9lXRnYz4kQB6kZkFqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T18:06:51Z"
    mac: ENC[AES256_GCM,data:26TqXGbhgxDGN3PLhJqGZqEWDURRvUTXrSpekBtksKgnWumirUv3tblrB1F6rnIvzKnOvI+zA7MmY3Ntb1xn8auxOAaz0YPfjv9S99Hwk7FPDUcc96oGoyAZ7UTDbRSGGga5MTxpSAyQ6l5+2kO9EULrIBTVlIfunddRyvodMF0=,iv:roboi4JoWKjkvGEtwdsNoaipeG871ku/L2H7jGQA7sE=,tag:9H9c6Ui8GFov4+Euyul6Zg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
