apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:U3VTn5V8GY89/wY1,iv:kUfVUXVCy4lUr64W/R2wUAj1j6VB5bfblzsoDtUEP2U=,tag:TSteDAJwbMcmAbENcKk0UQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZkwyWDBOK3lUbEd3TUxs
            VUdkb3NqR2d3TForN2UzZ1pGVlBsS0JPQmswCmxCLytCdzFTVjZoTXdUdzFTbjNk
            aFNiRUhmVzlicmhsYjJSdldsT2ZRaWcKLS0tIGdiUUVmWm12Q1hpbUdtN2pzcDBN
            Rkw3Uk1zaU5OaVdROGkrb2dvQ1BQY2cKssy+8jnCqzHATcsDgTd0LgbXlJOBisJc
            n4LqLCbxieRoBWrS6Ikna2MO0RgEP3v/r80ui3D4ozySOATk4edkuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T18:28:25Z"
    mac: ENC[AES256_GCM,data:Kh+51NYINhH4WcUvHx2iQjEDFOnuEnrcZyRyuRZ0I4Co3K2zRp6mXI4s6yNu9WbrlLywmHeBQsM5vW1wMuuakBk8vaXHZWp2w11tRETZzhQl8r9LJJItEmdoZST+VQW3mGMx6neAU71e5ehdIgZt0qNjakjOZn+6AjEuwBBKyo4=,iv:ZaVrSv02sDRuqF1ZSLLLjPGW5sIsYaYWx10qw6Noo10=,tag:KHB79mVXfOm/Qb16YSC58g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
