apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DsgABYM2p/qSza9P,iv:tYrDXmBCup+JgB0Vjue0PQPUm5qZSIMVdR8DsLZGvoo=,tag:7vYEKNMqzNC+wwzF8FoUkg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY01adzJCaHpWOHdHenBX
            elJxdzBHRTlBYTNwRXFRZE90dWNnZDFuREc4CkdNWXVVQVVoVzdUdFdSbEhpRlFh
            NEFtdG1pcDNRcndnQ3U0eEdaa1RVZ2cKLS0tIGdhREs3R0hvdEx3VTdwZGNXN01S
            Um04enRCL0dUMDE4YkdqVjNpd1pjNDAKoBtRYNFrts+XtTztfuTolUumD2MOXWsp
            P53J2Cy36hKx/lFvr9f/oePM7RDoKXZ5lJBuFRaAdENhOjQ7k/HgHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T19:25:40Z"
    mac: ENC[AES256_GCM,data:9DGEqMMmZNgyn+wCOF8wyeP0HkV4lpf7C46joMPRIhlDxgN75J5kHRnPRkOhY78HgZX6T09Y3j9+CPjM5T716D2R21GMItsLe2YJ6dwgPBzrCyPg6Lh9IkIJY8sn5L5lhwHL4/8JUgrfpRr+zbIIB++tQuH4LzbloU52RIr68Xg=,iv:mNa+H2iobuuoFwb0wm2k16eqYsJ4v+5ZZAE5VkRvM3k=,tag:1xcGqitlLtuvcpbOMEbXSg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
