apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qUr6rydZoDr75xGC,iv:bCv4hL3jwAkzlI65yfcf5r87HwS4kcC/brsjhJYd9hQ=,tag:uRTaOdmQucuV0ZcT/+LAYA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOFZzOVJzMTl6ZUhxNVhz
            SC9SUDVkNmt1dXdqZjdSdVhGbVFzc0k1UzFRCjkrTzV3Tk9qVUNoNDRuLzl3WkR0
            bFI0SU1vZ1pVUUtDZXcvYWdDTS83Mm8KLS0tIEg1OG5wclhmSU9ESm5Uc0xZUjJj
            L2pzaVBHZUZ0LzgrUTdKNnBPUGxTYVkKGAaiuC8NR3UdNU/3tLC+EGuR7oiHmpa7
            /X41B68H8oqHK9WebXu1qyJoir37BCQdrtcfb1qSjl1Z6v8nIX7+VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:00:42Z"
    mac: ENC[AES256_GCM,data:F4c0KQRPcX5Pjet8Hekd0UaVLttU5k5Ke6qjCGG2/z5StmY9Yw1iC2deXD0LcV5AkLpvH+CwbVTxoZgfdeV9YBExrCvfwP64ptYuOBo3xR0QQ4vqGsFr2iDlKW8oOxXTn3fR3trJ9SB7CSLdsyu2A+cf1bmzoDzVr4RsPuGSlxs=,iv:FKxbHm9gnMjaA6j+UcCafaQyqW6Xbm1qwpupnN1jebQ=,tag:T4YoUh1MOMrUUzsO1jC1vg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
