apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9h6Iy1OLflVB6VcR,iv:gIxTRuFggHsq+XM7+S83j3iOtzcB49WaWD9fbYZnGlA=,tag:bXleCnqErhGT8hrcHMZE9A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUakVhL3lYVTk0T0x5TUdo
            K1FVUjA2U3prdDVOTnlvMHBMeUFkWmF5VlhNCi9kOXp3RmFzK3ZQeHFzd2ZEcUxJ
            ZUd1M0xJNVFLN285WUI4d3AzTXBJRm8KLS0tIHUwNE1lYjdWUXRtS3FEYXp1ZW5q
            WHhTR1J0MkJHeVl3YllCbWlHdW13U1EKVLL/BotaNZRqvSWo94xi7bUKQxRUNTc9
            +a6+HZS0KueULZQ9yKZGLBYeyiHMQpL7IYMq4XiZHU+M0nx2+TIIMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T15:33:33Z"
    mac: ENC[AES256_GCM,data:ubSd3T57oXaDElR9cpkqQ2A5FjTrfKds8+Htxzoo7Q9DAei8j13jKPNEIQmlq9oIXUmy0lLb+/aKPKJj5W7CArr58XzoP5JR/pRXoH86e8TTbsVDJu7lK2jjsbUjE8IIZkJGpbP3NlYntte1Pr8BgC4rzl0+rkcnpJCvRUjtJow=,iv:Q5il5uDZx5/9cnde1q+ugDZbiA4fgdxo/xcwju81IKM=,tag:bEJrLmLqQE7MqwKJRlOSIg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
