apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:wDa5wcfAHrcMrCvz,iv:YqanqZI2AJXRGFHZXzZw8V76TT5vwhxAHjwh+uglTok=,tag:LjByDG20sloY7egTzphbAw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRzdOTFJVcGpNaTR6bVVn
            Y3BLMDJPUDdGWU5Vb3F0cXU0VXpVa2tZZWdBCkhiV0N2YVlOdi9JeTlkeWp4QVpR
            bm5YY3R3ZVZTSTBGY1VESEJHeHlhSVUKLS0tIFlDaU1ESTIyZnJ4aUMrd2h1aDZD
            MGtvWUJCbEJySmdia05FajRvb3RxamsKSV8jZAs73j5fsPaeZKJ9MABpcBDX9GHA
            WxM0LiZXM0Y1PcBLSvknlubmiGc07Qsld7dQMdE2hgSZZ01URAMh4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:17:22Z"
    mac: ENC[AES256_GCM,data:9jQJbnQL2tu9DhpRCO1mSjx2AyEfb+2yP16EYHoJuj2OaHdes60tCPrHJBm+81eOj0MUk4In2ORPqFLn2C72rc2ODJQJ3L9CAGzSXDim4wyBdWivjSHfGbQqBAsHNcuxD+90eJ6ybiwy417MDX4fWHNAPdn8Px4zGLojugF4teE=,iv:B3jJgDspJK49voZhSm/btjP8/atIKUVSLY6mbPC09vY=,tag:0YgGTl36fihPtw1kf4kguw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
