apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8IZNxJfxztlSVfIR,iv:bW+0wCq4SB7YKR1mK3chKXx9O7VFv54rzInZds/vcCo=,tag:doKRoGerqScp5b0jPgwlPw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNGxaZXI4NTYzdlVzY2kz
            NjRNY3Y3bFpzSlB4bHBBMzdLKzNHYTE4UmlnCkpJdEtUeE5QR1pRUzJsS1pWZjJT
            U1EvcWZISGRJUE5WNDZWQUNGbUY3dGMKLS0tIFRBWFl3ZEhTNlpvV1ZuWERQcHBI
            bitWTkJnalNjdzdIcldBM2dMbllDSjQKt6uNUwmsXaFmtJw0jpQo5wuy5NC4QhPK
            A3tdlYHdceWlud8sAzwRGlqnH4QRvXhEknrF9pFMyAAZqBvSP07/xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T06:00:55Z"
    mac: ENC[AES256_GCM,data:/YSxqE+0A4r6tD0fPu5Z0Q4Ik9NPrypmJwF8bQyJATEklFw3QMMbNZEkQsdQUwg1ft50OO4xoOX9S6FxtEmi5YI4vgt8V9bGKZZ9efnz7hkVM5FlGg8yVfbBPBbJqvb1o4DN+83GJXYNP7d7yX8O05GQqlNwfMTiGmP7ipjdcu0=,iv:qbmx6WxIdBUDoy+opJHk4SBDlKlMDCKa7s3NXV8Lsuw=,tag:1nJwSMitOhf48bqJ2zzugg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
