# provider.yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-provider
  namespace: flux-system
spec:
  type: discord
  address: "${discordwebhook}"  # Reference the placeholder for SOPS decryption
  username: "Flux Notifications"
