apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:muyoI5/zMU9TRQoQvDJWrISh05pN5fJjqEbKMWieqcIzrj77dUTIQwmQRFi0rVWo12RqaG9vuGwvfRRJ/3QgG7er7fXBkY3jwao=,iv:C23HljiE6wIhasZrYetV+p0iDuP3svaKXmrLCBdlukg=,tag:EhLomf4Jl0Joo2MJWlPkGQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUDE1U095UUprenhSSVZG
            K2ZpV2VxWFB3Nkt3bmRIL1hQdDV2MVhlOERnCll1N1lFSGFES3RSZElQTGNwcWFS
            dy9HdXNSR016QXNyd3VLS1N3bDV1dEUKLS0tIGUvZ25BbWJxdFNyZFZmOHRQdHlZ
            aVI1N0hmSE1nakR1MTJuR0d0UTBUdUEKfltWuVj9pT1S1x/rqU1u6TBoFlWTCq/9
            E2Ty2Dh/DHkHarkV4+RMeM5vD9t24XY8AoGITcygrBk938anlXNmRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T23:06:16Z"
    mac: ENC[AES256_GCM,data:AIf4aNYEQLMVDGCF+Z7bYd6GXDoq2u6DvueP0bXruuBSAxnbEG7lO4Eo59OeMQXVd5Nop/gneU8YCy+bjdyPhgbHlcOS7/0trXPQFdk6T01kgYwtAnpJdhMckvP5V0TplpA2yugUtMwdixiRfakA1CXwfK7b6C3cWDkWharj72g=,iv:BB/kkPgGyls9nscjb249tL6H/lYiCCG5FYrDfkJ/Prw=,tag:iRHCITFyx4DGaJg4lFUz8g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
