apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:tfHYErjuTDYKnik0oz/gYRx3pd0hbYnTjn6ah/hiEAug5mfk8cTJBGIiR8uc5njJg7vf4WnDkfNOpvcB06JA8kXFOzZYRb2Ln7E=,iv:/CyTDh2uzv4x+UWYU94AlablOPkEbJgQ/Jh4TEA4vmk=,tag:VUkWwwQjIhIELQmEZRLEiQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQjFJL1RrS1NUd2lLRlNq
            U3A0eUJ2WnBXWVcwY0pNT1hKRmJhbUVNVXk4CjlvdGUxOS9HQkh4M3VNY0p5Rlls
            cWJ1cnRjZFlFbUw3Q3kxcXBXV1hzbDQKLS0tIDRudUxFUzhIZnl0Z1VJcVRIdzFN
            U2thajIwNTlJU2NzcWhDcThOMmtjamsKMM9BZRqwonAdKW/AG1+A6j5toHv5jzP/
            Cj7zBYwIVW05/r4DlUGBrh9GDdemg+O7xdN1CL1zuwVugwx/S5IZSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:00:42Z"
    mac: ENC[AES256_GCM,data:/AS9GGtLsPzwLkuGFvw4dYCKIL+XjhRQ5xYjW1GocDU2wa8/qIDt5AHCkU8SV5mxPt67ErDacokfrEdpY8E3lSoHC4K4d8i2+GBf7q0mdgMU+6Li0PHppNZOiMMDniDPeP/nKo1JY0NqXY9pM1CD7hibg788GzmjUIZVcNTyFu8=,iv:WdIe21VsMtDApkcIWbuxlnyuvGkJWaGaxIV0ZEpjUa4=,tag:hjoDABZCxJBcWjW5xIEdEA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
