apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:FZCzs97W6HwLlCWuetGhrbfLokk97jlTvMloTw4j6Yk7KCOh0y06ud1M/vNHByVK5yXsWunbooMuBF6Gzq7rX/Emhu57q6XA+T4=,iv:oqcTDXPUT4hNWazUSwzebCrPs+Va3U8DIwOcGDQKhD4=,tag:/Xrvrn2ky3H606cDxZkOnA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZG1VbUhxNVh1bGtxdXFS
            UUVVTE9MNitPVEVNMm51L1BpZkF4L0pHYzFRCktNQ2xrUlNraVNJYXVVdFpSblIy
            TmVrOTlzeVFzc1BsRzdCVEdOOGVRVkUKLS0tIDg2aVZBbW5rZlZYOFhOUVhCQmRv
            OVlLZW5uNjQ3L3NsU1krbjVnYVhNbUUKE7d+kDUaaCq8oYngYz/btVNCXRE4XRrJ
            rLXgeKzwko5ppSBTm7YsO1x8eLkQNue6Ol9UAExg+pIVNetSjPVW3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T18:28:40Z"
    mac: ENC[AES256_GCM,data:fWH9gnz+jFn4c3wInbIsS+vEOW8IBtE5FIMGQ4LGRBqhMz1gKCYGIp8mkTEYMorB7du4QD6dpbWsh70kcTWVfkHqDQ0yYRUx+FCjMKs0vYiWIyQhlhrEDT0jUwq8DBW1Ljg4jQFzOcVYmfOcyWO7x+eTGkxvSieqh86JwT422iM=,iv:s7XfWDrwxVI5W254Vbz2/Yo6EFmQ9Ll93smiPY0bNwY=,tag:lnuohSDTLizLyNDXr5tbow==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
