apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:s3+0sT9KSQ8gjyTKSz4C+1HzA65nfyxnjHyUT6j0gHVbBqUfYYUTWMtm0So9f0w2dQc1mMZGCW+o3HNUyYeT+ABhJFFz8nUs+jw=,iv:/AfNfSfMlC9DN0ZECnYKJsPIql8kdEnRddLhixzYdmA=,tag:tGlhWwjOgkdM7qZn8Ty9bQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvM0xNc2Z0bENIcUZZb3VV
            N3JVMFZSTnBmWXhWRDkxbXVFZWZPb2VCUGwwCnVQUmVTZHZROHU0MWZBalVXRFRr
            bDhLN3dVSWtMSmVNcU4yY213aHE4VDgKLS0tIE5CVUdUK2UvMFRZMW10OGR1RllV
            QzBZcGg4c3ZRZWhzRk44bWE4aTNVSncKLFcCY9GmlR/6YeVNQzH97HPsghOxYIBK
            NwdK8wRi3264TTWFYpXBoLOxieUec+NENAay2uVYH5VwCtAQFzoP/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T20:47:31Z"
    mac: ENC[AES256_GCM,data:TrVy8Zd8V/xBSg7n7UzBcpMnwxFia/0yLjFv0LKaHI7PuOG7ARnNHASlddYGlnyzTfB6wQNfY+3ICX7RqsvwwNnMtEQ+sdDCk/DYL3cA0/eYCOp2JMGP7Fg6ENVISHwcaRLY4PNyu3P8cO6EN7Tzt+nzPjgyznkIWnCLmsgjCBU=,iv:0Jes+qStKy4RHb25KBdCqumX3G5iTIyDgC+ws5gK1NQ=,tag:RqoAMJ3qlWkAYiVAlEXG2Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
