apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:+UF5pchkVG2ZPpinBBuvLdITKpTTVYbFQShUUHvON3wzAH7qXHLpGG68lggOAFwmSIQ9c0QuujspYYtnmcuZxqPPMT5tuw4GLiU=,iv:stW0rKy5Mu+u/Fg2Wycg6aM0vGWmMvOC6bKZkEDHElE=,tag:Um2fjhdLTAFajovavXXGQg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRlAxMWIxVTlGbmxWTVdu
            NC9MVXdlUWx4WDl4OUJmK0h2eDJuTkxGY2drCmlxRlliaGFLMjlIQUc0c1RMVnJ5
            SDQreFd4L05qYVhwNXZQQ1FwTlN6UU0KLS0tIC93dVRQR2F2Y2pka29xOStpVjRG
            aDdJTnBVYisxaEFMYlhHNVhkWjVLemsKvK65mb9nAuDLn6dIUfNk+2wZiMgx2K/S
            pIg5RI0MiVN2KlJQYebhPvxvFK7mRo1L7CU7JeaAZxNlAhPwSX+MpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T23:38:18Z"
    mac: ENC[AES256_GCM,data:3QBIE7kDhLKWYsBO5/u9aDF5xbNyYBEGTJpSWLnix1Hg0xgXZ6DJIS8zBmQ2cMBobV8TUHc960tpMa5f2rwqEfTdO/AoPmXrO894nRnZoktZ8Ei/Yexxomr8RcdpqdtxC0sfiFZqg0RxZmKjQisFNjKWEnEpQulqGCybC6QEUKo=,iv:IoADyLL1t8/+X/Cr0U4wwEnew3fFKb9ghhtVDhLl19Y=,tag:xufbTk5B3UZ4oAc8vc6d0g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
