apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:NCCrN2PX36Eqi8Hj5kNQYqmfRaDEfR/Y9Mr9/PsWbPxyeqtwf1hRUStH1htkYsv3HUIX4IPQQy/zw0fi070FPLRo64WFIOe92SM=,iv:uBhVnmNd7GYoBkE8I1KvG2WLWZoyKMWbP56kzme9OWs=,tag:otMqgR9p8M56GvOp9tV2jA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVldhL2s2T1B3dTFWN3cw
            UURUS0ZNNlYvOTU0aStsa3lOT1BORXNrcng4Cit1QUpBamlrUXNSN0ppbHpzb1M2
            blZyOVdTMFZFWUFKaUJBbHp0emVQSXMKLS0tIDhIUk1QcExwSmtHWGxrMUVlNEsw
            cXhUWGk2aDhyUHNPVDhSWTBOUmRkNkEKFaZlMDWr2/R84afOh3nBieZ+11oqj2+e
            u7VBFt3F0zIuKOAlopIfgDIVDJIYjIcWf58Jw5ayAkMRemT6cebi9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T19:10:38Z"
    mac: ENC[AES256_GCM,data:FwWC94hk3DQZPlkE+f/FlEX3pQLZwfwlSp4uiRQrlq8wF67qefe7gq1BBoi7gsFCclDoVWGiVa9p7Dw7s9xvcGvZrzQrZqg0iBsxVzIKac4j1xRP8NOC0GXzJmPa4H1B6Qx/TSGz82Xl1iMd/1E750Uwxn33ENwn2lGPeLb1v4Q=,iv:GhEfhvXEQzP7oyJ+uXPupmleBrto3eBDhXE03UGrfgI=,tag:+s1DzoMqxjij9HggdDm/Dw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
