apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:Wcf83sA+5LOBOe3OfjlkUAIboah6Jc7F4AQrZ/FvwCMCfzwEUE+41yultQHSBskJDHXamxMiNJsZWpRbuWaW1l+6X/F8gGC5mfI=,iv:aki0Nj6PnImo0S1BJ17+s5YsNSMipdOC6k2hCK6hXOk=,tag:ozk2dxFL14I0xk3IFloFoA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSlNGdExCNlVMUHN0cXht
            YUpQeEdqbnNuQnFHcHJLcm1FNkowSXBsUjNvCklOL3psQUhnWXkvamlTSHdkV1Aw
            R0JKanhTNkgrVXZlYVl1Q09scHUycVUKLS0tIGFWNDNOckhCNDR2dVlyMEMxYnlD
            SHl2OVRvaXdRRkp3enVDUU1Fa1hJKzAK/j7G/3ZIukNuUrHfpfbaP8AjP/4IRt4e
            ZZJ4iPzStQmsLpCuEzc2sSeZOJ78O3Uc+Tk23GSUGf32hVnR/iR+bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T23:33:55Z"
    mac: ENC[AES256_GCM,data:Q/iZDjio0u9ReO321yYPFVCnxmm6FdRbItojUuwc4c5x5x4NrYbNgxe4nGecHGAeTqDcPENT5F8c+maHqMZWbx+DCfuYXCpPYQZrgKnvCaaCiOXIoPsunhZxIkoCst4qJzIVNFwdHBLUf9AHAhCkvfcKSWV+Pcm9/R8J1UWg7bo=,iv:opn3/YaUumRDZWYulaR2Jg1Eh2SqDJoKaYQnyu3ppK0=,tag:9nluJ1KRynIL0jzGQQlY1w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
