apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:+dwaiIPyAD9HF5HGA2kja0JxEc7yKnpi+GIHEemfaoL/Hm5iN2j0cDKupQl+qvNb+ODEMRaFosZL4Q3/Mu17UMGLdNlF9njFscA=,iv:cxeDk8PMs2pDuD/rbHRIMAD85mYxS2abw/FMInL6T58=,tag:PZzWJBu20DRAYq7IutfaHQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMG1LdXg0NnBSMEVNcjRC
            VkFmZVlOVDkxV2JkakhxQUcyR0piMzFMdDIwCmI3OXRzdHpYTU1QeUZ1aEZjc212
            VzZhR283ZnVLSW9wczJENTdBNzgxUEUKLS0tIC9tS3FheDNTTUE1bXBCRjVWYWsz
            WjRzU2d0Rmw4MS9ONURCR0F5ZUdjbzAKtXxpTFc7F3K3tE7ZX3S4jLOMX8zlAvUQ
            RGB5PrkvqtXrNtPnOR15rvDH3vcpbq2SSRJUXmSogpXuO/clj0Avcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T15:46:33Z"
    mac: ENC[AES256_GCM,data:fx0BQBqnk4bIdWNgK45zLsS2OmbpeLE8W+aTVsPpp4rjkEfi8KBDwk45fRjQ8ueY8DgvxZSabH2w+kDOlc4TNo7qPkYp9u9VztOFXZ5tmBeJDIXXNgb0D6vKIeDi4lIW/WQqh8+TAH2AMvNGaNYSY3dYkqg3dCsl393JUxB/CJY=,iv:9UCBfbnSwwM3CuP6u1rcpDQkk+wzEcCamuXo8x9unx0=,tag:QSZqeLuNNZqa6ka0Km/4gg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
