apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:Okxn3DQReFCNW6WLZZPIL7w9paDx7ocL4ZaH3guPUFMT63vbOCySCpUpQznLFrniTg2JoPzOCYnoJ78mW5lVFudkaIk0g1aapOs=,iv:SRTffSnrjF93WF+Fd2fYTlczVHuMLyXY+B8kJhr6LRk=,tag:pIT9OjYD0Nbh9N7xCF05nQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V3JHa3VZVVFTRW91VkdE
            a1JuM3BCaDFwWWhEY3NYdU5kUmJaOHZvdFZvCjc3R2w4aS9zcmpsUHR0VmVDbCsz
            amJSK3lvVUxEYVNER3pwUS9TRmNzOXMKLS0tIHZWYklScWFnTnk1VjE0c2drUktS
            ckV1cGVSaUxBZko5RnRDUkpCN0p4ZG8Kq6m0365yj8JTrY4c9wuwpTxO9vrDbUbK
            eHFLvZuksLOAO7FqdR/qt1PW95CbWnJWTbVoWb3aVwnj4Bl2tvsgCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T15:32:11Z"
    mac: ENC[AES256_GCM,data:EM5r2gcuI2vYe0XIIo5cgQx6SBz7aYRPWII/G+wnnhhSoUZu6TW2AMMcUhzlm8A7D9M6EiMO2EL2iMFXW5dH0F+k1VnF3p9D1DaPEOA8+Ied4F4RrKAg5Z8bORk06vzwOEwlra5hFDiXyFtudyxFtX+OY0tpYIVc3t66Xa4qpF8=,iv:0GIYxMDa2L8g4Y4D8+Qrh5skcu+fOsFpfHmat5u5/IQ=,tag:UamtGQb+wsq36N5GphH0QQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
