apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:IKakBYFfg0fnecivh3WXQAidmgoNcmkDypkQH2+1PzSvNpZzH2IL/Znu+lcVYpdVKI3IMM//KX9XZaMnUELn9le5Su3y1F25CF4=,iv:xL+IbqM0tZuoh1MCF6cDV+FiZ78ZQPC/iRXsfXYLyDU=,tag:4uNkMi5XtKAVLPFzeeEzzA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeEJvNjkwK0g1V2FaSEtq
            MURCUXR1dVlYTi93ODltYnFkSHBGZ1IvaFY0CjIwZm9kTXJTTk1hYW8yT2VwSTdS
            d3dvQU1JWlJxT241cGhYMFVjbWlmOTgKLS0tIE5MaFl3Y0FTOWlvMlc3dVlsRUgv
            YmZTS1p4N3NoMUt6bERaaFFoU0xueHcKGd2GuE81jrqRc1bDFd9MID2oVLLopfnA
            GEUmuNNfi5OazIDW1vGYwvQk4G7ZVog6isk2ChTdlkLv8WkL+Lzx9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-02T22:25:55Z"
    mac: ENC[AES256_GCM,data:l7SchJq1aATF5gsWeHfD0CmMvs4ujhH19/Ar8G6P+bfiVsFtNKJyRb2NwhnWbM9q1lA/qtfbMdn64iqTaN/sqkCXjZAFIxroSvPe8/0yzZDpJMZEWzSJijjY0AfilpNcOQbDcvtN9ff3wsTFZcyewmxzjZpOMY/7vrdGI2W/AaY=,iv:rP3geq5Fk7CB3KAuHfJJdYth09Ed4L37dfRZiblMbuo=,tag:da5Ouwe4dnqifA2PHbfSzw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
