apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:oAgcNd1KZ5AUhMnMfqVau0pxOLOc8JYdMUQ66vm8RUyPY/Rbb0G8gnnv9qJvmZikKpJEgJpXjRJykpStKYxWqbWaY/jpGtdAGzE=,iv:vknF68XFY3/+UVsG63k2hZLFYBuoDpNMuZAnqb6A9nY=,tag:7iMBRNQ+QXNCdwTSJQ+bKw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheVBSOEFYdURUTzJtZ0Rh
            RmJnbUtVV2JESU5oRTVsdCswbTIxOENEKzA4Cm03TmMrS2lQQndRU1RIUThaaCt2
            cE04OFQ2VEFFNmNjQUFYMGVXUjdzOXcKLS0tIGlPVy8yblpLOHpNcTlKVXUwczFp
            WnErNVBhbFFyY0hISWhLd2xNUnNqRFUK+VqV7FAz3p+bxzxuS2wGzHMeP+FpxDjt
            oHBJixhgPHz1y/9aqxSVlc6EB3NC3e8CJbwc5ODQ2ZGrrNU9EfXNMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T14:25:05Z"
    mac: ENC[AES256_GCM,data:LnxdiGvhUuAd5ZfqUcw4QuET1S2DZrmRfTDUHAd8p2kjwDx9tLLSDzpTRkYmUavF2/zAwHN3rcK07OJBQ7CC+sWyQQ0p6MBNjVM26/l3puG5hVlH+PUrPVKYNatz22Z5HK0ruhyyySFAWwDSSFf6lh1+cRArlP616Hh+3xD1fr8=,iv:UB5ai+MqTZZaHq27JSYvMCuIfm/jkhpskAmNeh0yxhM=,tag:Aua9QVzZaGkMYIgtr9WBOw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
