apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:Xpa/auELWNnulaAQzeycHvNUBE8SXWgjUkHYoTyNgQLkOIxicvQNZKRjJVelpgg5Tc1LTQfnE1RGeCGTGwGeflvwLJPQTlhn3kY=,iv:ricSKebBw/Nxyd2AZvaODjjT6RZaaB4waxZlawt7nU4=,tag:CIzGkf8V0Ikxr0soRPgKYQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VUpuNHAvZXdnbU04d0JW
            d2tLejl0YkIwQkJtQ3pHQW5pallhaXpxcWo4CkVrWEdtSklHSitvNHkyeldwUVE3
            Qk1ONlliUmwvSm5FbEl4c1dkdkEyUjgKLS0tIDBCL2haR1FVWWpBcHpzZlpkdHRo
            REl3UnhrbDFZOUpTaW14djUyU0ZrSUEKi/YN6kezVgWtzZywTf2aM2Cidw0LzVTT
            P7YZd1D2WLL1I38XiwOjSioWr1t6cy48TqQ545D6Kake8JcLEksC/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-29T15:44:33Z"
    mac: ENC[AES256_GCM,data:h3KqJP2jUo/mR3nxDzb4qCTNvjW4wq4vn/GNvdva9f5uHRIvPOe+HRLwHCKdBLYpgBuyL2pulamU1e8x3RR9BRoQquleG48pzhhCY38eKdmvFINmNFxGoR98TWNdHJXLvVsOGiTgMZFKh7y75gT+D+QD6GR52yvdtVlUNIGanhk=,iv:t97FRau3KMrCDYAbRdEy2PjUg3DCwFyNYYB14EJBQH4=,tag:o+7di6R0k3aS7rTEIc6++Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
