apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:sqTYKqZVOJP04pbPFtk6135HOq7lNDzFPwgHHGwFsescUoTm3HzxuvWzkm0o54kSJOfIGSti3Mgbq8rjh0Dg1Kb5tqvcZIdkups=,iv:0ghtHHwjbUliPBs22vy8uJl5Nxit5pPckUFcTfFYUYk=,tag:IRqnK9NBztOrYCzQWiZMjw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraTI5WHhVckpjSE1zdlBM
            MVlHY3ArQW85Z29uK2VaeU5GbWpJVWs2ZFNjClU3MEZEWmRrUlRQTmZQYTlyVS9R
            dGx1bjZJSjlOSUZiMUhPYnBFZmE4K28KLS0tIC9xaWluZHZrTnB2MDhXeHlmWVJI
            M1hSbFNqak1qdU1GbVJ3QVY1LzZ0TUUKjAgnIHmJyZgfllGEtUWB46uZRQvkR4C3
            w3W5h+qYeI1cID+vxl4ZYIOgsjBDN7HKJD67dKPz6LJUZtfVCXVBBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T07:30:51Z"
    mac: ENC[AES256_GCM,data:hyKeKmV2vkzq9z87OqZqYx2ypugpceQ228euNu36/lrg09+wst4alxv1iWtZdPNboRmcr7mODaJyZYa6NHk9mUAQIQCar+3zgwMiALgAfsR6zZ0s0cKlMKvrvCGNJaFSOeZK5OiOO9SHKxbZGlTOLUYD/pw9nd+WUPwVZTkKfdw=,iv:VufwYZOxs7inUYo1h+kmCtEGGHimDUBVoJReCcRzSwc=,tag:+48VCSTt00LwI1SPTUJspg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
