apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:eOJb/8eCoq3qlJ88B7MVMFMh4HyLA9oYtQ3HXxLPHoJlx/c3KANwkQzIzQmKhdXpA9jEPcP5hyUrs6qMpUK6/UlfKUNQQu0VA1Q=,iv:L63dXHiydbulCsqCv0buOYtBrJpQhe9meG5uLp/1wug=,tag:cQzwHy91+p6qelRStmHI9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV1dEOWNuYkkxMlJjbEha
            V3hrR2tVb3I5NC9YMzFXYXh5VXlsbWIvV2pVCjlIc0Exb2NjYjVoSXdOQ2ZidHBk
            MkUwQ2ZOaENmbEp0RVpGVHJaTGg2QjQKLS0tIHJCM0pic1RrQnFsS1hKWG9xaWhO
            dXJhcC9tb1NSaGJkdm1VYjM2RlNUOEEKl3IL2IQBTb7OUgo39DT9h5H+lDbS7ECY
            Xuy9ldDoRU6VMpq+Mj8x2ifINvSCQjmUzLucqQXmED0Q0n8hjxEWCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T16:42:42Z"
    mac: ENC[AES256_GCM,data:+EZn/IkmsbGE8msqaj4xGkggDE/RT1cqzrUf8lhAAQISVhfENvaek2rv9FxAKvGmyash9deeEiL913k7mm/tm0vblIbHF5tTrwRvk9Qoj/BCxYB9+uIVcMkhr7jDsCHfj44Bni+Yx5dSJQbH4Fz+6R5oyokQHyzMeSNNihVtEjE=,iv:o4PRj6azJUtVs/xl0EyLKtwdlrp4Qi7kCiy646AvNV8=,tag:O+3ZIbpwUOY+7Xectc3C9g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
