apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:RclcQCOvFHCNmnFuCYH/G9ey9+1xGXAV4fpjmV01Zx7PZGSi8dzl6t4br7wAymZ+CT1hulhH02yqFx87nctBwQ1wLSVI9UNCmQ4=,iv:4cXLG3bOTBAwmzl2MogW5mKYAdZqIyXM9HlsE16Jfsg=,tag:s0w+XkGevnmdiGqXOi7opg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TTRPZW5DWlNSNWE5ZW9Q
            cjhPRFVOc09VNUxnUUxrWTRGTUJhZ2grS2t3CmxOQWZ0K09kOW5tZlFNa29pQitG
            RjlCVGtrRGo1dlVQL3pBRzN0NEtwYkkKLS0tIEt5Um5EOUx6UEhKdVl0TUFVVlJS
            RWRKWXpoeXN6aXJkR1RvUG1tcFYralkKgST2riBRDNjK0MUUaYSjFeqXlGrH9GAp
            vuIOxPnk3GLrlbeM4qBqaYaf8KifCTI7Xz0QMsK29Itg44rrBd0lUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T18:06:51Z"
    mac: ENC[AES256_GCM,data:bgjHz2drdImLAiurJF41Lfh2+rod6WRtBs+rCYrxBL13jWICEqIrP4BjzdEOeHUzTfoLRMpZVJL/dY5rUfKj+r2CXWialvfCYEqM5HxLAAjRAtjox36wqDm/HHrf04U+3S78jL6r6NbUNgkdfZ5QRkMjCGFtygU6vOCuuCocDgY=,iv:7PLOx5GRbljVjwkDCz0gLlVquY6686+SdaCWAkBQhJo=,tag:S3Q78MetRYSUJK97ukHTDw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
