apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:0FK1Y3E62AnizE79AW+epGsszXLbEdTSa7UVpu04LtuqaxLoLmlCx8SNwls5qSvQVUR/xF2pTifnIto2s5A9kUETNTLLR36rnCQ=,iv:JJ8sg/6r1CgsqNbgtyUnK6SDs7HU3qn7CMtUT/oss4M=,tag:LEtNPSPywo8sBRQauSIeXw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVk5EZDhINGlVTWNJOEIy
            WWhmWUkveWIva0RQODhURE91Y1NLYis2dEFNCjVqOU9jUythVnl3ZTJXRHlCZ0Vu
            ckJQZFptUnFMdUFObTZwTWtoblNwelEKLS0tIHFDbEFqU1hEU2RQbElNSUZ4N0tQ
            NDF1YmE2MnJqY0NibjNpaWtuSmZyaDgK61Ik0TKqIhrFLmWDehkD6DdI913g6T7Z
            tpkbmYtjM03aV0vmzu1he9B6/4Pb2KfrL8IrgI+fusylo0GWRCVxeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T17:32:38Z"
    mac: ENC[AES256_GCM,data:eVQODx5JQHJWvSTOPsKDYUtjaokZYXxgXP54eZNjhTOVW3+koRDjaJLyCPq9Ioaprcpsbznu9VXu78GZ6ctQLZCIIEZ5bjtQtpgmTuLC4xsO1W4xzz/VuiafwOh3BMuYc+oSDOyMmiSMJ0pD2l4IHym0jKxkDunwmOgUrtQ2nxM=,iv:gwwhgVEeM5MDsbscynACbBPWTtiv1J1rg+mzu4B+WPo=,tag:Nhntf+X5hQkeB1aSAEZ1TQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
