apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:D/aw70QCBTn5N/JwymatCFdrGZQBTg9kMufLlga6fsxoyUvhT6J4zaLm5sokrUplTQuqtqXI7c1DFeH213Ig2ZRYjdJFpz1EUgU=,iv:CTRDkWGjVIqZ5ZCnYFEdRYU2V/H67k+oAOwMu2EdULE=,tag:EyOpFb9dp5LKGcnCzEn9Uw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWGJoSzBwa3FTYWtQa09R
            S3RENnp3a2FoeDhqSS9aMXZZR2dOKzRZU3djCkMrdmFVNEdyK3BJNkJ0MmU5UGIw
            MEhqWE1SSkF6cDM4TzNESUJEZ3RzblkKLS0tIGNNZ0ZGOUhFQ1dNYkxRS0RnTEpn
            ZWFJR1oyeTg4MjMyN3ZSQmoxWWlpV3cKJtsajGcu/L8VmLbxyd0eE/P7uBuMUIeH
            kBpli7FHX2SCKP2f3EiSLDXSaZZfA1CJQAb78mKH5Eb1mOgLxaqJKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T16:20:07Z"
    mac: ENC[AES256_GCM,data:70t45MLRsSA92PbLJXNwTRsi7VhRmzjLF5DyFTCBe7707K0bmuD7X+GDvX390OKENrmb8HGwP/+Vg4z1r2PWYzs7WA9o78jb3rUaanj/cTPqm6Zn2KaHOp5M7SzsvJC5NCcfIGdPMTaZZBRgjJFkGeZyjDbIIlNxpWJrEfoGQmA=,iv:zMIWV2fc6pNZzCaE/v98qLaE4XigoaIVs062dAsota4=,tag:3ZKgQIediXtvlaWHM5fk1w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
