apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:pQZPMI6ZB1dUhFXQgfWYmnu7xFz9zH9zppzZN57Yn6ywlVa6tcp9nnemuElvvEHcPtqB3EDtkTyPq2JZPwBT5ybKVpm6P3Ty4+E=,iv:07xJgmUderPXKzdGlR/l5rXsXQl+F0vBCkYq0EWrjrc=,tag:qY4uJxa5vv5uBi5znCIJ4w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SEJ4ejFLamdVR05YY0pu
            R0ZydGlTR2hUVDRXaUwvVWxYWWs3bU96U1VzCmxHL2FyNGM5alhLM1ZCMnF4azJE
            SGdQUEIyMDRYb3BOTHNUS1JabEVmbFkKLS0tIEZQWWRXV0k2REJXYTF6L2VralBZ
            d1JoWThtcStPNWRtZWtibFZqMGF3aEkKgzL3If5b3xVtL5dXkaBt++PM9frR097Z
            WkBzRJkmt4grMoL0E4SSO0v2TX0i68UHP56iWqY9KPSwEtLMADo4eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T22:13:34Z"
    mac: ENC[AES256_GCM,data:qZ7nyy0+aj6b6cBKxupv+bTGCeEoeHKKmh5I8V2Pv7iIZpgLkFl5LZTjyZf8emy74aG2TbFsOGHgdQk6dT982NNvJqiVeio84MaDW8vkSo7sXpfS6vBquR7mitG6SiEduepHwJ2xywqv1V+OxrGvYpQL9e/URRVitNYhd7EA89A=,iv:qHLj4TE5lCOhH9w6Kc6DxxqUseF64aEC3v7lxOzywPE=,tag:m4z3k8DB3ySYolB8O1dQTw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
