apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:2YYr+aGR+hu9esomHnYOTPCuNE06fN32v20qpYFFf8FKHVHtowAH8HdXD9O7/XC00ILZCExuzkho1RnkJjSxnLGFSjC0BWZihzE=,iv:16MhK0G5QV4F0fgceWlHrRBQ04JkYHHJuY7vvqmKLJs=,tag:qfmToxL2IIzRTagjMIbEtQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U2Y1cUxOa0FlbSt5ZXRu
            VVNVL2hTOVhIVG44eC9vU0tCY1NCTkIrVUVvCkZzeHFLYmJIR3daQkltQWZHVEt4
            TlZBNDRldUp0ZkhTdk0wV3JscVRJYmMKLS0tIEhWZHpqY0ZTZzVLazNYbDREbnZv
            bDVSNGNpYThTUHZ5cWdhVzlYYkdocDgKM+AQ10qbS41VUHlVD/u9RPL3LuYNE3VY
            ovJOUymJO7WhooW4Jve8mggWtEeMXHL/CONNIyN2y0KFzayhf3qTmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-01T17:28:08Z"
    mac: ENC[AES256_GCM,data:uQcG3AwjFaGg4rFXCNMjFbA+icVuLAwMpEH1Ld6KzEBzIFfG38QejXURpdpTaRldbdaBXT1atBMaIXED3+vmIUEOFrjvHFILimkQKtTm5tmH7+fu0zjHJTG/pHMm47NGjP8ol2u+Lh0kTWzluxKb0FQd+BrG89uRxSCb12yviJQ=,iv:y5EhYQTRpQko3OEk44dkVxxREYTVkKMY/nTC+OwFtdI=,tag:2pB4OdgUfv1YeaHvkQbOWg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
