apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:aR/29xrgbYuOTGYsq/YEWEzPh0jKknrXyjmE/jH3n8BPoFnrLDDoJ7AVpDeLmjEGRhs5iHb5JoyIUo3C/Ke0Ra72retExK2JIKk=,iv:lejN3NdxNukUU1AnBfDQvCvlTO4PehZkn5LrMcOZWS0=,tag:Nz0pTPi+VB9rnss4b9gDlQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWlZyc0trR1ZocnFvR1ZU
            NUZmRGs2NjhjeFBweTQvaC9zdXZUZDNMcVJRCjBLUFRlUHZqeWUxK3V2cWphc0la
            YnptRU13U1B5cmZ1a1REa1hiT3BoY1kKLS0tIDFlZWorZDA2WHlwaGg3ZjhaWHdU
            TlB0a09IcGQySXNJOWIwV1FsaGlCaEEK7zZ36PwVyb/SoXkCGw+u3pB1OmrWZwbz
            y7DtIXbIkcwvFIMyyb8ZH5sB+lh5bVIpbf/8Rx9pDynkuOKlIx2CTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T14:53:45Z"
    mac: ENC[AES256_GCM,data:/jhOnzQWLrxJ7uvWz0FGrhM03rKTHUyPL6WEiHPLHYWEF7jdBTb7u4NyCMRJKp6FFpefRAdMwR6YaugZSu/Zjx1MJaxz/m+jaI4TDrL+qtMkRIStflj2QFflIt9T9PZIH7wNUSowyoWd37hKssZcjI5NbyQyMjDqqWSjUIfTYqQ=,iv:z6iJamF64on0rhSwHojtQcTQKRDtmKDbCgOZgjCDQx4=,tag:UePg62TOQrqgmd8IKlSp/A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
