apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:wMKWjbC+vVYnHV/WuWwQN6bq6/aWrgg+EQykiD0Y9xn/FdGvjpAUdhpaz1vju0pFA8hCmLGpFpDRq2JXKTZ1AzGR9FBvMkncz1U=,iv:6BxAGVmN5txsXLR1u6ArKqQ32/EWrz/XyI2Opy4J+7o=,tag:e0bVKRo/PEfp6/LLbxAlgA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L29OVGtMUFN5ZzdXS3d2
            VFd5dGl4cE1VR1d2RFZLR1VSalZiV0Q1RFJrCmlsOE5SYmdiQjROMkpmeGJOb0VV
            cmxubmFhVCs2akJ0OTI5U3BDSTl6TU0KLS0tIHdYa01yRTYrNjkxZnMxdjBxZ1RL
            eG1LazZlLzQyZmhXa2x3SDRGVG1yVmsK4e0mNpy6JlYCqKQyU0wTVzAYtfhFmjjy
            0MCm3Z5STb6AIsBLV4NI68YrMuen2mFsWIVgGxabnhoWWfW8r8Fyew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-02T18:06:06Z"
    mac: ENC[AES256_GCM,data:L2JMrvT8GR8VHdJSTQl8VG3/e5F+nMLFvkBQbQKrRcesTehZsI2jtPKv97YmzaeLXFlKpdLjeXjSu8kSGsXLR0NA3WI+Pt7SIgiqv3MweZ9HKmqkkRZwNUrr3dXa7peik7rom3vyZZXAbHSgHXbtrsA1jf4DsxzcXM1tpMpDRJU=,iv:aDkdekmB+8KrhhUzNKPeyBVqhc7OjfHKue/Oy6Duf1c=,tag:HEKM+n3GlQFqrunvTYNISw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
