apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:rZ07caLSmGIPJxeDNi5U59YyA07T7bxod0eyBeBeXIeI24QY8IM5YAmZHBt2ULftb808ic44gkOsjeIg5LlQ70Htt9SPNnWqgow=,iv:g42TOzlRwE9gXEDDFBfbB06RdFqliX3n6aDeT1/RFTw=,tag:flnnCGVXz2AXDIeBNqTMSA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK09yYWx0UzZhd0F2YkFx
            MFhPeWhpRnp2M0x0Uy9BZWUyLzVuR05SeG4wCnRUbkMyV1pIYjlLcVVyc0puTTdl
            VFQ0dEtrbTl0Wk5DUGxtNDd6cmFGZ1EKLS0tIDd1bUNkbjRTQ1VZZFlxU1J5OVF4
            Q25BWmRhdEhYUXcybVhXcXFpWG02d28KQSl8q3G/IrsBR+zbDEF9WB0vc0IgHw+N
            IEvuC15S8aZnPh5HX/q5XodvWYnH2E2I2asIglvs14XQbTHOb/r9xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T15:33:33Z"
    mac: ENC[AES256_GCM,data:j4Mt4uQD5f44UNJHYIBIfYB0yeCqofyvkKjXTMUjcYzbHE7KlUo7Sd70nXxR8p6uyPn0XBOsJ2V9ApCHrQwihhDGydyDbeXOx9v1pD8jSE6JDU+kC5OsDHfPTttBmflmYLNffd0efrfZB8yIOZ7fFxaUzsPo2FmlGw9GYAQ951g=,iv:4QATrzCWNYS4PkUfnxXPeGejMGoMHoC9RG/c8fFWcos=,tag:SSdX8zQbIvbw7jon/DWRRw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
