apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:77HAanUnGEbv1/KQhuBxCGo7AyauJ0yA7EOjdKt4jY892LvubbpaBvPbhlYVbm1R2KD160csFPAlSpd6F5b0ybJRQGslGZNjte0=,iv:G5hRNBeTKbe16Et7aVkMf99qi/301rB6E0MmsiUjt/U=,tag:LQvvnpRjDeP0x2x629Li2A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNWErM3hWbkhWZExPVXpa
            Z25LTnd1ZnpoTERJOGIwUTdBMHNqc1VJcDNnCnFjbVV2TDVHUXBGMFF4YXZCQVZ2
            MGhUOGhJbUtlWXRHd1NnRkZQZWphTk0KLS0tIEhiY2xZdnd3dGZlYldjeUNpYXhH
            eFliSXJZR3ZDSWJjNFlCY3o4UDJ4UTAKdiFi03CPm6u+G8sX7bglgPrco8XgJCeY
            wkfMv0U3pOSgydF1DeQeSRFx8RfoX3I425xNg0HqawMAsgKECOmn0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T21:16:40Z"
    mac: ENC[AES256_GCM,data:d+yVb3KY+Quh/u3VjbY7av/nWj4ikjgkZZ7y5ne3PZGw42mEVPCOiO3VND4FSOqKqvV4gScmQvTg0nNyJ5jV1NqDE+Ye+yAGIwKAbqpYSslTjeHx+EQSm0+GBC9+idY20yic62qQwKJnWGr8fp7hRG1YXO8ZnsmSaexJil4A8NM=,iv:jz7p4XKXKQBusTC3JjV/90l8vB01xlubwOGwaU9n5aU=,tag:s3gnSi/5JmEl9wiMU/6GDw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
