apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:zYjpYa+0sCQsrA4mP4kNKOj6lE+l1xXscyNTlT/1nvBqyF8sQtFaiWH3NSf3uRcXAz9fwQ7rhSktcBDxm393BQsRt0S5/po4Oro=,iv:Mqyp6CcniP8WEFiTRVKLzIIeiWYoeR3QciPs0JHml8g=,tag:RtCdHVX/LfuPczOJxXdhbw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTnNDK016OGl2SU5rRkZX
            djBPSHU5OG52VlBCQ2VPZks3b2V3VmthREc4CnhjNCtSQk8wQ3VxRHFFclZIb3hr
            S3N3QVplQm9oVjYyaWdLeXpIQkd3WlEKLS0tIGgreFdDTG1CQnVPL1ZKTzJETURi
            SFZURjhseGdnYW8xTENCS2FWZ0hqU1UKQmGxL24pjebrPnGqxMw0AUY4vn4ClxQp
            uQwSmINGt3HOOVwVhX8xdqXl3mSvJfmRz2DLfClXnqrXMfpeAyvQ3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T16:22:06Z"
    mac: ENC[AES256_GCM,data:QWy79xSIi/Xaccbwo+CSrU/fB4D5yJ/sae5MAotOhffYubA5XESmox/7+gEnL1IUP+evtZ4sBCP87LFhMz4ba2vB5r2Yry7ZY6nslfiVb7GPPzAJIHd61TZC42FsGS89iHA5J9zQrd50xxWDYadkJv5HmDWR12RE4wGlMKv2VmM=,iv:725/3szE+Gcm0tagBnOxvAFHYZMV6xfxmpb83oEZNc4=,tag:hyt2sHdmzKSEV/kImCu2DQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
