apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:SfJwv0BQKZfWNvUCF0T2UD0g6uZDavQqLGosJC2v6hjpjVae/wC59RScu9a1JfAVVogvrpFKV5HB4UMdcMxNK+Pj5qya8CrMqAM=,iv:lYcD+PTwEJtNMaegp4oSroOdyPo6e9nDCY+Zr7/oNhc=,tag:nxKko1ptwHDalkxvFuqFwA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bFp6TXBiM241a3R3MjdY
            MEpiVTBNRWxMV0hxMVpGZGlVK3Z1Yk5YM25JCjVNd1JNYkZRdUtSWlkwcXFkbXVy
            RFdIUkdrNUxxV1ltcnorekNCbVRsMGcKLS0tIEltc2l5d1JBa3FxdHRQMmxQQ21r
            ejV2ZllJMDBsYWVMbnc3eDJrOFUwSzgKLgMSxkdHpEiOXavWWkNX1PAR0rTt/pbq
            gt3WWfJlu/sah7/pyh0VYIE4JAvP1+IyywHkg5ingmx7XdZfAux2eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T16:06:21Z"
    mac: ENC[AES256_GCM,data:0vPod86HXRRjv7usuxhpV9IEHMS1NCCrtkpGRa5iO/mK1aVg1QoCvMTtTnDEaDSXXYx1rlHgTLHSvCjbcWQWFUAdlQHZG4yWzxIXVvI4po5BX6TGfR7Wx9xAHvVr/XBnKfkCAk23jgKvJnQg9gPQKu1Mn/1V3xUMaBazrmB4aW0=,iv:JniwVZm6HJRk2ZmFpJsPyJLTkv12YLsrJapYPscGUB0=,tag:KpGtKDH5rOZVW8hb8F362g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
