apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:jsroEvZ74K5PGfaJL4D7acFtOueihZfHZ+C5PbPNsoBR63i0z8wSCQ5bVBVk68SeOTvqc/FEd6Pp6lOhNZvoRP3RCYO3IW5OW+4=,iv:TxvUYPeoGg8Kru7WN02/uj11YpQ58/tTvxdRqmD7afM=,tag:BeTh0PKJklXkPUIOX6LPag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENTZGcG9Lb2NYSUMwOFds
            QlphY1dIbDBNSUZBaGNsM0laQVhkL29qZEcwCjJ5SDlpTnk1UzNSMXhJd25wZzZu
            dGN2NFNXZVRrVG9mbndZc08rMHE4NEEKLS0tIEVoVnZXS29sRS9qSlJFQTJ5UWVZ
            a1dQTVU5OHVwRHpuaDZLYnA0WGFmeFEKAQu3o/rolME8xINPHCixRRLV80LTZ9Xl
            tnV5qMw3fi5xWpD2d3+oV7wCXFynmnLWNbWDMOmTg+KllgkROTsP3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T14:44:37Z"
    mac: ENC[AES256_GCM,data:PNHuKEho0g+cnsmfT8e9BD/ktqNDJf7EVaO35tCD9O5BLMCuW/WYdsAeUMB7DyS2L8HVLYajiB509J/aDnhLhgQ48BL6frfXiA0bSp2O/9vOyfZp80SKml7r5NITGwLxmC6Krlzkw4VFqkpHqJOhgfcXEzsvSvsNZorx2uJTHMQ=,iv:/E0ve3QcsN+a2uUNDdGoKRzl3i/9veWxOksPmsCsG4M=,tag:9aSGsM/B/lonMviGsXfHNg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
