apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:+FVaAkWf6go7jjAYJu63paLiLZ3lXcrwwVPskHkKd4y8mfPKVrGjlp0ymCyb942HRehgUm1624E+xI/Etep5VZjpKTNgN2zInNw=,iv:nMCXnsbaF3VdplNIEofr1diSO3i8fQlv7k5TH3mgAtM=,tag:ZUMTM1ut5/mzJl5juEkakQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbmZTcFJvZGxuUkFHL2Uy
            alROOEE0a0FpVG0ydTI2WjRlU1dUaUs0b1dJCmJiUUVwZ20rOE9WbHp6ckRweWFV
            bk8ydTJUMWdOYkE2L2I2MVl5amMvL1EKLS0tIEJrRXlud3k4dkhWQ1RnUnZhSmxl
            cGlPaVZqMU5Zb0VuVkVXck9RdXdkOGMKK2lrE4IM6QTKzuw+nFF02J+z16V89vWJ
            YegKYul/iz6yYpfAgc0Zar3ZM5ahlSAl2kJzoUSiqp2F6PCvJ9BRJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T22:36:30Z"
    mac: ENC[AES256_GCM,data:wyb194EuALC5PbQVdISPM6EkrYq2ER9Gb3ohhJMZLFl+GZIutkGNR+X3PYriuTm3Sg4FmXsi1T37+ola06TQWFRZRdReqJ6CvYD/qkzEnaZcjmRXpev2uDVtxyQlo4bC4pFEpr8Pl5g4Km0KsWnv8jX5aRuBfKg/i77y8ZVJw/U=,iv:CNGR32q1t6hveC/OceCOjGnxv7cibMU8ZvlPWMvUddY=,tag:aGOLYuoGWsRUctbXKUT4BQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
