---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stash
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: stash
      version: 17.4.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-stash"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: cloudflared
        hosts:
          - host: stash.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
      cache:
        volsync:
          - name: cache
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
      generated:
        volsync:
          - name: generated
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
      metadata:
        volsync:
          - name: metadata
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
      blobs:
        volsync:
          - name: blobs
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
      data:
        volsync:
          - name: data
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0                                                        
      store:
        enabled: true
        existingClaim: mediacol-stash2-nfs-pvc
        mountPath: "/store"
