apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:5PLhMOapDJLzPApvls8bp7suW2LgkB2Am6smv4paFqqOaiOVe61Nox+NSgOtHlBQ6kxeh+cFuhvKhTLRqpGKKY913Q744S2NQSbUQT8lp1SJ9eH4JDYiEdqqMQhb8tcfIcf19tTVzDdal8DPtPQj1egUnzrOFnBltQ==,iv:3cpc34ul0Zif7Ye7h5rhp3BBw1OwEDUcbNcaA0rq17c=,tag:l8m51E2P56QKtQSzdSPeEA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbG40MWxmUHhIcFQ4SmNX
            b3F6UUdaTjVmNmIvK0Vyb3BHYjNGdllHcFNZCnhRNGl4MXFkcUkwajJZblJaR2NY
            MzdsMG5JLzV4VThBSDVBSitGdXBhME0KLS0tIFFya2VSUEEvVDkzSXYyRjhhVzZ6
            U1cwazRCd25uTVdHL2h6amNkdGllbE0KxnkU2rSeKXUKZsVZROCpcGZyVE7XiTu6
            bX1GsHtI7o10ER07HE2UB2AKSZWrDN3GryBTzZ8N9maBfXg8Q9M6Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T20:05:28Z"
    mac: ENC[AES256_GCM,data:KUXAMCj2SYZoWCRKDd6HMzSqXflG6QxPvTkd7KCkGr0yfqWgwFmyDYGVCEuiQ/NqN/TjP432KzzG2L4hbOFuM75vkLvNb7z3E1QGDnKR2XXjEpbJE8GN15EDIgHzySqm5ugGj3ERCN6ED0jBUuh56SHC8FEaDxlR2EECaaRkbug=,iv:/XPbfDplmEeJjFNFOsT8ddCJa3YtPRaB0Ry6isLoXpg=,tag:WqrBRbkxfyoSzJjG3hLSnQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
