apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:RiWtINTEqCuX5ED1bqk8sehpkpT1TG1neHX8GKu279gd1q5OkSTllR21Yj63rK5uYZiErK95ERvqhQQK/EfFHOYHtzsop+AkLkbcXxh58LecmeeuBkXP/AlXsGeOw1zDqqisw0x8FDD6lI0nppTLtUVrP7xMCeidnQ==,iv:Lg2eLRLQ0o9rkI9A4jf02c9qE2irHk2EwESid3Y6tYo=,tag:x5XixYpuFBuZA8C/BUQw0w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa1docnZEaWVVVG5aS1U0
            SzlucXo4M2pqTmlkR1lRWk5HVzRrVnd5VUdFCjZMM0o5NnlqNEcxVFZIZVpvV3Mv
            WXNLNUgrMUNVV01zOTdHMHNOZDR4cDgKLS0tIHRTR2QwUVBZNFI2cURybmJqK3A3
            dE1WNzJES3g1ZU0zWjcrMGIzcUkrTnMKtAIb13wHg9x+ZOhHwyZGVby8C1CVU6zF
            fZW8+VhZJlRXLVMNpFuW/i+F4zYJt5smnEX8W1R+dENKEc81sDRVyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T14:30:11Z"
    mac: ENC[AES256_GCM,data:ibFgBPOBRb31A78AnMKLxti1VYkAauqOfkxqHhm2E5zKMB5IN1DKj3w2lHdBGPtevzf63U5ulNWFcANzpgNw23zNUW4u/5guL6oHIAZ7wg8ip8771LCsGUd+AEDHgW1+Q6/N7p8B3Zk76RZIl9Gfjq0qSjQMA811ZaoFJeVZ2Rg=,iv:hykjoBg0XkLFtI7cAFKNGPrjRohzwO1Am5h/8rOyZb8=,tag:J8DDYoHZY7u/1cQb6PzsJw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
