apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:813fJczoe1wzi1muADSFihzQihlA0yyY27GizmdVh7G6TXQlYVP6/q9yFM5Nb5Sdv13uDpyaP7lG7rFbZSmyCmLosD41tkVxrwh1/B+KHtf9DkhdN+Nkmft7nTKe8d4C707GYvkBOTzzy6K1BPluBaY0URCngw/LUA==,iv:QnGs1ML3C6wOFKWkOBw1w1+Mmju2rnQPD8VqLvn4AgE=,tag:thY7Vx/Q0ecaatRY2huiGQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMnA3QzB2UzdTRjFqV3ov
            cVp0R2p5WTVDTG1Da0QxTnh6ZVNLRHNnYm53CjhLNWZsNjVGTUJwTzVWaDZ2c0tO
            UHMwUk1hTmN2bHVlZVZ1bU9jNDg0T1EKLS0tIGhteWFLaEplYUpmVit2c3dzQktq
            Q1dtZGZwUjVYTGgyWHdnVEswVEJJT28KfQNh2tf3EsTVaGtSXCTDMpbol1g7Kfyg
            6VHfxJI1ANsVypC0SstRaf+T924ovls+jbpTTiGUAZBKUsp+o/N8/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T23:06:16Z"
    mac: ENC[AES256_GCM,data:hfc04wrMMNgq5JjlFMQ3WU6veYgpcKPxi5DvXF7PCdYRq6VVwGGwQTuIi+rKSzqnaUwE1l3/T+jlDtC5RoZen0+06CqZ/xJX7qhIaWUFGEOtwrm0nbNOurcLlOry7O/OSDIju4ynWMIV0qqFaX/Yfj2kmyitHSwsbQKM2YIB0dY=,iv:FGzZGPxJPUft4QaXMd6HQTDmAzeyuDd0yPCNcAtc21o=,tag:q5nUFKLstogB999Ffz3Jow==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
