apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:XrTyV/W4pFM1ib3FPLSy/9Kn7S66nh5qSnf6XBnCDUNU2pQbZSTOYLEoHJrnaywfQyvY5spq5JLQoBZ/RjiY1TNsFp44OTKK+NI1Lfg8XysdL4OUF2sXISGVhpS8TCUS7J6wxzSsqf722f2HY/WEScsTZUxd8qjifg==,iv:2pqgggnTfxKMIe/JWKwPJbWm57dQc50fzIoLtGOsQOY=,tag:OwRhNCSVH5Fui2UisEtykA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N3BuSTNnUDBsSXI5NU54
            ejh3SjBRVlJoMEoybkpwL09aQ1hKN3dOSlR3CkxPUUYwdFdGbkN0bGNkUGx0QTRh
            bUlTc3piV2RKVk15cDk5YXhLeitldzAKLS0tIDd4WndjNG94RjY0ZGNKVzhYS2Rs
            N2FkOUhteWYrZ1BYdWppQ1dpemN2SUEKNl1OEFjEDfOz7lF+5oOR/DmY/auomnWD
            UBvEqQ5uqezFhk0e9VoAK5rgky+koiBNUQ6bet4nkaxfRWGPgDqR2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T06:42:23Z"
    mac: ENC[AES256_GCM,data:ttwmk1yn0zUQPzaQSR1RzBbSjXe5zuMzdbQmc5j3tix0UZ5oewP/KjAP/9DvbOlP+m6OX+v9z1WadWA/r3QqLchE0attJqD+VmzvA5tRsxmQhxrSzfpHjC1RLS1GjeUT9jZfTLNgJYl7miKRhXUa4RSfjEchJJkXaPE+awXR/ss=,iv:F5PhzraWLBxR1lDLpwfTyEDIaq/i2lhx1csuL6BdbBU=,tag:cKQ1EPe/9h0UDLuqkszNCg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
