apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:4XCIaDJq5W6KUGIP5zyzVoPnTsKg+12pbnRpVnNJiRqlK0Oew93Ej2W+egyGUbWnAV+mAzanY5RmPcil0JaejPYWJ4uLO+jTh9g4odwc9zCmVMkuxs5/unrznnUX3NLlCYHVp2YCS8u4Qq+QbB3XgRQzpwTwCoR2nA==,iv:bWgIMwuiAboqcocfh6VMGGUHc6zq2APuyOOLF8fQ34k=,tag:uwGO86SR1X7tnQeGmjp1hA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYzkvUHJ1ZjBSbzRZdzhI
            TjFodTQzYm1NQ3dSSlJWZHA2TnB5NXc3RlQ0CkZRbXN2N3hRR3dWN2xEbmZ5ZGtp
            OXhuajNhcG9xVG55RGJtWVFSVFRReU0KLS0tIGx0MW85eDZZMUFNdW9xSVBDU3h0
            N1dWRjJzcGlKRWd5dDhwQzU4Q0VOS1kKWV1PQXyydWUg6iDzL/1hp4oucJ4ixIlA
            Xee0Z7KtxgPM39aElCBMA5t7SqvZob+bAq4KF+SpPHej/h7e4l8d5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T14:44:37Z"
    mac: ENC[AES256_GCM,data:VECIH5+v7hBVAzF74F4bxSa4sN5JuU+mFUucjnnE5R9jWlRumGZj8gz/NAHpWvVuItiEkOmx+gSRUtR1X+R3qVschT88CJK4rucY/Sw1DgfGPmrNHdr4piFTJCkRlOx0aQavdqIkBj87IvZTj02DyRscH4vyQUSxacMSF6kaG4A=,iv:YQnm4ORy/I6IfQV6ASQrOJW4ZgMEObZ68xh1Bx96NmA=,tag:wwI3EJoaFBmXAQ9ZHlvJrQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
