apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:ewi5aSkfdtcUNZBvq0XJhcYnQG2fltXcjn340y6t5/fRqRJgEDbrY5WAjnLlieFUY7yihrJz8+xOFX5/bwyq6H1/xLV4vbdF1C7BxeYUhobr+PMa1VjCHWP2xIoxxwfkO2cYXP6bPskSBkICRi6ukKcHXKHF1b6U9w==,iv:6ujmxN0nhhvUykl9BM449d8+8WFRjk2AAnm5Wu4sXM4=,tag:X5U8gCR/3m3GzZyndZ6GLw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWTkwMzdEaml2OUl0VEZx
            ODZwQ00xd1JaUk1zMlVxS2Y4cjZzcHhwVW1JCkVHc0RrMkgyWUFmREFOM2I4OWFt
            TjJtazdDZEdvaGZ5WHVlODNvL3VmZEEKLS0tIEVoSEpobmR3TWJqcHhoM0h5S2ly
            bDJESXl3SWlwSWVUQ2hMbnNXNlhtRFkKwyzFA9+VUCGdoFTjGRO+7PjXpb5NFSns
            qA9G9B+OOR8jXVX2v1MqKFtKPy+Y5O9Clq/QHctTXnaWownjRSHLAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T10:20:01Z"
    mac: ENC[AES256_GCM,data:XiHjXXDjk0qcEwAyc/9Hy5j17qaPzEbXYYkD/Ev2PXI6jt6aWVLb+hzo/WwrDViVSl7vNmCO/BWeraY0DCGisEGaSNwxxGZSBx9v8tbNMIDJYGPFZfMzH+V+W9R+zwc1w9/VeJNPkqOhqTOOzt6qrrtYXu8j5TzA04axb65X51Y=,iv:UwfcasgIxdkyHLfmlpCkLXD81/Bia7+HI7tWoNZ7XGs=,tag:n8bnTyFq+5VLVMe9+1hZAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
