apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:rd/BRWu+Q/kSTxyg1ETxWWeqiKuNDqm3G3DAIzgMckNUQYQsGobyymIjti54kbbETrRV9g1cv4vUpt1+lXUO8jTV6R5lZK2jqIlacv2gudq3+vgu4icKw38GT/oeDOgkd2MZr5R6d0FeeISQ7wHD4yyvtK/avTYYyA==,iv:vERFemvGYi+WJyGwRF2hsoxVaz5FcZGXa2De07NJTlw=,tag:O/lLLCS9sazGRFa1r9R66A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MzBtWG9kVkRHR3k1QkNX
            M1FjRG1JMG5uRVJ0VTZQOVNIZ0lqZmxNZTJjCm9QTWM2ODhuYXVwclpiYm5NbmQx
            dHhDSjdONHA5QVZwazF4dFlEUWtQRUkKLS0tIDBrT0JJZmZqbnBOT0QvMy9UNE14
            dTdVWDd1UE9MT2FoZHo0YVFwdVFYMG8KMuvN4pzYR6BqhwnpMEk4Pkw8cOa0a7mz
            GsinJs0odAvNbChzGH/+0H7zPw9F+zhWZBMz956l8+cGm8tvmSjEuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T21:58:52Z"
    mac: ENC[AES256_GCM,data:0f9EWkwcHt2/H0CN5v6DKjgMlZC+tTFldrp62Gk+2ZG7KLjtMXh6sKniMbSm15pnJHO/amMztud70A+It1rUYQPm2Zt+hpyqPG0pbmpuXESpQuCckq8gPqIH7jMfooYXP9uQyTyoDQRK2/wA/bJL840YOYE344TqXvJShJm8b28=,iv:sI6yYIwpUXSjHW7w/m0WiEdijRBfyuCzbbtxttRzxac=,tag:kTwvQU3ojpAc9mkCYgYimA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
