apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:IIr/em9h1L0MAMQD6i/6AhZNGR/7RHAAnlsL9imJhVo9c1e2LuOiOu7p6zVvcbotAa4pavBSL/Q7Zs7daIXgC1LjUq1mj+E910pYkUIA4srA8uR+q6sIvp6pkHEE0hg2gu1QeZpM1LDkbHiUBeyRWif6fUt/gqx8mA==,iv:rtVomlChjKkfj+e7amW3fcqYMvh3SyN1XOmtY6kTUpI=,tag:XwAKs9ZWkGhfz7xI+M8U4g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXajFtYk5TdUZjYWplYnZZ
            UFNDRDB2SGU1WVJ5aGMram5DRVlyVGVCYVdvCjVlLzdaMGVrMXdRUklOQWhHekVV
            OXZpWDgwaEJCQWRtY1pQbzZjSStxSTAKLS0tIHJRdXNCVlZUY0M4NFdnUEpXWWVv
            aC93Q1l2WmVOUmRuK2RGbCtJcGZZL1kKu77PErG3861UVL9uIW1PNw/+NVSKo1OZ
            dD5Umn2vgC6aOlqn1uwXA7CuTo+EGHIDxT3ByHpne3ZLTYZg4lEqTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T15:32:11Z"
    mac: ENC[AES256_GCM,data:eMA1Ob5sVBmqu2nZuHat4LropWqxh5Ujb/f02XRbdQpRr7m3avKy++j/L+eYUtiWJLGFG3UQwH6/3SCzHFFpPr6mLuCIFZkAqUHAKHpsJ3Zz+tpbvtTItbWHuX2T3wxIMZ0IKrSs0m9iOsGpPQz93o9T+MBP8KmAxwMHja1djAA=,iv:tSsiskG2Fab0zMKbz2azzsS2boqKyC6vmVmHi205mww=,tag:OnEuKiYi91tjDzsodxTlpw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
