apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:30tvURoKnw1dKr9TICC+oFeoViCb66FB1PKdzaFcmYIuKxq39YjhNULKm5lfvANnJZdfCvt0VST+W1luE19Jl+mW6ZKOkd4qyougxxHymhM4Z6v0zJy5qby1vr5qIk6DC0bScMeemwupZYrX+cB3nG7k1lZN6lFkJA==,iv:QYXBdZzJVCInGe1fAJQpHGSIa4weaMb/7PfrvmUv/oQ=,tag:8u3SrgFM1VpJFDKVU1WgZA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCLzNYeitrS2xaTVQrSTVw
            aXBHbWluelRBS0RUUkdqMGRoYUJCeFlMMFhFCmlPa2FKV1FiM0diK2RZTXNzU2Nk
            SS9mSk1pcXpyczVBc2t4RkhIN1kwb2MKLS0tIGhNbVptTmpIa25yUjNEdWRYZ1c1
            eXd3MmFuZStwYnpUWURUaHVnTFVpV1EKvvgOIcFmzWW0++F1tp6HpVF7Wwb+YW8q
            2plncX3OYcuU79Ih6clUw0Yc+16mJggNoJqZJfQyKtTpH0amJPWSTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T21:16:40Z"
    mac: ENC[AES256_GCM,data:XYkN/q6qXEGYBGX8jlBbwQ7x2iszhQnEmB3eFm6EqQG1D1mxwIJtYHSAMA/UWR7CxplPyIpqNT6ylQksko8NfodIEfHSzNAD2ZZQ7dZIWKlqHFAQLsdxSBRVon9gvSNRW/wCVw+lp/uvppVYYgXL4vPmMa9GMITdbID+zZTS+mk=,iv:OdJHRHmL1WeR5KxsJSbLxZzBXFtIXo6cH/dgzqwjrBw=,tag:r3cJ2lzZN5bovZKUmtCueA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
