apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:wyARDKOH3p1rwtcaXFaDd/PdA92OlshjmE4ZuUjuJC0cL0jlmUofoP/ziEHNd7CXYD2PC4qsLwkoCawJ5hXKM65eYXF2vJeRR4K+5h0nDmNuP5IDt0AXdM2/oVwsNW19ujugzMlTcxGySFYphT3RhS5/6ov2tm0/ow==,iv:EuqT9Q3XPT/U1nwiyEAoOjuajQRQl8yqOwd97To73II=,tag:PPhQi6EmwSLyRLoi7MJsdw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN2RHMzJVbTB0d0FSY1VP
            S21HKzNtM0xLY3NZeUhMbnhmc1RCTDBiY0JJCnF4d1NBTDQxb2o0YW9aUldlcXVa
            ZVNaeXp5ejliY2IvSU1yMUZaZTJmZTAKLS0tIGhqdldNUWcxa2NZdkJhZW9scXBW
            UkhLOWJoeGxSbzdSUStxSFM4M1hoa1kKxSnjuG6WY01e7XUU/XHBcirn+rZdj2aH
            52avILOGM1qiuwpm+B3IX2O69w/f64L68/acxk4fY7rJwwoRALJaaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T19:52:01Z"
    mac: ENC[AES256_GCM,data:P3iL547Cscl9ga+0faqH+djsvBL+rwf2NNzzW/7IdeVGQqvRrXHVw/UiGjzt6oxwFPJzw8pisVgo5/68c+I7L9aOj7RJgsMwme0XBMmC+I3ekLwpP67IjaQsUcYEQX7vk3TI1tRzChURbpfTfP3DUgAfsPWo67k6AfOVAvSaxNM=,iv:O1ypjWr1qT2tRyYanRrkr5bptJKeCb/KZHHd/jeqZ4k=,tag:+gMDuujll4Q/PphbDBXjsg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
