apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-secret
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:PAgt2irkffNXGss1d98lAgveAhVvg+Ritl3O5PlAfvb1pXdeEDO2q1nQsd1dc/Km2poykS2Sed7qevyDlxw9OwaPDT2S6BQPsBVoP483uLv/x7StvcVraCFF13hhf4lTHiB1f+59m0ccfnBmVgYUrk9Ehz4gedGHIg==,iv:xqyjwFpbmLDGGZ+VGeSVEm+i4ki0UauOSq5coJuSzKw=,tag:raVi9Zb0uFgcn2JvKDJhNw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L21yQlpvUStmVk1uaE5x
            QzZidzltWjVqdWI1Q0hLbW8rS2Qwa3dlWDBzClRuS0VEeG44WC8ycEdiWnFOTkVy
            L0RFelpidVRQSHlFSDVyN0VoUVpReUEKLS0tIGNiSEI5ZFBZUG5pRUlOOUFlQUtZ
            MzEwdjB0bEtEeXYyMWt5cHFrWnY0dWsK25JAiiD+nPKRwRqJf5gt4GuPOIsWZQaQ
            i1bwJRpFTOncMv0NraJ1nbOn3HMGT9Gmw4+xTWp4TI2fONww6x/1zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T19:10:38Z"
    mac: ENC[AES256_GCM,data:8bj62uQUmi/fiMNFzaPVbGTa0tOoiJJtKumFjV578WAoMCNs94E9y/emZ30pu+JZxspe0NOXEN5qAU0x4kaZGWfOiQQQQ9TKYtuFJylDLWrppv7MsUJ2JWMwC9SVifhc8rN03NM/qAGIuEJtxk3SfLCcyTD3OY5GOUZOmL7QTDY=,iv:sTF69+FLSo9jWT0QD95gXYMhCyps6un11Qe1Dfi23m8=,tag:x3BS1L6/sjJZroEcvW6dXA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
