apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ptOue9ftzRMp8zvS,iv:iTuxgnzekqg68rq/Jx17FyvGBtOxEiBZ4+gWp1WwKpo=,tag:DK/LDSQZCdxlQjzC2UepBQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUWRnRlpTUGxXbk5xenE5
            anBVQXNoZWJVa3BWS1djcWwrRG9GT0VMMFRJClJ1aWdPQ3RHVXJtcXNnckUweUVH
            QzFEMG1KOWV2b3Y5aUVDa2xoSmM3bmcKLS0tIDB0ZzBkT1hZZDhjL1JZZG02VHdu
            Q3Z6ajFOTTQ5bXFuODZjZG1iV0NqVG8Ka+wZoVexbK3DtxxARosgcZg942wkrtdR
            7LsK8Uqsx2a238I7EPx4s9MNm+TK35sCBcJJXujfCIw+SSZWcpdIfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T15:32:11Z"
    mac: ENC[AES256_GCM,data:jx1AW2P9EHHY6wD1rmYzTUxhG/oWdYNCubzOs7EgOys36jcNi51ZzmJ8VSUKfpJ655mdh28iczPO1SO16i6YDGe2e+aHF+Sa7f+vgb3C2bj1kM09qPG1OLDG4u9Fr6A3PLseMCGzvnl+Uwa5rDz4fGtRctM28j40XWbvD/ufVAU=,iv:R3oY9XCRjCNBDqBb6A/f0gqir7+axQSlyN6LVllNBWo=,tag:puY2CeHPeOPq380GP1M6Rw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
