apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:luohT2WHJ9Ba548B,iv:Bc6Pp445/lzY5VBLl5CwaD+84TIv9VmXsQHEn5RrXDM=,tag:kn4kf9orvu4Oa+osaZc3Eg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL293cG5sQlQ1Rkpab2xk
            VXlQUmExeFYyR2J6Mit6RW5Qbk1HYk9HVWpZCjZjNHdlVm9ackdwa3h6cmgxK043
            aDcvRWViWVpldkR0UHp6czFtUUlkcUEKLS0tIFNUMWNhQ3lTYmxvd042R2lBS1ZS
            UkQxdDZkUkF3cXRWOXBZV1RqUzJBKzgKKNkIFtys/cs/+NE6/PqqcLU2QXvZUhUg
            op0zxwXTP6vo4J0xZ/rT32WFimzJgUxJZtpP6bBGe28LTXffskGNTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T15:31:07Z"
    mac: ENC[AES256_GCM,data:s5o2HpQS73VSgmZSRgMSG3gNiSke4fASiDDWQ7Xjh6C+qZ3tToxFK+EU2LWjm6ChazbbVyefnwwagFIi2I+g+2LP1CXKB0xDaaqE1rZ5hx/S5AFMRttoPAmROE/Ejz4GsdR1+bVsd7zVlMMChOmM8o1SBa8L7zMeebGwrL//Dyc=,iv:pjKaO6OjAIU66raJqmIqA4y0IXmRyws801nIkRf/MvI=,tag:uldFAaTO1PVwf4FmNR0GAw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
