apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dSA4uZKd+8iJi/1R,iv:jUcSSESDlXXcxeXak0wknlGIRs6rnn0jq0Rd7qy/Ovw=,tag:ow97l1edTs3w6jOn0uyJyg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZnJnZmMzZnloU2FCcXkx
            NU9BbHNGcnZwSFNMczRrL0ZZcWRuU21hbVYwCjFuSmtmQ3loM09UUExnelpuU3I2
            VjloNEdpcE5EbUhpSFZWYkpZL0ZRZjAKLS0tIElOc3gvSEJNeUZPSXpRV3hLYTM4
            aEtmQzJhd3c2Y0MwZlRPTHB6VkVteXMK2hDCrXJBccu0vNHtV2OHQf+xxz339dqj
            CbC1pGRnDZpGBAVQmHJw6L78rtJT9g/SL3s2CFK4Pj2xpoveM0KJZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T06:42:23Z"
    mac: ENC[AES256_GCM,data:rrdUSSnBBNIBVcwmrC948+JaSSASQ6oHop3k63OiGeIJy/tR+3WCtOr8ZiRM2KYbhX1/exqZb1hr4722DUpbA1wRVJJltmXnIcesNgBqeWsXWrOR1v1B2FF69OmDkeaEROUyC3e9hlurkX5oXQogzW5PBjKddXKbk5SUiqEejXM=,iv:S+/7gTD75TDFnbeAF/SGxgeaChl77rSN5lr72yXgiPg=,tag:aMunUbjksNA2xedfM1khjw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
