apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uWYJ1GYdpgcjwYbp,iv:nxXn50iuQdKtPI+9/9Br1hGlJbnUrW0gw3klsO6RFf8=,tag:W45WHrKrfjbDDa+pZm1V8g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZktwNzg1ZGRxS3NZSlh0
            a0F6NEhBUE1qOVdTOU9wMEovR3h2TGNZTlJBCm5TSW0wd25BU3ozcElDb0N5TmNR
            Z1JmbzFpZEVMY0s4UXdSWE9KdVQrMzQKLS0tIHNLak4vbXhRRTUySWRZbkVWdEtP
            OVJyQzF2eldJdVNJRHFZc041Ulp4dmsKQal3B1OLHdCMPleXN1QsRc6v10QZpyvv
            oBxNc53Uhy1U3NysEgqib7389ciOwdzXZHJipC8o475/0LUvUe1iFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T19:10:38Z"
    mac: ENC[AES256_GCM,data:vP6gav0AHXphgJTU2wMhjT7e8MKPEvJEJ6FyKqVNGmlM/4aR+9tx1tB/iroEoPkH1EKUMqFwuAf9iDqabaSeHsc7s3GiqLHZeYJ7nrEko2/S1x/UzW4gOJQGSvv1uAaPCPpddJ8fqfCa55+MEmFRMcRFv65/xNsVLkLVZ+GpFZg=,iv:1LDqu/paNi7jUpvD4gI5HTBtY3ETyplzhnA9JXmObO4=,tag:Gy4b0AYyNdbu/smUavEiYQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
