apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:QmOXHn1vHbIgeuyw,iv:C5iue5qVXe06Iizdq3j8AXtLv3zagiMAvidVETk6kFg=,tag:I4Yb/t1IckXphh92kCCnJQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMlNyK3lsYjRHSU1yOFhG
            TSs0VENaTWI1WjJvRmJlbzgwZVNLTnZIbEZ3ClJWTFJpN1MvM2ZZcElaUitwREVK
            ZUU2dmdSZCsyKzNxMGJwblVnMHZzb1UKLS0tIDdnR2FlbWw0aEJodHZGU21KVjR4
            RFZLZlhuVU1TZys0dU1pdUc3VVlZUDQKwUMccSgcZyQ4pEasWmwNGhR3Y9+3miM4
            abdLcrl2syMNT6N1rY4Pj84ohP2GW1c7Avvfi4b6nFYDC0NTaq34gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T12:41:52Z"
    mac: ENC[AES256_GCM,data:GhKVSmOb7jODjhI5ZezR0Inxr1UemoNhrh7OepUUraBJlfMFMOAbMInZzqNEUPFzRVf2ZOh9PFtVJTDFh+rFZuhRnAMt3RROqP0wSUFxYrhWTjx24Dkansi2TdHWvNhft29aA7o3VqhXXdhHyCVICclFH0c8zvGRIuUstdXwcSA=,iv:rS5MScgFXBzYwagWj7q029WvYHYEwoziQTmfZ8TgemI=,tag:enuAjx3bU0lmtCImnnTHag==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
