apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dOaYZTbqjRgnUBXC,iv:F3h87l4v/KSgHiYgpDqZQSQuPEYkAN/5QL3YpJN+hrw=,tag:Ji5Y3u+qFeLltuiO0mApZw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZzFSaXdwU0xYcEJWdWgz
            aEtJT3dxT0d0cXp4VGwvNXZBaHFaQ0JoTG1VCmVNeXlkWTJmREFSTU8vR2EyU1h3
            ZVVEVy80N3Jpc090aEJqY3pOWXZnL1kKLS0tIGxSaVVmTmVXTlo2VkN2TGV5TjhI
            Ym1odWtaOE92U0xFam03QThpVVk2MjgK1Hyw3DJnQo4oVi7KYU2IQXFEh2EDgq+f
            TMfW8WFN6iRqKKWpJPaE34nuAhzkj9BSf8GfSCnuJQg9yx+dINy2IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T22:36:30Z"
    mac: ENC[AES256_GCM,data:M17ZQynp7GpjiHiWQPNcJyvuas+kwm0uRyJx+CmKN67vwnlh4m8buuazvpskMw9IGvtcM8ClworghGfgarQm9r2IkQFQS5ybJsrTY5+XD5stNGZm94FQbN9HiSFnwa5FschWc27pG8O35KKLqRC/Bi1K3V+SQGwdsnsgAcZVyBc=,iv:i6syD1x6r31GLD+Nbuj6ExiOVtYUDAh8ZBKoxbux2x8=,tag:I2yXsagjzkOtzQZ/L3OVdA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
