apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sKQ10okrBoIiBEEM,iv:GSP+6f9wMZV2AgyLRIx+me8YqxFiTuQHy46jZLXoTcw=,tag:u2w18XERN6PQ62CnLi8dXQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RFJQZTlQRldpcjhlZElj
            T0FQTXRzTEs4cWlDU0Uxbm9teUtzWXZhTWlNCldkOTFuYkJweHJqM2VWWkswMVVE
            VmhjYWtkcnpBM3p0VFlhMWRhQXl5OGsKLS0tIHpjMWoyWVVxK3hyTFpoS3dFY1Ry
            dlFFdGFIbTE2ZGM0NVJyeGZPOGQrckUKLRhc4lWclNu7VOHlP4hnqITgR+SdfRMW
            cwAfnFN1IzfViixE/Fvw93IOCWE3LACwerzCIdTDPv5JgZz3K315jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T17:51:25Z"
    mac: ENC[AES256_GCM,data:qfdhGpn6RQY5oBv2wL0M96yCYwYTlYztBhfD7K3kdMnBa6/wG5/mwa9bigPfhXhAaLxCz8REMcuwWtKl26GoSlP2NHJ2vvR2yqRZiYcrfzwFlXLD3xMaBi/A+Q/vwGNB08xoS1eiKJNxlgysNPt5EUDZYx7Q06gKHmrz4Kh8JjI=,iv:s3i4/LlRdr4lus358VLrwaQPQ06RSqRkLcpzmG4G8K0=,tag:avrinmmQKszxrrQx0CinVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
