apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:AuPqDJ91b16AADzG,iv:9BfSTunnUeaG/s8odC6EzXCPuYhP+Or1CpotsbLwiMM=,tag:4qbcDIPHNwb79QSnKdi2Fw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOGlwOEFIUU8rbEhHS1pv
            Z1UxK0pCVGVEcjVoM1BLNnF6ZGVxcWs3K2drCnVRZGU3Ty9YVy9ITUlUMWozQmpa
            amp1VUNZamFwQXVZcUhua0YwaUxocHcKLS0tIGF4YkNmUEdrQlVFRXRoZ0JyZ0Ir
            N21MVjB4azUzNGdXRGJ3cVJWRTBXZFEK/fFYC1e3HtFULr6pCVFYNUnPHc11eB+9
            WyQ8qhYzMd98W/zdmY149UQTfViQxeFTK9aS3nFp1IgMgoyoaMSbNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T07:04:19Z"
    mac: ENC[AES256_GCM,data:k38N/eS0ZXETC2J2uC+fWp5GEggcUzeXS1vEzcqYF3pShOmgspclQHEWw5IXk3kfWqERyANnbWx5//Ue8WoreUq3+LDeWEUP5S7pRPbD5iZw19tffYaDZtsrSESeFargXk+9oKiiYe+IELV2vRNPxnkS6hENPNliNEw0bwa3JrQ=,iv:Q0LiC8mjVBTJpy1UEaJhSKal0Vvwah51FhHU18GgT4I=,tag:jiRUGKRsv92Puv9CTeu6xw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
