apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:pXIrxWup+R9QFomF,iv:LqDYS1JArXDCJxpUhoNpGW9lSQATZmLyaLpjqwp7IdY=,tag:rsO3aiyzNugCxGKG+8TZLg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBub0gwSjdnTkpZdDBUWjdR
            Y25pSnU1RXdPMEpobVdRWkwvKzNCZ2ljNWhBCmRvbnU2UVdLWEJxZGhCRXZlcDdp
            NlFWZVBuamZRYm5oNGlTS25YUHJFdkkKLS0tIHZmcnBEMkFqRkNxcDhIKzFDUG51
            N2k2SndRdEJtaUs0cms2RkJ2Y2tjTVkKmGUykLs/cA1pRlxCqjWMXMKnhjKBFl7+
            H62bN7XWuS2XnQhEzzfJ7+HoeKWiYNnzQlw+6KizhJ8aFHuE+V6g4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T14:53:45Z"
    mac: ENC[AES256_GCM,data:8S1QnNnGIfUv3x9v6Cos2EVlOFve7DzYDa7D2GEYGAdClBz8Uqmp56KRhmq/ozjSzOK+Pb6hNcixMzwyDblHsE8+kar7S2m60+vzyXQpqSWJwhszOFkZ8ikotvPcq7GJHqQHWtRJ4uu3LCAgjfs6hyXOhCKme4WDl6FxBXISGQk=,iv:PxBzkd2JftWTzv8gFSrGoAi4WQTq8ezvY0DCeEdTAHE=,tag:JsTvhc/KAmNj0HKDU1c2YQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
