apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:s38q7YPqpQ3ga4y7,iv:ySM+sdP5RHOLKKoohRJbcE++hnxvgoI1tNxRqfzEzWg=,tag:x0ZuZJu9QzDESHiW1GfEvA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVzFtaS9zL29QQmVrVXhi
            alhOb21hVE5lbm9ScnlDeTluZHdZU29lZXp3CjhyMHcyc3hia1h5dGxwdC95TTc0
            dWsrVUNTSCt5U3Vza3J2Sk1vOTg0VGMKLS0tIE5YYWRHZ2tqWXRoYkZnWHhRMXRn
            UmpUbUl6TGRkM2NrOEZWLzhiWGxqc2sKR1iW0SnUf8UUjeVZc8s9LY25NoDol4jL
            xmN93ObQjy/SbO4bjhAiK5uOMmoBc8yPhPJRuUow3NVx0HWpGmaA/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T20:05:28Z"
    mac: ENC[AES256_GCM,data:p8iUOzsKcgyeGTwXrlENp4Ldn3cjvxpWZZrweR3SxdQEP0Rn8Bsd6S9DoiGkuM+Oj3qq/tOSIyOENhd4EO6/Qb3CjiYDPW77SJ8i13puiwgVhqst4c8toGoS+8M5L6wV5EVSYdPL9vQQ0A1DRPgb7hlJxPJDffdpZJAJFidOKYI=,iv:aA1dQBhzCfr7OwaUP51R4b5xgCdy484ZTYArVNLE82A=,tag:eP4B13U9YV1b2YMQ/J2wqg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
