apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:KdGIqJDcXBLriuue,iv:rb8rjIcl54R7DV4e/DlgEESiOg/vX3q0tvmBWXeVS8A=,tag:9NDu/yenWZZyVfiiN6lEsg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bjBRVjVyVmtRaHdZaUFQ
            ZWYwek1WYXFzVi9RN2p5VWFmWWlVdnZjWHc0CmM1bkNkUFBKbkV2SW1WQk9ITkpR
            SkMzR3F5UTM5aHRla3VDZVZGdXNDQXcKLS0tIFpCWjBPbHNabTlTTHBOTjVWbnFC
            dlNRS00vd2V0MitEaVZYYXl3MlduaVEKcYUKn1nTxoRGgrHyWHhzQwG5OVRnyZv+
            qnKHHcHSAUzbluU/+FQKlX+TxX7FLXsNt7NhNA6Vz79Bo976J1fiwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T12:06:33Z"
    mac: ENC[AES256_GCM,data:n5zBTji6kjwgKZC9+v7w4Q95Ebi/vyitSO5MBjAUN7G+RGNgPi1yxAsIP75JAuRQC5d08UUfCNZ7sYyPk2sheD4Vcl9XXjMYYWHr6+kzZJQ4vKEijfU/1/7jkc15IqYTIxh45cva/N35NFu1nItyIYpvvdr3Kpxp+yuziwxdOWc=,iv:rLjXKH23tLPIOXAx1tx/Yvy6PnCVIFLJiI65CuP3MKI=,tag:ip5m6TpAnKcWQur2IoXh0g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
