apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:N758NHYXHY9Rp/yt,iv:jtVQzntxf7HfJMOH+ABqBpWEdC5dATaT3V2mQ07t/AI=,tag:rkqJV923rcQFtrP45THUFg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ09iNFRiNU5pVG5LeFIw
            QmZDdjZETDNzVGZwbTA4R3FoZytZbFNEeG1vCjhRZXJOMHMrWXBJWVBvNFc5aS9r
            VW1nclZ6OS9SdWd5NFdTRktzZ1NUcVEKLS0tIHpoQ2VEL0hWWlp6YVNlSFQ4VW9s
            OGpacjRobWpTdDVNbklMRk84alJUdmsKO5m6GqdStB1dfusibXfbeUdvYdsIyAAs
            yme4PI6en722Uh6MTX78x59GBxLV96tsdOrBTajDcUqJYBNp2b2SKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T21:58:52Z"
    mac: ENC[AES256_GCM,data:qRo+hgVyymoBStXuouj33cLQOl3DRWxgPetNaPr9g4hvtJcxIVjjzO1KuTpyeDZ9b1BH1rTSemNzOdEtvDcfKwhLwLdYovSC8U8B2NjjsOwEJ+pac3w48EXpoGaVztg/qeAWG0+AJZrlv/oPErQEx7b8Bm/YrWrka8ylLihemtU=,iv:A/Q6Vss4bSJbbfP7N1DncczwLXCkzRB0cQk79+j4pTM=,tag:pYobeU2d0D8Z1UK1VsE+oA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
