apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:iR7eS9ZyD3raukgD,iv:bN5HmYUHI9AWKO6Uu93Ww9f6pCd7jY5N+w7znKZWqns=,tag:cM7HooJSJsEZUu50hvOi4w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Wk1Dc1AxQjVQUlFZdjVr
            Q3VlQW1NVlcwSDh2REhmWG1tVEJacmU0bUhRClNWcU5Hbm9VNE9lTDdPRXZWamFD
            K3BtZmxKdksxMHU4SUJZOGIySEtHQncKLS0tIGErMHhsT2IvT1hETGxWRjlOYm1a
            ampza3JMK0JnS2QwSGdHSituZ3o3TnMKmoykUpXJoIdYBIDLTYlNPxmpY+iDLqnU
            1OVhyRhHkNiGfh4gzO+hfumLtdlSgztE4adi0qJzsu8hiLVzQBeRUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T18:29:28Z"
    mac: ENC[AES256_GCM,data:qBtJ0KxrrWiGzZ8Clw8ylCUdCaNvIi2MEoNWGwHFlrzHmjaeOi/FMKZbY1y3IGXYs98Y0SdQnF2PC0tYsh8BEHcR5LZ6JLFR4cCFP0kTVXD5DWkuT2p1LKYjaonaH1tdvhLXAIKBcsDARCOWcG2o4M4nt4RvADrzjmzbpzbg1Cs=,iv:EpX1KRG1QE6DWu2iayyx1NZ/AjEfkmMEtuRbJor2yEw=,tag:0Ejz/fjzFTSCWYzJVFbqkg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
