apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uLIqoB+cfjlYmXOh,iv:hCXUQRMHNYZ2aWAuQw1Ojd3SIROM24nGnOCB8mbV3Tc=,tag:6TG0cGwYFW26R/adWo7CPg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTEdMMVJEUFhYTVFGdG5n
            N3dWNUhSOEFSWERmSmpsbm5FVTlnQUV3OHc0ClcvcHFhT2JqbjEvbTBFcVM1RjVN
            WHFBblhZSytqb25OOTYycFErZUV0TWMKLS0tIDB5VnJHeE9hamtkbTVvT3RHcS9T
            M1h4SmNxSUNpUWMrbjd0OXlxTEhSZjQKpRwI8BOfk68w/8M7k2NxCkKrkjyk/7i0
            4mqsBE3hICPfQl3NKfFfm8rqkZIGfZVzT5gMDMTBw/eYq8Hq2zLs0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T14:44:37Z"
    mac: ENC[AES256_GCM,data:pHJjP/CakLJeMvmwlAVgDZCpUn5SwG3ZsFqksESvGuQ1ZAWmcTNAcHb4qow1ecVb8XfBVIPij3Fwa7J9AAIgeeDnj1dUHktO1t6cxbHNGau0D43dZ0BJSbyi2z9KHEHMazLHFFntid6V8fLw6dWUbQTyHS9BVqmS4ivVTJnDd+A=,iv:o5OuNKX7F3f8V83AfNmj82DDkOLQ9Rgjvqrsb3DhPvE=,tag:vfm5oswb8u2ikvkfij8BLw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
