apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1+JNwek6j708vdRg,iv:tvcMLTvrd756kmGkBLRFaQPI74d1hDHhRfqx4W2phNw=,tag:6bDuN3/2gQsxlSJVeL0YPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VzRQc29LQXhEemFyRjNr
            ZUQ1anZ1ODhoSjJCSlhUNzN5bkdEYStQUFhzCmk2RHErNE1YYlNJenBYVEJRRyt4
            V09wMEMyUHlXK3lRL0kyY2RTV0dWN0kKLS0tIHdmbzJ3M0lGVXVIcXd5TU1kY2Fl
            ZE1qakRKNVFGMHAxOGZwVHVnRytwcTAKlTlFIqxSSifd9BOJn8AyhcraQ+l/Lw7u
            8lVUTVka/NtnkIqGkh/Kvxgus7Nc+2hJIMxIy9N6dRk7WVwvPbQ1Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T10:20:01Z"
    mac: ENC[AES256_GCM,data:E5d7pwA2AMFtuB4jT5D7/urWvNkykDB1xegruIeeEPxFHImHSRwzZPA/9qvXfi9r4OXMqgNdAxIaBnuvSd6MJqgJ5sawnEfjHY/gc2lIcc2u8UKIY7F2NYh+ZOD2Mop12UyF81MWFb9acnRkPGcKnUUXK9mTUm7HoEPRM0vaPdY=,iv:ESihmkPePZ2NDVhIoIZebRYbDsXABvhxup+zyEpKTi4=,tag:CYDPJmN1uLMXtDXd/XAFHw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
