apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:F379ICSgtP3d2jBJ,iv:wRTa21h6OeVPO7NaaJBfq9gRO8kFe3EMr9lJrqfXTOo=,tag:GoMGTGSJ9E67Nm1AjmE/fw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQjNDazlPLzBnWE1Rd3Rw
            VnN5bmxoZWtzQXp3VlRQQWQrallEUTR6Q2tRCjNvbFJHUjhCRmV3VXVVRGwxZjJ0
            SWgzb2hPdWk5L2pCcUEyOFlxMHpGbjgKLS0tIFZNMTRJSU5VaEtrcEo3ay9oTzlk
            dnFZZWRkUElsOWFyeEhKTnhUMkNVTXMKjFfYbDifHjeLvt3cDSCrZMKQXKifB3dM
            tGREdwM2uG1RDpiXSdO3yMaAKsFbP2zbwtzyiDubRBQxVgUrA9pE4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T23:06:16Z"
    mac: ENC[AES256_GCM,data:V6eTjEPip78mkSy0LgZKq+T3YSlsLnbbdDgidbKwbbu1kz1uw59FoGdbYhCEJ5JFz/D5gUXHrgZJoN0L2Hi1gSU1y0SVHlEugtMexePqKs1wI+bZUtYRTqkSoNQb1pjyXa1vTkQAVU+bEIpAKDTqYs1W0KsuyD3UnJ5FlkkDbzI=,iv:TrKuTWSOMnVnHX6Aun07fzMWP8gwF1d+23t4r/AAC2g=,tag:GhpotQx1wJd4PgajPa/qfg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
