apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:YgHw3NUhgNeIG5mm,iv:ZKfX3h6Sphs9AQoxAk1wn9hEYFfBK0dNU5FWIdwTyrQ=,tag:356pqKUciIiCKmFpZ3Whdg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OXpubFhZaDNvSWVGaEVQ
            cXFZZ21MYUVPcVpjL2c4ZGtWbk81eWprVURjCmpTUURYWEZaY2ovT050UTE1TVZJ
            UElsbzBYV1doQ05pMzVaMFc2ZW1NU0kKLS0tIFI0Z0VrUjRCTVJrMGhibE9xTFIv
            dXNzaWY1cW1RSEdTdG1QS0VwemZUcmcKfbZpS/DZ9/MHNbgziB5gZcw3fezuvn1D
            I/LgaQ5FT5dDTP+ldjT5s2NaEv6UR5KzXbUyjrcXiGuB5g4W/Pn93A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T23:26:22Z"
    mac: ENC[AES256_GCM,data:q2cmOT4mU+kB3qJoTvTC/zHK35V16qyN412GdA04Ys370cLPOH5OZwfKciL/WOxVu/jfvh7+3rwV76JENkCMVrjidptdOLQMfskmhl8rKHKm1rSYOFF58jdMYn2Y4Je7ioH4oZ/j+juHl3gTQ1c2Da3SA3YYdmEGevMdCi5+n3E=,iv:yre7/6SBWzvITXppS/SkpUiYL7XhaVeghPB3UABakDE=,tag:gUQ2bKbdogQk2+52eeJsqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
