apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:tztVf1Jq9QEE8Wa7,iv:EDwqQEEw7FOvxuNN0NFsDT4DTsOOSeZCoi41Zib4jgY=,tag:o2zmlRwJGY7vFSwB+2BteA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaVdia2dFVVVCa1Z2bisy
            VE9zOE5PZTdKVW9neG9aSE0vMEwwVmpPK1dNCjRreXNqMTI0SHorN1d4TmQyMUNC
            RGZyQjhDM1VXNTlBeUJlMUdON2V3ZDAKLS0tIE5JSUZodXZHSGp6WHpuRkE4ckI2
            anYwWGxpaFZJM3JzWndGaEd5dThVSlUKBupUoqeJ6n8X0q1H8JT2ybGlcRasgG6H
            kdZzPL191iGHjhfJJK89ITUQe5IVffH3Oz+MPhioNz3nVhpcYyfsyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T22:49:14Z"
    mac: ENC[AES256_GCM,data:k0MOYtpXjbJanWrdFdgfrq9xHUM0ZIejuULoL1p27jP2RZs8fKRh3kMlZ/0CHD+oaB/L3CdYDj5Ivfr6z9DsLqb+ELyDidC1mKqbhBNe9wapsOnxH2/dsH1fa592pB2nIVF4Mp3XCzlBkIM4u7VHtybpNjTaVK9iwjQBlZEqZtQ=,iv:X8XH3y5Y4SgEDCeB6Cs01qGhITv78duzYUoK5fWEGUA=,tag:oT5k/Nmw6BbHmn6FThYKTw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
