apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:usUeqqke53byxbM3,iv:ZBUOXY9BFeZcH802Z6VporOjKtfQJZTedXCFuT3QFTk=,tag:tnTetB4X9dvUciNcu4HGrw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRFJxUXcvZWNqZW9CaTds
            aVE1bHhTZUVXc1c0VWN5V0doeXVia2tqRndFCkYwMkYreEZjU2hkbzRhY3V3WWQ0
            ODVSY1Q3dWw5Z1dicWg1V2tuWmxxSE0KLS0tIGhoV1I0a2hvdVMxOUNrV0FEd0d0
            c25TS0lOYUZuZVlCZVVEOVlPWXBlMkEKCUJQ3p9rNW3tqwG/jP6gUs27eYrNxaor
            0LpWFgVBwfZCQO9u9hza1r8PMYLHhQWFuPS0ZLtse75dek+lNw2pDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T14:30:11Z"
    mac: ENC[AES256_GCM,data:nT6t/1TmSq7Z8s6m3dqXiFYkYLSveXm5j+S02t2ynTaM3vRTGv9lcTadXAkwDRWdkmtApLv6m0C5ve2fbfOdXvg54NxyXe4MMCWH8u2QcmpS3Bzmnp7OEtztV6ipvAurYN+Q7mYGDvLiBRaS/0ddHv1oMSO7JomB4IT7zoR3hzQ=,iv:VKXB2bpgUUAlRii34/E5+QYy7dLsbo9vEpN0y3m/JGU=,tag:lD5YlTx84U+07vSd2FiPvA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
