apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4ecxKRO4dk26vWtj,iv:hJ4k+9FU5Gug6wvjxe8kq+ivnNAoUH0nyUTMqz5vSV8=,tag:selrg/CM/QS6HSCEbFVN+Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cTlpTDFDeU9obXM2Z05F
            bXZkRGxtRWl0Q2pQTzRnOXhLWmhwcVFMS1ZRCnN6a1FVN1dmVk9XM0hZWitmTW1Z
            RG9vRDhiVUgydlViZWwrME84OVZKVVUKLS0tIHlHRklDcStZN2VjejZvYnQwUzVm
            MmI5ZXhscE1Bek5XNFhsZC91NVdvbGcKjbWxPuVhtsBod/RW3iueYl1CE0xBZ/jx
            NAFH0WgvbISrc2UaQFmXOBuBJqTD21Vkci/8h2UEPSaL7RKL6syAdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T15:16:11Z"
    mac: ENC[AES256_GCM,data:xytWNHNlbJ5zjxcBB+ToLCEcsYZq8lPcQHhQjvGaR9yzCnRymOgg5sRcdGMFX8u1ClhCFMIg5of7wHQDgHykmMGfsFK3rhhlloRjLQLz8dGW8Yc84q3343UVxVmV58QaJPZ9nW0nfF1Ck40AWPr7JsDnAMn+6TJkjI9QMpgDNJk=,iv:rrQwJDQUaJ6pGy2+Xkeu141Zjz5baofLjopih2tsOBA=,tag:R8SY2mBiqI0h4osIsAHhZw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
