apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:TW9hkT9QF7vKE00t,iv:NV0/+ZM3BsSjBj1mK7vRhoP6rhLXr4fvrkcjIwbyzco=,tag:5hC4o4JR4ujkmZox13tdNw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdUZVSDFXOWN1cmZCT0FD
            Q3BPeXFzY0hJQU5rbWhqcHNHYzlXbjhZd0FvClExRWpXWnVlcVFXWDZuSnJNaUo0
            a3YwdHpUeFhLRTN5cjJYZ3lPR2lBTGsKLS0tIDMwR1V3S3FrVEF1QWFydmtaZnlk
            L0k1clA4MlIvMVc2YUJTWjJ2b3k5UWMK9P9v2yP6JgEKnyMxQ3kVbSrKasPeqft+
            hbmGk7YDCfNZpr6AKvkaUYU+q757H85m2TDCseqZfMfVnIXySu/Nog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T19:52:01Z"
    mac: ENC[AES256_GCM,data:8Im+nE1bQ0nDeNOnMG9YCjJ9D1a8a3Koh9aUsDyfRqYwUNY7Xx4NQP6HC4Dqj3L4+CqEbf2IVUgxBDeTkT8TKVDzwEyd9HMcGqpt8bzTFLqnookVVUulB6eGV4LP42EjP3m0VnWtjGmZ6Sq5EJQ+2BA5gW0Pwx9hIoTB21jXAdY=,iv:a6iSfkuaxKHyZ1yPq5qiQFlMa/I/I4YWfAWOy7gJmtk=,tag:OEzumrXiQV7wdjQJ24dwjg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
