apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:iQvOqWno1maAa0Tn,iv:q5abPpvWp2ZcWqiX+PxzRNK/I38vkc10gAg6OOxwi3g=,tag:tQZMeFtmiFsBinHsodif+w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age10njf5h964qqukpp8jwgkej8m6u3m86f2ex77fwlp4ehtu70cwpdsqu8rjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYlZjOElRaHUvMGt5OXhP
            cjg2RUJFNUg3L2FoODhFWEFpWVdUaSsyVFNNCnkyVU9xbVB1WFRYWXdaMzdjeTBQ
            Z1BwZjdkY3ViRTFoQWYzM0ZhN1Z0aEEKLS0tIFVNRVBYd3lkd29CUGVsNklNSDJq
            UmhsVWFFZm82WEs1dElHZW44bGVSTzQKw7Eo4zridPj5H1PdwGmbZku1fM0oHPWC
            usLz74e58nwPkW1v6tFkV0xSRNrRYLP75g9YBbVzSm2fVqxC/514pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T17:32:38Z"
    mac: ENC[AES256_GCM,data:8RjMLzSkhuc3aATXwd7p8z2i1LQpHryr6uxYgZa476sUXs0BwwhW6AtwToJzNFfilseSRZ3Ipn+QQg/bHnRXhKSPlVHWBg/XToDiiWBr3t1BBQxbwLCLN95vL9vHRkM4tR0ADXvaBKqVSzC+Gxiyq8npMzVG6Qb5z80vBb/oBBE=,iv:2wVNJOkNrB2UjOtKVlo5kHdStgjrHga3gAGFvlP7HVc=,tag:NIpziWMnw5dXxqz7uMeZ+g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
