---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 9.3.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision      
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-homepage"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: cloudflared
        hosts:
          - host: home.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0    
      public:
        enabled: true
        mountPath: /app/public/images
        volsync:
          - name: public
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0  
    addons:
      codeserver:
        # -- Enable running a code-server container in the pod
        enabled: true
        ingress:
          enabled: true
          integrations:
            traefik:
              enabled: true
            certManager:
              enabled: true
              certificateIssuer: cloudflared
          hosts:
            - host: homeedit.${BASE_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
          tls: []
