apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pi-redirect
  namespace: traefik
spec:
  redirectRegex:
    permanent: true
    regex: "^https?://([\\w.-]+)/admin(.*)$"
    replacement: "https://${1}${2}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pi-prefix
  namespace: traefik
spec:
  addPrefix:
    prefix: /admin