apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pi-redirect
  namespace: traefik
spec:
  redirectRegex:
    permanent: true
    regex: "^https://pihole.domain.com/?$"
    replacement: "https://pihole.domain.com/admin"