---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: "${WEAVEHASH}"
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: cloudflared
        cert-manager.io/private-key-rotation-policy: Always
        traefik.frontend.passHostHeader: "false"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      host: gitops.${DOMAIN_0}
      paths:
        - /
      pathType: Prefix
      tls:
        - hosts:
            - gitops.${DOMAIN_0}
          secretName: flux-system-weave-gitops
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
      additionalRules:
        - apiGroups: ["infra.contrib.fluxcd.io"]
          resources: ["terraforms"]
          verbs: ["get", "list", "patch"]
    annotations:
      reloader.stakater.com/auto: "true"
