---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: feedcord
  namespace: feedcord
spec:
  interval: 15m
  chart:
    spec:
      chart: feedcord
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision      
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    configmap:
      feedcord-config:
        enabled: false
    persistence:
      feedcord-config:
        enabled: true
        type: secret
        name: feedcord-config
        mountPath: /app/config/appsettings.json
        objectName: feedcord-config
        readOnly: true
        subPath: appsettings.json