---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: linkwarden
      version: 6.10.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision      
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    config:
      nextauth_url: "${LKURL}"
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-linkwarden"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
            - websecure
          certManager:
            enabled: true
            certificateIssuer: cloudflared
        hosts:
          - host: link.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        volsync:
          - name: data
            type: restic
            credentials: s3
            dest:
              enabled: true
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
            src:
              enabled: true
              trigger:
                schedule: "0 1 * * *"
              moverSecurityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0    
    cnpg:
      main:
        cluster:
          singleNode: true
        backups:
          enabled: true
          credentials: s3
        recovery:
          method: object_store
          credentials: s3
