apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:TPyrj05rWeGidfPszSA5bg8E0FKEetDUxSpGnWCDb1v2NfgqFZOFpjjDaOocJtarmmi2+CHmX0dw4RsK96ZKJuRGzOwWz6S3tjpFTsGHAEi1VfmIQnmTeArOxP5SAA==,iv:RjteFXOi7hOM5Xe83813xp0VGtGgdDI83re9r7fNmME=,tag:8k8uwY9XKw/cO7QDO15GRw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Fqi3BjhONA==,iv:OcaGAaJw1wG1+onkdkJn+4JI+TrZW2eWbyQUIkp8Dqw=,tag:0YVlB86SpNLKpLv6QXIGEQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:t9JSQ4yVmlivCrCCUtrn/uFN,iv:E5E7uZyyV6Zxyk/L3x6XL1AQNn9I5NIdcXGqHApHlBM=,tag:+15lwRVLHuCm2QFYCOLYnQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xx2hgmxtll6gxchzszxfr0j2n2fujw3kkx3d4kktyc99ceex336seqg5m3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOS91V3E5cFRHYnNzSC9H
            cDErN1VKbHVDUG40UFAvWmdMRkhFdjR2cXhBCmxNOUh4L1cydXNJaHU2S0tMVFNB
            OHFKbEFjb1lsN09ibi8xV1lPOHgvazgKLS0tIGxHc3pYNnRuMnNuc2ozd0k2KzhK
            Q0J1OU16K1FHSWFVNHU4dUcxdXJNRWMKl8Fu+UsxZ4TSmvn6lCRghuUqUGfYR2s8
            nRICPICK/dqKHoSISJyab4lIOb3fF3/OEd7EWfPHBhLPjY1GoUhH0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T21:15:59Z"
    mac: ENC[AES256_GCM,data:7W6Of46UZ9C8pvb8A+L6pTFMk2skeYytZOOAyXre2vKAopZio4r/Aj6pkOKOd/Ub4A/e4/vI30IWwO8NC3JkcwqA78cHt7LQH8rcbdoqQv/rP+qXyssCyip7OKAs5oKRLGQkakDCj2xSn0tS7OtqsBaXNJjWrzFRPUB9DO3nLgs=,iv:lXXih+Q6aKGivjEDtYPWlsSg+MXBRteIyJn5zEGh/as=,tag:U89IyT9UEMhad9slASJfdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
