---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: "https://plex.${BASE_DOMAIN}, https://plex.${BASE_DOMAIN}:32400"
      disableGDM: false
      requireHTTPS: false

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PLEX_CLAIM: "${PLEX_CLAIM}"    
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
    
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: cloudflared
        hosts:
          - host: plex.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    
    persistence:
      stash1:
        enabled: true
        existingClaim: mediacol-stash1-nfs-pvc
        mountPath: "/data/stash1"
      stash2:
        enabled: true
        existingClaim: mediacol-stash2-nfs-pvc
        mountPath: "/data/stash2"
      media:
        enabled: true
        existingClaim: mediacol-nfs-pvc
        mountPath: "/data/media"

    addons:
      codeserver:
        # -- Enable running a code-server container in the pod
        enabled: true
        ingress:
          enabled: true
          integrations:
            traefik:
              enabled: true
            certManager:
              enabled: true
              certificateIssuer: cloudflared
          hosts:
            - host: plexedit.${BASE_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
          tls: []