apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unifi
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/networking/unifi/app
  prune: true
  suspend: true
  sourceRef:
    kind: GitRepository
    name: cluster
