apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-tls
  namespace: traefik
spec:
  secretName: traefik-tls-0
  issuerRef:
    name: cloudflared
    kind: ClusterIssuer
  dnsNames:
    - traefik.${DOMAIN_0}
