---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 34.4.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    additionalArguments:
      - "--entrypoints.websecure.http.middlewares=traefik-chain-basic@kubernetescrd"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
    deployment:
      enabled: true
      replicas: 2
    dashboard:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.io/ip-allocated-from-pool: main
        metallb.io/loadBalancerIPs: ${TRAEFIK_IP}
      spec:
        externalTrafficPolicy: Local
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        namespaces: []
        publishedService:
          enabled: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: "certificate-issuer-cloudflared-wildcard"
    ingressRoute:
      dashboard:
        enabled: true
    experimental:
      fastProxy:
        enabled: true
    ports:
      traefik:
        expose:
          default: true
      web:
        redirections:
          port: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
