---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: filebrowser
      version: 11.7.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                FB_NOAUTH: noauth
                FB_ADDRESS: ""
                FB_BASEURL: ""
                FB_DATABASE: "/database/filebrowser.db"
                FB_CONFIG: "/config/filebrowser.json"
                FB_ROOT: "/data"
                FB_PORT: "{{ .Values.service.main.ports.main.port }}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            entrypoints:
            - websecure
            middlewares:
              - name: auth
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: cloudflared
        hosts:
          - host: files.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        mountPath: "/data"
      stash1:
        enabled: true
        existingClaim: mediacol-stash1-nfs-pvc
        mountPath: "/data/stash1"
      stash2:
        enabled: true
        existingClaim: mediacol-stash2-nfs-pvc
        mountPath: "/data/stash2"
      media:
        enabled: true
        existingClaim: mediacol-nfs-pvc
        mountPath: "/data/media"
      books:
        enabled: true
        existingClaim: library-nfs-pvc
        mountPath: "/data/books"
      docsconsume:
        enabled: true
        existingClaim: documents-consume-nfs-pvc
        mountPath: "/data/docsc"
      docsstore:
        enabled: true
        existingClaim: documents-store-nfs-pvc
        mountPath: "/data/docss"
