---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: filebrowser
      version: 11.3.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-filebrowser"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: cloudflare
        hosts:
          - host: files.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              cacheCapacity: 10Gi
              enabled: true
      database:
        volsync:
          - name: database
            type: restic
            credentials: s3
            dest:
              cacheCapacity: 10Gi
              enabled: true
            src:
              cacheCapacity: 10Gi
              enabled: true
      data:
        storageClass: longhorn
        enabled: true
        mountPath: /data
      stash1:
        enabled: true
        existingClaim: media-stash1-nfs-pvc
        mountPath: "/data/stash1"
      stash2:
        enabled: true
        existingClaim: media-stash2-nfs-pvc
        mountPath: "data/stash2"
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: "data/media"
      books:
        enabled: true
        existingClaim: books-nfs-pvc
        mountPath: "data/books"
      docsconsume:
        enabled: true
        existingClaim: docs-consume-nfs-pvc
        mountPath: "data/docsc"
      docsstore:
        enabled: true
        existingClaim: docs-store-nfs-pvc
        mountPath: "data/docss"
