apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WpOblZ9pX0pFhBYzw87A8VutMxQ4lcYIUkeOLMa/Xc8=,iv:DFBwKFsHtiWtvfoRK5/K3RYamA7KvEOb7xloy/n8bq0=,tag:sZ40Vi96nzg5XcMd9LRMHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xx2hgmxtll6gxchzszxfr0j2n2fujw3kkx3d4kktyc99ceex336seqg5m3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYU5uQkU4VG01eXFYa1Ft
            SkRiMVJNcUVsUmJTZUZnVUdNNFNJbERzM1JRCndVYm1lQ3NzWDNYUG5IMzVLSHMv
            aWZNWUZuRkR1bkJBNUk3ZkJVUmhMYmsKLS0tIHcyNFZJOWNNbXczRTFYaHRVYnds
            NVdDVmcxazE2amhLWmIrMCtwRmF1N2MKwkZvShJYbh1skeyTsqVwS7XgG1tHGj9B
            Em2ECqJjbHULSFjSIP9v71lSD7emp4ujuN47nW35QbdgUVIplRwjBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T21:15:59Z"
    mac: ENC[AES256_GCM,data:T77oqbZ6dDUOnQ3Xv/ugg4mfB7aesd+1ZFXTH0XxmwLI7s8KNEgMXbh5/i7wuZ7KjUgR9oQCZ8uLvszOorv6DhOBRxbpXhNkf4g0rhS+kym1FQ8FtNbUNpWgq0Lfs7LtQfbCOhufLXDKah4ZjvJRLb1jHQw7/ezGGB7XuKtSRq4=,iv:9YLcLKcoXFLbnmz8zrq97ei9g6nOLriCEg3/VajYgNA=,tag:pkU2EtdQQfUO+2/NBTLiug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
