---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
  pull_request_target:
    branches: ["main"]

jobs:
  main:
    name: Labeler - Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v2.1.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Labeler
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: "${{ steps.app-token.outputs.token }}"
          configuration-path: .github/labeler.yaml