name: Lint Helm Releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Lint Helm Releases
        run: |
          # Find all .yaml files in the specified directory structure
          for file in $(find kubernetes -type f -name '*.yaml'); do
            echo "Linting $file"
            helm lint $file
          done
