name: CI

on: [pull_request]

jobs:
  hrval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find Helm Release Files
        id: find-releases
        run: |
          echo "##[set-output name=paths;]$(find . -type f -name 'helm-release.yaml' -print | tr '\n' ',')"

      - name: Validate Helm Releases
        uses: tenna-llc/hrval-action@master
        with:
          helmRelease: ${{ steps.find-releases.outputs.paths }}
        env:
          HRVAL_BASE_BRANCH: ${{ github.base_ref }}
          HRVAL_HEAD_BRANCH: ${{ github.head_ref }}
