---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Pull Request: Validate"

on:
  pull_request:
    branches: ["main"]
    paths: ["clusters/main/kubernetes/**"]
concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true
env:
  KUBERNETES_DIR: ./clusters/main/kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Homebrew
        run: |
          export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> "$GITHUB_PATH"
      - name: Setup Homebrew Tools
        uses: tecolicom/actions-use-homebrew-tools@b9c066b79607fa3d71e0be05d7003bb75fd9ff34 # v1
        with:
          tools: fluxcd/tap/flux kubeconform kustomize
      - name: Run kubeconform
        shell: bash
        run: bash ./scripts/kubeconform.sh ${{ env.KUBERNETES_DIR }}
  flux-test:
    name: Flux Local - Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Substitute placeholder
        uses: faradaytrs/substitute-secrets-action@8974be5ae47e1b03886cec98e5c2f00061684207 # 2.3
        with:
          input: 'clusters/main/kubernetes/**/*.yaml'
          substitutionRegex: '\$\{(\w+)\}'
          substitutionData: '{"S3URL":"https://placeholder.example"}'
          throwOnDataMissing: false
      - name: Run flux-local test
        uses: docker://ghcr.io/allenporter/flux-local:v7.5.6@sha256:725baade5b3d01ab6b1be0fb1de0d454e4222cbe959b3bdddee1137464aa1f3e
        with:
          args: >-
            test
            --all-namespaces
            --api-versions=monitoring.coreos.com/v1
            --enable-helm
      - name: Undo any changes (if needed)
        run: |
          git checkout -- clusters/main/kubernetes/
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: pull
      - name: Substitute placeholder
        uses: faradaytrs/substitute-secrets-action@8974be5ae47e1b03886cec98e5c2f00061684207 # 2.3
        with:
          input: 'pull/clusters/main/kubernetes/**/*.yaml'
          substitutionRegex: '\$\{(\w+)\}'
          substitutionData: '{"S3URL":"https://placeholder.example"}'
          throwOnDataMissing: false
      - name: Checkout Default Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: "${{ github.event.repository.default_branch }}"
          path: default
      - name: Substitute placeholder
        uses: faradaytrs/substitute-secrets-action@8974be5ae47e1b03886cec98e5c2f00061684207 # 2.3
        with:
          input: 'default/clusters/main/kubernetes/**/*.yaml'
          substitutionRegex: '\$\{(\w+)\}'
          substitutionData: '{"S3URL":"https://placeholder.example"}'
          throwOnDataMissing: false
      - name: Diff HelmReleases
        uses: ./pull/.github/actions/helm-diff
        with:
          retries: 3
      - name: Diff Kustomizations
        uses: docker://ghcr.io/allenporter/flux-local:v7.5.6@sha256:725baade5b3d01ab6b1be0fb1de0d454e4222cbe959b3bdddee1137464aa1f3e
        with:
          args: >
            diff kustomization
            --unified 6
            --path /github/workspace/pull/
            --path-orig /github/workspace/default/
            --strip-attrs "helm.sh/chart,checksum/config,checksum/redis,checksum/secrets,app.kubernetes.io/version,chart,app"
            --limit-bytes 10000
            --all-namespaces
            --sources "cluster"
            --output-file diff-kustomization.patch
      - name: Generate Merged Diff
        id: diff
        run: |
          {
            echo "diff<<EOF" >> $GITHUB_OUTPUT
      
            echo "### HelmRelease Diff" >> $GITHUB_OUTPUT
            echo '```diff' >> $GITHUB_OUTPUT
            cat diff-helmrelease.patch >> $GITHUB_OUTPUT
            echo '```' >> $GITHUB_OUTPUT
      
            echo "" >> $GITHUB_OUTPUT
      
            echo "### Kustomization Diff" >> $GITHUB_OUTPUT
            echo '```diff' >> $GITHUB_OUTPUT
            cat diff-kustomization.patch >> $GITHUB_OUTPUT
            echo '```' >> $GITHUB_OUTPUT
      
            echo "EOF" >> $GITHUB_OUTPUT
          }
      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add Comment
        uses: marocchino/sticky-pull-request-comment@d2ad0de260ae8b0235ce059e63f2949ba9e05943 # v2.9.3
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          header: ${{ github.event.pull_request.number }}/kubernetes/diff
          message: ${{ steps.diff.outputs.diff }}

  automerge-and-approve:
    needs:
      - kubeconform
      - flux-diff
      - flux-test
    permissions:
      pull-requests: write
      contents: write
    name: Automerge and Approve build
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - name: automerge
        uses: pascalgn/automerge-action@7961b8b5eec56cc088c140b56d864285eabd3f67 # v0.16.4
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          UPDATE_RETRIES: 12
          UPDATE_RETRY_SLEEP: 60000
          MERGE_METHOD: squash
