name: Retry Flux HelmRelease Diff

description: Diff HelmReleases using flux-local with retries

inputs:
  retries:
    description: "Number of retries"
    required: false
    default: "3"

runs:
  using: "composite"
  steps:
    - name: Run diff with retries
      shell: bash
      run: |
        RETRIES=${{ inputs.retries }}
        COUNT=0
        until [ $COUNT -ge $RETRIES ]
        do
          docker run --rm \
            --user "$(id -u):$(id -g)"
            -v "${{ github.workspace }}:/github/workspace" \
            ghcr.io/allenporter/flux-local:v7.4.0@sha256:b27388b65df42dd3ec4208aebd8d50ed55a2f555b6a81926849897202ffeb06c \
            diff helmrelease \
            --unified 6 \
            --path /github/workspace/pull/ \
            --path-orig /github/workspace/default/ \
            --strip-attrs "helm.sh/chart,checksum/config,checksum/redis,checksum/secrets,app.kubernetes.io/version,chart,app" \
            --limit-bytes 10000 \
            --all-namespaces \
            --sources "cluster" \
            --output-file diff-helmrelease.patch \
            --api-versions=monitoring.coreos.com/v1 && break
          COUNT=$((COUNT+1))
          echo "Retry $COUNT/$RETRIES failed. Retrying in 5s..."
          sleep 5
        done

        if [ $COUNT -eq $RETRIES ]; then
          echo "All $RETRIES attempts failed"
          exit 1
        fi
