---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docs-consume-nfs-pv
  namespace: media
spec:
  storageClassName: docs-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.118
    path: "/mnt/media/filing/consume"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-consume-nfs-pvc
  namespace: media
spec:
  storageClassName: docs-nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docs-store-nfs-pv
  namespace: media
spec:
  storageClassName: docs-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.118
    path: "/mnt/media/filing/store"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-store-nfs-pvc
  namespace: media
spec:
  storageClassName: docs-nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi