apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: documents-nfs
provisioner: nfs.csi.k8s.io
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: documents-consume-nfs-pv
  namespace: media
spec:
  storageClassName: documents-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.118
    path: "/mnt/media/filing/consume"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documents-consume-nfs-pvc
  namespace: media
spec:
  storageClassName: documents-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: documents-store-nfs-pv
  namespace: media
spec:
  storageClassName: documents-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.118
    path: "/mnt/media/filing/store"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documents-store-nfs-pvc
  namespace: media
spec:
  storageClassName: documents-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi