apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - calibre-web/ks.yaml
  - calibre2/ks.yaml
  - documents-nfs-pvc.yaml
  - library-nfs-pvc.yaml
  - mediacol-nfs-pvc.yaml
  - filebrowser/ks.yaml
  - stash/ks.yaml
  - stash2/ks.yaml
  - plex/ks.yaml
  - paperless-ngx/ks.yaml
  - kavita/ks.yaml
