apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: library-nfs
provisioner: nfs.csi.k8s.io
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: library-nfs-pv
  namespace: media
spec:
  storageClassName: library-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.118
    path: "/mnt/media/calibre"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-nfs-pvc
  namespace: media
spec:
  storageClassName: library-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi