apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mediacol-nfs
provisioner: nfs.csi.k8s.io
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediacol-nfs-pv
  namespace: media
spec:
  storageClassName: mediacol-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.118
    path: "/mnt/media/mediashare"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediacol-nfs-pvc
  namespace: media
spec:
  storageClassName: mediacol-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediacol-stash1-nfs-pv
  namespace: media
spec:
  storageClassName: mediacol-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.118
    path: "/mnt/media/stash/misc"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediacol-stash1-nfs-pvc
  namespace: media
spec:
  storageClassName: mediacol-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediacol-stash2-nfs-pv
  namespace: media
spec:
  storageClassName: mediacol-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.50.118
    path: "/mnt/media/stash-rm"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediacol-stash2-nfs-pvc
  namespace: media
spec:
  storageClassName: mediacol-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
